### ISSUE TITLE
Expose volume level on TVOCall

### ISSUE THREAD

**Issue by goldsmith** [twilio/voice-quickstart-ios#106]
We want to render current audio volume levels/connection strength for our users. Please expose the inputVolume and outputVolume on TVOCall or TVOCallDelegate, as was supported in the Twilio.js Client.

Right now we are trying to capture the "call quality sample" log output from TVORTCMonitor as a workaround but we can't get it working. Other short term solutions are welcome.

**Comment by goldsmith** [comment]
Any update on this?

**Comment by ceaglest** [comment]
Hey @goldsmith,

Thanks for the feature request! I don't have any immediate solutions that will work with the current releases of Twilio Voice, but I will discuss this with our team.

As you point out `TVORTCMonitor` is internally capturing audio levels as part of our Voice Insights reporting, but we haven't bubbled the same information up to our public APIs yet. Your best bet in the short term is probably the (inelegant) parsing solution.

I'll keep this ticket up to date once I have more to share.

Regards,
Chris Eagleston

**Comment by piyushtank** [comment]
Our latest SDK provides APIs for stats where volume level is accessible. See [this](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta2/docs/Classes/TVOLocalAudioTrackStats.html#//api/name/audioLevel) for local audio volume level, and [this](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta2/docs/Classes/TVORemoteAudioTrackStats.html#//api/name/audioLevel) for remote party's audio track.

Closing the old ticket as the latest SDK provides the requested information.
