### ISSUE TITLE
Outgoing call failing randomly

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-ios#119]
Some of our customers have reported that outgoing calls are failing randomly i.e. sometimes they work and sometimes don't. Since the issue is random, they are not able to provide exact steps of the issue. But, when I tried to reproduce it from my end, I was able to do so by trying to make calls in very poor network using the Network Link Adapter. In this case `callDidFailWithError` delegate was getting called. When I logged the localizedDescription of the error, it said : 

> Generic error (503)

I have set the log level to verbose and was able to get all the logs. I am attaching the log file here.
[Twilio-OutgoingCallError.pdf](https://github.com/twilio/voice-quickstart-swift/files/1801545/Twilio-OutgoingCallError.pdf)

Le me know the possible workaround for this problem.

I would also like to know that apart from network issues, what are other possible causes when `callDidFailError` gets called

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

There are a number of possibilities that could cause Twilio Voice calls to fail, but the `503` error code typically means the mobile client is having trouble reaching to the Twilio service based using the device network connection. I've checked the SDK log and unfortunately it seems the DNS resolution failed while the mobile client was trying to connect to the Twilio server.

-bobie

**Comment by GuntisTreulands** [comment]
I have also noticed this, and also in case of poor network. But in my case - calls simply time out (notification is not sent to the other side).

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Thanks for your reply.

I would like to know what could be the other causes when `callDidFailWithError` delegate gets called and how to handle the errors thrown by Twilio SDK for different reasons.

Thanks.

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

For the error codes and possible causes, please take a look at the `TVOErrors.h` inside the library package.

**Comment by piyushtank** [comment]
Our new SDK is more stable and provides more meaningful error codes. 
I am closing this old ticket but feel free to reopen if you run into any issues.
