### ISSUE TITLE
Audio disruption when custom connecting sound

### ISSUE THREAD

**Issue by sochalewski** [twilio/voice-quickstart-ios#143]
### Description

Our app uses custom ring tones sound when connecting an outgoing call. It's played via `AVAudioPlayer` object. Unfortunately, there are various audio disruptions in outgoing ring tones.

It seems to be connected with Twilio, because it plays fine when no calls in progress.

### Steps to Reproduce

1. Make a call (WiFi or LTE)
2. Listen to the outgoing rings
3. Note any disruptions (change in volume, momentary cut out, silence)

#### Code

```swift
let call = TwilioVoice.call(…)

do {
    self.player = try AVAudioPlayer(contentsOf: self.sounds.encryptedDialTone)
} catch {
    print(error)
}
        
guard let player = player else { return }

player.prepareToPlay()
player.currentTime = 0
player.numberOfLoops = -1
player.play()
```

#### Expected Behavior

No audio disruption.

#### Actual Behavior

Audio disruption occurs.

#### Reproduces How Often

Almost every time

#### Voice iOS SDK

2.0.4 via CocoaPods

#### Xcode

9.4

#### iOS Version

11.4

#### iOS Device

iPhone 8

**Comment by bchen-twilio** [comment]
Hi @sochalewski 

Thanks for reporting the issue.
Currently the Voice iOS SDK does not fully support custom ringtone playback while the call connecting.
Is the custom ringtone played when the app starts the call and stopped when the `callDidConnect:` callback is received?

-bobie

**Comment by sochalewski** [comment]
Yes, that's exactly the way we handle it. Do you know when we can expect a full support for custom ringtones?

**Comment by bchen-twilio** [comment]
Hi @sochalewski 

Thanks for confirming the implementation. We are working on the new version of the Voice SDK with a better and much customizable audio device API, which should give you better control for such case.
Currently I'd suggest that the application call `TwilioVoice.call()` after the custom ringtone playback is done (~2 sec duration).

Sorry for the inconvenience.
-bobie

**Comment by spacedema** [comment]
Hi!
Have the same issue. Waiting for full support for custom ringtones too.

**Comment by piyushtank** [comment]
Our sample app provides an example code on how to play a custom ringback tone, see [this](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L658).
Also, we have an epic in backlogs for `call sounds` where developers can play sounds based on the call state. The feature is in discovery mode right now and it's in our roadmap.

Feel free to re-open the ticket if you have more questions.
