### ISSUE TITLE
Phones are receiving completed calls when being turned on again.

### ISSUE THREAD

**Issue by fmonsalvo** [twilio/voice-quickstart-ios#181]
### Description
We are experiencing a situation where calls are reaching phones after they restart or are turned on again.
The case is as follows:
- Phone is turned off.
- Twilio makes a call, the call completes since the phone is off.
- The phone is turned on, and the completed call notifications starts the call again.

### Steps to Reproduce

1. Turn a Phone off.
2.  Make a call to the phone that is off (Using client ID).
3. Wait for the call to end due to the phone not being reachable.
4. Turn on the phone.
5. The phone will receive a call as if the completed call is happening now.

#### Expected Behavior
When the phone is turned on, the call should not appear.

#### Actual Behavior

The phone receives the call.

#### Reproduces How Often

100% of the times.

### Versions
iOS: 2.0.0 via CocoaPods
#### Xcode

10.0.0

#### iOS Version

Several versions are affected.

#### iOS Device

Several devices are affected

**Comment by piyushtank** [comment]
@fmonsalvo I apologize for the delay in response. 
Did you unregister your phone before switching off? 

Our invite model is push notification based - if your phone is registered with Twilio Infrastructure before you switch off, and if the registration is not expired when a call is made, Twilio infrastructure will try to send push notification invite. 

Let me know if you have any questions.

**Comment by fmonsalvo** [comment]
Hi @piyushtank sorry for the delay in my response.
Not sure I'm following. The phone being turned off is not something I can manage, so I cannot unregister a user. Also, when we started using Twilio there was no way to unregister a registered user. We asked around several people in the team and that was the answer at the time. Is there a way to unregister a user now?
Anyway, as I said before, I do not have control over the phone being turned off, so I'm not sure I can unregister when that happens. Also, I do not want to unregister the user, since I won't be able to register again once the phone is turned on again.
Thanks!

**Comment by piyushtank** [comment]
@fmonsalvo You are correct, an app can not manage when user switches off the device. I agree, the unregister APIs cannot be useful either. Unfortunately, there is no straight forward solution to this issue right now but we are discussing this issue internally, on how to fix this problem for developers. One of the solution SDK could implement is by adding a timestamp on the call, but we are still brain storming on how to fix this issue in our SDK.

To your question -
> Is there a way to unregister a user now?

Yes, see [this](https://media.twiliocdn.com/sdk/ios/voice/releases/2.0.7/docs/Classes/TwilioVoice.html#//api/name/unregisterWithAccessToken:deviceToken:completion:). The device should not receive any incoming calls after it is unregistered.

I will update this ticket when I have updates. I apologize for the inconvenience.

Best,
Piyush

**Comment by fmonsalvo** [comment]
Great! Thanks for the reply @piyushtank.
We'll wait for a solution.
Let me know if we can help finding the solution or testing it!

**Comment by piyushtank** [comment]
@fmonsalvo  In 2.1.x and 5.x, we configure the `apns-expiration` field to 30 seconds to ensure callees don’t receive VoIP push notifications for calls that have already expired. 

Closing this old ticket, but feel free to reopen if you run into the issue.
