### ISSUE TITLE
Disabling auto muting in conference calls

### ISSUE THREAD

**Issue by nxz91** [twilio/voice-quickstart-ios#193]
Hi everyone,

Is there a way to disable the auto muting of non-speaking participants in a conference? I'm seeing that this can be irritating in some scenarios, specifically when only two people are on the conference.

I'm interested in the other features of conferencing, specifically the ability to announce something into a conference, so I would like to keep using the Twilio conferencing system, but the auto muting is a no-go because it irritates our users and prevents a natural conversation flow to develop in the named two people scenario.

Thank you!
Leonard

**Comment by bchen-twilio** [comment]
Hi @nxz91 

Thanks for reporting the issue. Although the mobile SDK has nothing to do with the mute behavior of the `<Conference>` TwiML, but this is still an odd experience. Do you mind providing us a Call SID so I can ask the experts of the Twilio Voice service team to have a look?

Thanks
bobie

**Comment by nxz91** [comment]
Hi @bchen-twilio 

Thank you! A conference where this happened was CF1563ae1c5b5499edb67f8b562b206299 and the call legs were CAa885c681ac1d76f0a99be050ae9989e4 and CAbd6b697166804ff265bb980039b8c8f1

Any idea what happened?

Thank you!
Leonard

**Comment by bchen-twilio** [comment]
Thanks @nxz91 for providing us the SIDs. We will get back to you soon as we have any findings from the service team.

**Comment by nxz91** [comment]
Did you already find something out? It's happening constantly – we've just had this call:

`CFae9f677aba9cfda74fcad46e89642025 and CFe9c13cc71a8afdcee01f1229fe3e6b19`

with these calls:
`
CA1d2eb2f399dbcb00306d41ab2ce3e6e4
CA717683868a99f1c10366fc450ceb5683
CA99812bc1b99b889c8ddb068c8f27ea96
CA91dd16ab8c632062968b4ae41a101c25`
