### ISSUE TITLE
Vice is not audible at first time 

### ISSUE THREAD

**Issue by devlove1C** [twilio/voice-quickstart-ios#210]
**Hello @bchen-twilio , 
I’m getting issue for VOIP call confirmation voice. Many time we tried to call for confirmation voice is not audible at first time(When user is receiving first call for confirmation it’s not audible, after first call its working fine) and user get stuck for confirmation.
We’ve tried and found "handleCallInviteReceived" method return “ "audio_level_out" = 0” in  this case voice is not audible. When  “audio_level_out ” return greater then 0 then voice audible.
Please suggest to me, how to solve this issue.:** 

I’m using below SDK :
* TwilioVoice 2.7.0 with  CallKit
* Server: twilio-php 5.16.6 (updated with 5.16.0)
* Devices: Iphone X (iOS Version 12+)
* Language: SWift 4.0 

**handle call recivce below object details** 
```
Inside statsToSample:, call quality sample: {
    "audio_level_in" = 0;
    "audio_level_out" = 0;
    "call_sid" ="callSidIDXYZ";
    jitter = 0;
    mos = 1;
    "packets_lost" = 0;
    "packets_lost_fraction" = 0;
    "packets_received" = 0;
    rtt = 0;
    timestamp = "2019-02-09T19:20:02.048+05:30";
    "timestamp_ms" = 1549720202048;
    "total_bytes_received" = 0;
    "total_bytes_sent" = 0;
    "total_packets_lost" = 0;
    "total_packets_received" = 0;
    "total_packets_sent" = 0;
}
```

Thanks

**Comment by bchen-twilio** [comment]
Hi @devlove1C 

Sorry for my lack of response.
This is an audio device bug of the 2.0 SDK which has been fixed and greatly improved by the [Audio Device API](https://github.com/twilio/voice-quickstart-swift/tree/3.x#audio-device-apis) of the 3.0 Voice SDK. You can follow the new [CallKit integration guide](https://github.com/twilio/voice-quickstart-swift/tree/3.x#callkit) and we are more than happy to help you in case you run into any issue.

Thanks,
-bobie

**Comment by piyushtank** [comment]
We have already released AudioDevice APIs. Closing this old ticket but feel free to re-open if you run into the issue.
