### ISSUE TITLE
CLIENT-4943 Restrictive networks may fail unless ICE servers are provided via TVOConnectOptions or TVOAcceptOptions.

### ISSUE THREAD

**Issue by kieronlawson** [twilio/voice-quickstart-ios#225]
Hi,

We're prepping our app to support the 3.0 SDK. Regarding CLIENT-4943 - it would be helpful to understand which call/network scenarios would be impacted by this issue.

For example:
 - are peer to peer calls impacted?
 - are calls connected to Twilio voice conferences potentially impacted?
 - what error condition will we experience on failure in this scenario?

Thanks
Kieron

**Comment by piyushtank** [comment]
@kieronlawson Thanks for reaching out to us. 

The 3.x SDKs network connectivity requirements are the same as 2.x. [This document](https://support.twilio.com/hc/en-us/articles/223180888-What-are-Twilio-Client-s-Network-Connectivity-Requirements-) describes the signaling and media IP/Port and firewall settings requirements for network connectivity. Please review and let me know if you have any questions.

> are peer to peer calls impacted? 

YES
> are calls connected to Twilio voice conferences potentially impacted?

YES
> what error condition will we experience on failure in this scenario?

You will observe the call will go `TVOCallStateRinging`  to `TVOCallStateDisconnected` on the issued `[TwilioVoice connectWith..:]` requests.


Let me know if you have any questions.

**Comment by idelgado** [comment]
Hi.

The network connectivity requirements for 3.0 are different than 2.0. There are 2 main differences. The first is that all signaling occurs on server port 443, whereas, previously 2.X used port 10194, as noted in this [support doc](https://support.twilio.com/hc/en-us/articles/223180888-What-are-Twilio-Client-s-Network-Connectivity-Requirements-). Additionally, the media connection is established using a protocol called ICE. All calls are routed through a media server, and media is served over UDP. In rare cases, a network firewall may block UDP traffic entirely. Only in these cases would a TCP based ICE TURN server provide you with a relay connection to send and receive media. You can provide ICE servers from https://www.twilio.com/docs/stun-turn or use another third-party service.

> are peer to peer calls impacted?

Calls are never peer to peer, they are always routed through a media server.

> are calls connected to Twilio voice conferences potentially impacted?

Any call that is initiated or accepted may be impacted if the client is in a network environment that blocks UDP traffic and an ICE server that can relay media via TCP. You can provide ICE servers as follows. Note that the same applies when accepting a call via a `TVOCallInvite`.

```Swift
TVOConnectOptions *connectOptions = [TVOConnectOptions optionsWithAccessToken:accessToken
                                                                            block:^(TVOConnectOptionsBuilder *builder) {
    builder.iceOptions = weakSelf.iceOptions;
}];
self.call = [TwilioVoice connectWithOptions:connectOptions delegate:callDelegateObserver];
```

> what error condition will we experience on failure in this scenario?

The `didFailToConnectWithError` delegate callback will be raised with the following error: https://www.twilio.com/docs/api/errors/53405

We are working on improving our documentation in this area and I will follow up with a link to docs in the future.

**Comment by kieronlawson** [comment]
Thanks for the detailed response @idelgado. All makes sense. 

We will adjust our onboarding process to reflect the new network requirements for new customers, although they're not significantly different from 2.0.  Our experience has been that around 2% of our customers have 'restrictive' networks and have required specific firewall rules to open UDP 10,000 to 20,000.

Our primary concern is a clear migration path for existing customers. Based on what you have said above, any customers who are actively using our product with the 2.0 SDK will already have UDP via ports 10,000 to 20,000 allowed on their firewall and therefore we should not expect any disruption when we roll out 3.0. Generally TCP/443 out to ANY is allowed by default in our experience.

BTW, the support doc you linked lists the 3.0 SDK as still using the PCMU codec.

**Comment by piyushtank** [comment]
@kieronlawson Closing this ticket. Feel to reopen the ticket if you are still running into the issue or have questions.
