### ISSUE TITLE
Poor Voice quality

### ISSUE THREAD

**Issue by aksthelion** [twilio/voice-quickstart-ios#235]
Hi,
In my live app there are many voice calls with very poor quality. My app has only client to client call feature.

Is there anything we can do to improve it if not how do we investigate it to find if there are any problem?

**Comment by bchen-twilio** [comment]
HI @aksthelion 

What is the version of SDK currently used in your application and can you provide Twilio Call SIDs that has the quality issues so we can investigate?
The Programmable Voice 3.0 iOS SDK is now GA and the default audio codec is Opus which should provide generally better audio quality than the default codec used in the 2.0 SDK. You can reference our [migration guide](https://github.com/twilio/voice-quickstart-swift/blob/master/Docs/migration-guide-2.x-3.x.md) and a complete list of new features [here](https://github.com/twilio/voice-quickstart-swift/blob/master/Docs/new-features-3.0.md).

Thanks
-bobie

**Comment by aksthelion** [comment]
I'm still on 2.0. I'll check out 3.0 and will implement it. Will let you know outcome later.

**Comment by piyushtank** [comment]
@aksthelion Hoping the voice quality issue has been resolved. Closing the ticket as it is opened for long without any activity, but feel free to reopen if you run into the issue.
