### ISSUE TITLE
App crashed with required condition is false: format.sampleRate == hwFormat.sampleRate'

### ISSUE THREAD

**Issue by anoopkumarevontech** [twilio/voice-quickstart-ios#244]
### Description

I am using speech to text recognition in my application it is working fine untill i make the call using twillio framework.
After call finished and i again start the listening using speechKit my application crashed with following error :-
**required condition is false: format.sampleRate == hwFormat.sampleRate'**

### Steps to Reproduce

1. create a singleton class for handling SpeechtoText and listeing the callback in controller.
2. stop recording and start twillio call. End twillio call.
3. Again start listening. App Got crashed with following error  **required condition is false: format.sampleRate == hwFormat.sampleRate'**

#### Code

```swift
class MySppechRecognizer: NSObject,SFSpeechRecognizerDelegate {
    /// initalize the speech recognitior . it is a shared instace.
    static let speechSharedInstance = MySppechRecognizer()
    var isSppechRecognisationAvaible = true
    var speechRecognizer:SFSpeechRecognizer? = nil
    var audioSession = AVAudioSession.sharedInstance()
    var audioEngine = AVAudioEngine()
    var recognitionTask: SFSpeechRecognitionTask?
    var recognitionRequest: SFSpeechAudioBufferRecognitionRequest?
    var isFinalWord = false
    var inputNode:AVAudioInputNode? = nil
    var callBack:jimboSpeechCallBack? = nil
    var isHotWordDetectedForApp = false

    func setSpeechRec() {
        if speechRecognizer == nil {
            speechRecognizer = SFSpeechRecognizer(locale: kAppLocal)
            speechRecognizer?.delegate = self
        }
    }
}

    //MARK:- Delegate
    func speechRecognizer(_ speechRecognizer: SFSpeechRecognizer, availabilityDidChange available: Bool) {
        print("Availibility changes")            
    }
    //MARK:- Audio engine
    func startRecording(){
   if recognitionTask != nil {
            self.recognitionRequest?.endAudio()
            recognitionTask?.cancel()
            recognitionTask = nil
            recognitionRequest = nil
            inputNode?.reset()
            inputNode?.removeTap(onBus: 0)
            inputNode?.reset()
            stopRecording()
        }

        do {
            try audioSession.setCategory(AVAudioSession.Category.playAndRecord, mode: .measurement)
            try audioSession.setMode(.measurement)
            try audioSession.setPreferredSampleRate(44100)
            try audioSession.setActive(true, options: .notifyOthersOnDeactivation)
        } catch {
            print("audioSession properties weren't set because of an error.")
        }
        inputNode = audioEngine.inputNode
        recognitionRequest = SFSpeechAudioBufferRecognitionRequest()
        recognitionRequest?.shouldReportPartialResults = true
        recognitionTask =  MySppechRecognizer.speechSharedInstance.speechRecognizer?.recognitionTask(with: recognitionRequest!, resultHandler: { (result, error) in
            print("Result is===\(String(describing: result?.bestTranscription.formattedString))")
            var isFinal = false
            if result != nil {
                isFinal = (result?.isFinal)!
                self.isFinalWord = (result?.isFinal)!
            }
            if error != nil || isFinal {
                self.audioEngine.stop()
                self.inputNode?.removeTap(onBus: 0)
                self.recognitionRequest = nil
                self.recognitionTask = nil
            }
            if error != nil {
                print(“Error === \(String(describing: error?.localizedDescription))")
                self.isFinalWord = true
            }
            guard self.callBack == nil else {
                self.callBack!(result,error)
                return
            }
        })

        let recordingFormat = inputNode?.outputFormat(forBus: 0)
        inputNode?.installTap(onBus: 0, bufferSize: 1024, format: recordingFormat) {[weak self] (buffer, when) in
            self?.recognitionRequest?.append(buffer)
        }
        audioEngine.prepare()
        do {
            try audioEngine.start()
        } catch {
            print("audioEngine couldn't start because of an error.")
        }
    }

    /// to stop the audio session
    func stopRecording() {
        DispatchQueue.main.async {
            if ((self.audioEngine.isRunning)){
                    self.recognitionRequest?.endAudio()
                self.recognitionTask?.cancel()
                self.recognitionTask = nil
                self.recognitionRequest = nil
                self.inputNode?.reset()
                self.inputNode?.removeTap(onBus: 0)
                self.inputNode?.reset()
                self.audioEngine.inputNode.reset()
            }
        }
    }
}
```

#### Expected Behavior

While twillio call sample rate should not change.

#### Actual Behavior

App crashed with sample rate change error.

#### Reproduces How Often

Every time when we make a call from twillio and call got connected or starts ringing.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

3.0.0 via CocoaPods

#### Xcode

10.1

#### iOS Version

12.0

#### iOS Device

iPhone 6s

**Comment by piyushtank** [comment]
@anoopkumarevontech Thanks for reaching out.

When you are making call using Voice SDK, it configures AVAudioSession and uses VoiceProcessing IO  AudioUnit. My best guess is your in call AVAudioSession configuration is conflicting with the speech recognition. I personally haven't tried but if you want to run SpeechRecognizer once the call is terminated on Voice SDK, you may have to reconfigure the `AVAudioSession` per your need.

Also, if you wish to configure AVAudioSession while in call `TVODefaultAudioDevice` has APIs to do so explicitly - see [this](https://twilio.github.io/twilio-voice-ios/docs/4.0.0/Classes/TVODefaultAudioDevice.html#//api/name/block).

let me know if you have any questions.

**Comment by Miguelthebug** [comment]
Use this while recording -
    func startRecording() {
                
            if recognitionTask != nil {
                
                       self.recognitionRequest?.endAudio()
                       recognitionTask?.cancel()
                       recognitionTask = nil
                       recognitionRequest = nil
             
                    audioEngine.inputNode.removeTap(onBus: 0)
                self.inputNode!.removeTap(onBus: 0)
                    audioEngine.prepare()  //12
                                  
                                  do {
                                      try audioEngine.start()
                                  } catch {
                                      print("audioEngine couldn't start because of an error.")
                                  }
                      // stopRecording()
                   }
                
                do {
                    try audioSession.setCategory(AVAudioSession.Category.record,mode: .measurement)
                    try audioSession.setMode(.default)
                     try audioSession.setPreferredSampleRate(44100)
                    try audioSession.setActive(true, options: .notifyOthersOnDeactivation)
                   // try audioSession.setActive(true, with: .notifyOthersOnDeactivation)
                } catch {
                    print("audioSession properties weren't set because of an error.")
                }
              
                recognitionRequest = SFSpeechAudioBufferRecognitionRequest()
                audioEngine.inputNode.reset()//3
                inputNode = audioEngine.inputNode
    
                guard let recognitionRequest = recognitionRequest else {
                    fatalError("Unable to create an SFSpeechAudioBufferRecognitionRequest object")
                } //5
                
                recognitionRequest.shouldReportPartialResults = true  //6
                
                recognitionTask = speechRecognizer.recognitionTask(with: recognitionRequest, resultHandler: { (result, error) in  //7
                    
                    var isFinal = false  //8
                    
                    if result != nil {
                        self.timer.invalidate()
                        self.timer = Timer.scheduledTimer(timeInterval: 2, target: self, selector: #selector(self.didFinishTalk), userInfo: nil, repeats: false)

                        let bestString = result?.bestTranscription.formattedString
                        self.fullsTring = bestString!
                        let lst = bestString!.byWords
                        guard let str = lst.last else{
                            return
                        }
                        self.lastString = String(describing: str)
                        if self.lastString.lowercased() != "send"{
                            self.inputContainerView.inputTextField.text = result?.bestTranscription.formattedString
                        }
                        //9
                        isFinal = (result?.isFinal)!
                        
                    }
                    if error != nil || isFinal {  //10
                        self.audioEngine.stop()
                        self.inputNode?.removeTap(onBus: 0)
                        self.recognitionRequest = nil
                        self.recognitionTask = nil

                     
                    }
                    if error != nil{
                       
                    }
                })
               // inputNode.reset()
//                inputNode.removeTap(onBus: 1)
             //  inputNode.removeTap(onBus: 0)
                let recordingFormat = inputNode!.outputFormat(forBus: 0)  //11
                inputNode!.installTap(onBus: 0, bufferSize: 1024, format: recordingFormat) { (buffer, when) in
                    self.recognitionRequest?.append(buffer)
                }
                
                audioEngine.prepare()  //12
                
                do {
                    try audioEngine.start()
                } catch {
                    print("audioEngine couldn't start because of an error.")
                }
                
              
                
            }
   ////////////////////////////////////////////////
and use this to play speech or words-
     func speakText(voiceOutdata: String ) {
        stopRecording()
        do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playback, mode: .default, options: .defaultToSpeaker)
            try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)
        } catch {
            print("audioSession properties weren't set because of an error.")
        }

         utterance = AVSpeechUtterance(string: voiceOutdata)
        utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
        let allVoice = AVSpeechSynthesisVoice.speechVoices()
        for voice in allVoice{
            print(voice)
        }
       
        vc = AVSpeechSynthesisVoice(identifier: "com.apple.ttsbundle.siri_male_en-GB_compact")!
        utterance.voice = vc
       
        synth.speak(utterance)
        
        do {
            disableAVSession()
        }
    }

**Comment by piyushtank** [comment]
Hi @Miguelthebug 

Can you make sure you remove all Twilio resources before you start listening?

Code you have shared is not Twilio specific and it's very difficult to debug the problem without knowing the complete picture. If you share a branch on our quickstart sample app to demonstrate the problem, I can take a look.

Best,
Piyush

**Comment by piyushtank** [comment]
@aksthelion @Miguelthebug Hoping the issue you were facing was resolved. 
Closing the ticket as it is opened for a couple of months without any activity, but feel free to reopen if you run into the issue or questions.

**Comment by delasign** [comment]
To solve this issue use this: 
`self.audioEngine.stop()
  self.recognitionRequest?.endAudio()
  self.recognitionRequest = nil
  self.recognitionTask = nil
  self.audioEngine.inputNode.removeTap(onBus: 0)`

This will allow you to endlessly start and stop.

**Comment by delasign** [comment]
Here's a tutorial that details how to start and stop it on repeat, without pressing a button.
https://delasign.com/blog/swift-speech-recognition-loop/
If you are looking for the specific end looping functionality, it can be found on this step:
https://www.delasign.com/blog/swift-speech-recognition-loop/#step-three:-add-end-audio-recording-functionality
