### ISSUE TITLE
52134 Invalid APNs device token

### ISSUE THREAD

**Issue by Romulomga** [twilio/voice-quickstart-ios#281]
### Description

In Twilio dashboard I see error(52134 Invalid APNs device token) and my call never reach out partner.

### Steps to Reproduce

1. Created a new .certSigningRequest from keychain access.
2. Generated new VoIP Services Certificate.
3. Downloaded .cer file and added certificate in keychain, Exported .p12 file from keychain
Followed instructions on https://github.com/twilio/voice-quickstart-swift to run those three commands to generate key and cert.
4. On Twilio created a new Push Credential and added Certificate and key by copying and pasting.
5. SANDBOX is unticked.
6. Change CREDENTIAL SID in my server backend.
7. Restarted server.

#### Expected Behavior

Make a voice call.

#### Actual Behavior

Call start but never reach out my partner.

#### Voice iOS SDK

[e.g. 5.1.0 via CocoaPods]

#### Xcode

[e.g. 11.2.1]

#### iOS Version

[e.g. 13.2.3]

#### iOS Device

[e.g. iPhone X]
[e.g. iPhone SE]

#### Extra information

- I made migration from 2.x to 5.x(passing to 3.x and 4.x) and in 2.x everything works fine(except for iOS 13 terminate your app call kit problem).
- With SANDBOX ticked or unticked, the result is the same(52134 Invalid APNs device token)
- Entitlements is production.
- I tested with the phones using TestFlight versions.
- I tested with the phone forcing production in direct cable versions.

**Comment by bchen-twilio** [comment]
Hi @Romulomga 

Do you have a Call SID when this happens?
The SDK upgrade should not cause the 52134 error. Please make sure you are using matching entitlement environment and Push Credential SIDs (sandbox or ~sandbox). You might also want to make sure that the device token decoded from the PkPushRegistry callback is in correct format: https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L216

-bobie

**Comment by Romulomga** [comment]
- **Please make sure you are using matching entitlement environment and Push Credential SIDs (sandbox or ~sandbox)**

Exporting as production and sandbox is unticked: 
![Captura de Tela 2019-11-27 às 19 05 34](https://user-images.githubusercontent.com/23625196/69762530-45d39380-1149-11ea-904e-8a5cbc3d8d11.png)

P.S: Doing a revert commit and turn back to 2.x version, everything works fine. This makes me believe, that's not a certificate problem but a malformed device token.

- **You might also want to make sure that the device token decoded from the PkPushRegistry callback is in correct format**

Sorry, I forgot to add this in extra. I migrate from 2.x to 5.x, so im using the correct decode format.

![Captura de Tela 2019-11-27 às 18 58 39](https://user-images.githubusercontent.com/23625196/69762877-52a4b700-114a-11ea-8142-e016b9a490e4.png)

**Comment by Romulomga** [comment]
Hello?

**Comment by bchen-twilio** [comment]
Hi @Romulomga 

I have checked the Call SID you provided and it appeared that there were two bindings associated with the called client identity. Is it possible that the device was used in an Xcode debugging session but later used to install a production version of the app? The device token received in the PushKit callback might be from the entitlement environment (development/production) of the previous session when switching between debugging and production versions of the application on the device. Does this keep happening if you restart the app and perform the registration with the new device token?

-bobie

**Comment by Romulomga** [comment]
Hi @bchen-twilio,

I follow your suggestion to restart, register a new device token and the result is the same.

New call Sid: CA78dbdda4ab49ea2ba4d6089f3d1dedfd

**Comment by bchen-twilio** [comment]
Hi @Romulomga 

Thanks again for providing the Call SID. I've checked the Insights data and found that there were a couple of notification deliveries to the callee identity `21062` and one of the delivery attempt failed, which is for a device with device token `a765b0db ... eda3d80d`. Can you check if you are able to locate the device and see if the error is fixed once registration on this device is refreshed with the latest code and the correct entitlement environment + Push Credential SID.

-bobie

**Comment by Romulomga** [comment]
Hi @bchen-twilio 

I locate the device. Made the refresh and the error persist :/

Just to be clear, now I current using two devices for test, both with the correct entitlement environment + Push Credential SID:
iPhone 5s device token: a765b0db ... eda3d80d
iPhone X device token: a0dd4e58 ... 7c908842

After refresh, new call sid: CA9586caa6127511878bd411bf434c1363

**Comment by bchen-twilio** [comment]
@Romulomga 

I checked with the Call SID and the error is still from the delivery for the iPhone 5s, where the device token is invalid for the environment used by the Push Credential SID.

**Comment by Romulomga** [comment]
@bchen-twilio 

Are you sure that the new device token decode method is correct? Because downgrading to version 2.x, using iOS 12(iPhone 5s) and returning the decode method to:

`let deviceToken = (credentials.token as NSData).description`

I receive my partner call. This lead me to believe that my environment and push credential is correct.

**Comment by bchen-twilio** [comment]
Hi @Romulomga 

Thanks for trying different versions. Technically the two decoding methods should return the same values. Do you see different values using different decoding methods on the iPhone 5s? The SDK does not modify the device token but just pass it to the Notify service for creating a notification binding.

For iOS 12 (and earlier version) + Xcode 10
```
let deviceToken = (credentials.token as NSData).description
```

For iOS 13
```
let deviceToken = credentials.token.map { String(format: "%02x", $0) }.joined()
```

**Comment by ayazalphasquad** [comment]
Hi @bobiechen-twilio @piyushtank  - I’ve updated my AppDelegate.mm file with CallKit and PushKit. But, I’m still facing an issue where the notification shows as "Unknown caller" when the app is in the background or killed, even though the correct caller details are displayed when the app is open.

How can I fix this issue and ensure that the correct caller details are displayed in the notification when the app is not in the foreground?


My AppDelegate.mm file: 

#import "AppDelegate.h"
#import <Firebase.h>
#import <PushKit/PushKit.h>
#import <CallKit/CallKit.h>
#import <React/RCTBundleURLProvider.h>
#import <UserNotifications/UserNotifications.h>
#import "RNFBMessagingModule.h"
#import "RNVoipPushNotificationManager.h"
#import <TwilioVoice/TwilioVoice.h>

@interface AppDelegate () <PKPushRegistryDelegate, CXProviderDelegate>

@property (nonatomic, strong) PKPushRegistry *voipRegistry;
@property (nonatomic, strong) CXProvider *callKitProvider;
@property (nonatomic, strong) CXCallController *callController;

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  NSString *bundleIdentifier = [[NSBundle mainBundle] bundleIdentifier];

  if ([bundleIdentifier isEqualToString:@""]) {
    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
    FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
    [FIRApp configureWithOptions:options];
  } else {
    [FIRApp configure];
  }

  
  [self initializeCallKit];
  [self initializePushKit];

  self.callController = [[CXCallController alloc] init];
  self.moduleName = @"sigmagoMobileNebulaConnections";
  self.initialProps = [RNFBMessagingModule addCustomPropsToUserProps:@{@"isHeadless": @YES} withLaunchOptions:launchOptions];

  
  [RNVoipPushNotificationManager voipRegistration];

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

#pragma mark - Initialize CallKit

- (void)initializeCallKit {
  CXProviderConfiguration *configuration = [[CXProviderConfiguration alloc] initWithLocalizedName:@"Nebula"];
  configuration.supportsVideo = NO;
  configuration.maximumCallsPerCallGroup = 1;
  configuration.maximumCallGroups = 1;
  configuration.supportedHandleTypes = [NSSet setWithObject:@(CXHandleTypePhoneNumber)];
  configuration.includesCallsInRecents = NO; 
  self.callKitProvider = [[CXProvider alloc] initWithConfiguration:configuration];
  [self.callKitProvider setDelegate:self queue:nil];
}

#pragma mark - Initialize PushKit

- (void)initializePushKit {
  self.voipRegistry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
  self.voipRegistry.delegate = self;
  self.voipRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
}

#pragma mark - PushKit Delegate Methods

- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(PKPushType)type {
  NSLog(@"PushKit Token: %@", credentials.token);
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type]; 
}

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  NSLog(@"Received incoming VoIP push notification: %@", payload.dictionaryPayload);

  
  NSDictionary *payloadData = payload.dictionaryPayload;
  NSString *callerName = payloadData[@"callerName"];
  NSString *handle = payloadData[@"handle"];

  if (!callerName) {
    callerName = @"Unknown Caller";
    NSLog(@"Caller name is missing in payload");
  }
  if (!handle) {
    handle = @"Unknown Handle";
    NSLog(@"Handle is missing in payload");
  }

  
  NSLog(@"Caller Name: %@", callerName);
  NSLog(@"Handle: %@", handle);

  
  [self reportIncomingCallWithUUID:[NSUUID UUID] callerName:callerName handle:handle];

  
  completion(); 
}

#pragma mark - Handle Incoming Call

- (void)reportIncomingCallWithUUID:(NSUUID *)uuid callerName:(NSString *)callerName handle:(NSString *)handle {
  CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
  callUpdate.localizedCallerName = callerName;
  callUpdate.remoteHandle = [[CXHandle alloc] initWithType:CXHandleTypePhoneNumber value:handle];
  callUpdate.hasVideo = NO;

  [self.callKitProvider reportNewIncomingCallWithUUID:uuid update:callUpdate completion:^(NSError * _Nullable error) {
    if (error) {
      NSLog(@"Error reporting incoming call: %@", error.localizedDescription);
    } else {
      NSLog(@"Incoming call reported successfully for caller: %@ with handle: %@", callerName, handle);
    }
  }];
}

#pragma mark - CXProviderDelegate Methods

- (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action {
  NSLog(@"Call answered");
  [action fulfill];

  
  [[NSNotificationCenter defaultCenter] postNotificationName:@"CallAnswered" object:nil];
}

- (void)provider:(CXProvider *)provider performEndCallAction:(CXEndCallAction *)action {
  NSLog(@"Call ended/rejected");
  [action fulfill];

  
  [[NSNotificationCenter defaultCenter] postNotificationName:@"CallEnded" object:nil];
}

#pragma mark - React Native Integration

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

**Comment by ayazalphasquad** [comment]
Hi @bobiechen-twilio - Thank you for your response. The reported issue has been resolved. But, could you please guide me on how to accept or reject incoming calls when the app is in a terminated state in the App Delegate?

**Comment by ayazalphasquad** [comment]
Hi @bobiechen-twilio - Thank you for your response. The issue mentioned above has been resolved. But, could you please assist me with handling the accept/reject actions for incoming calls in the killing state within AppDelegate.mm? Alternatively, let me know if we can handle this logic within the application ?
