### ISSUE TITLE
Twiio Incoming call

### ISSUE THREAD

**Issue by Unnikrishnanvenad** [twilio/voice-quickstart-ios#291]
Hai 

In my project  i implemented a browser - device call and it works fine. i receiving call but when i took call with phone call ui. it going to background and my app is on foreground. iPhone default call UI actually running in the background  along with my app. How could i resolve this issue ?
Can i hold the iphone default Call UI For incoming call?
Can you please Help me to find out the actual issue?

**Comment by bchen-twilio** [comment]
Hi @Unnikrishnanvenad 

I think this is a designed behavior by Apple. The call will only stay in the native call app UI when the incoming call is answered while the device is locked.
In your case, it is still possible to use the process view to switch to the system call UI after the call is answered.

-bobie

**Comment by piyushtank** [comment]
@pouledodue Hoping @bchen-twilio answer help implement the UI flow in your app. Closing the ticket but feel free to reach out if you have any questions.

**Comment by pouledodue** [comment]
cc @Unnikrishnanvenad
