### ISSUE TITLE
Crash when receiving a Twilio Call while you are in native call

### ISSUE THREAD

**Issue by MarcoCanalcar** [twilio/voice-quickstart-ios#298]
### Description

When you are in a standard pstn call and you receive a Twilio call, the call gets terminated and a dialog saying "Call Failed" appears. First, I thought this was some issue in my app but it's reproducible with the quickstart repository.
### Steps to Reproduce

1. Make a PSTN call to a PSTN number
2. Call the placeCall endpoint to initiate a call to the device while in call

#### Code

No code apart from the Quickstart code is necessary to reproduce this issue

#### Expected Behavior

The PSTN call should continue, a dialog should appear to let you choose between calls

#### Actual Behavior

The active PSTN call gets ended, and the Twilio call is not displayed

#### Reproduces How Often

100%

#### Logs

A callservicesd crash is generated:
[callservicesd  10-24-19, 4-08 PM.log](https://github.com/twilio/voice-quickstart-objc/files/3768289/callservicesd.10-24-19.4-08.PM.log)

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

5.0.0

#### Xcode

11.1

#### iOS Version

13.1.2

#### iOS Device

iPhone SE
iPhone 11 Pro

**Comment by piyushtank** [comment]
@MarcoCanalcar Are you still running into the crash? We haven't seen the crash in our validation.

**Comment by bchen-twilio** [comment]
Hi @MarcoCanalcar 

Hope things are well. I am closing this ticket assuming the original issue has been resolved by the iOS updates. Please feel free to reach out to us.

Cheers,
bobie
