### ISSUE TITLE
No audio through speaker when running in Background

### ISSUE THREAD

**Issue by jvanakker** [twilio/voice-quickstart-ios#299]
### Description

The sample application contains a function called "toggleAudioRoute:(BOOL)toSpeaker".
In our application, we programmatically initiate an outgoing call. I have used toggelAudioRoute to force the call through speaker. This is working fine with the iOS app running in foreground, but it does not work when the app is running in the background (either locked iPhone or just with the app in the background). From both ends of the line, nothing can be heard. Any thoughts?

#### Voice iOS SDK

TwilioVoice sdk 3.1.1

#### Xcode

10.3

#### iOS Version

12.4

#### iOS Device

Any device

**Comment by bchen-twilio** [comment]
Tried with iOS 13.3.1 but this seems to still be an issue. No updates in the developer forum thread indicating this has been fixed. We will mark this one as a known issue.

**Comment by odieatla** [comment]
I've ran into the same issue with iOS 14 when app is in the background. Wonder if you have found a solution or workaround?

**Comment by bobiechen-twilio** [comment]
Hi @odieatla 

Is it possible to provide some detail such as the steps you did that lead to the problem or SDK/device logs?

**Comment by odieatla** [comment]
> Hi @bchen-twilio
> Our app is continuously running in the background. It automatically performs a call to a pre-determined number in some situations. The app doesn't receive calls. Also it doesn't make sense for us to use appWillResignActive to place calls, as the call will be later. As mentioned the app is designed to keep running which works, only when initiating an outgoing call without CallKit, the audio has stopped working as mentioned since iOS 12.4. When using CallKit methods, it does work, but this is not desirable for our case, as we do not want to have the default CallKit "phone screen UI" that CallKit triggers when the app starts calling with the phone locked.
> 
> This is quick code snippet of initiating the call using the Non-CallKit method:
> 
> TVOConnectOptions *connectOptions = [TVOConnectOptions optionsWithAccessToken:self.twilioToken
> block:^(TVOConnectOptionsBuilder *builder) {
> builder.params = @{kTwimlParamTo: self.twilioPhoneNumberToBeCalled};
> }];
> self.twilioCall = [TwilioVoice connectWithOptions:connectOptions delegate:self];
> self.callKitCompletionCallback = completionHandler;
> self.phoneIsCallingTwilioVoip = YES;

Hi @bobiechen-twilio, my use case is pretty similar to this one. I see it's marked as a known issue for iOS 13. I wonder if you have a fix for iOS 14?

**Comment by bobiechen-twilio** [comment]
Thanks for the update @odieatla.
This seems to still be true on iOS 14. Just to confirm:
- Does the audio issue happen when the call is made in the foreground?
- Does it happen if CallKit is integrated with the call?

We can also use device logs or SDK logs if it's not too much trouble for you to get the logs.
