### ISSUE TITLE
Crash - Attempted to dereference null pointer - twilio_pj_atomic_get

### ISSUE THREAD

**Issue by fabriziomoscon** [twilio/voice-quickstart-ios#300]
### Description

When attempting to make a call from Simulator.

### Steps to Reproduce

I am not able to reproduce it, usually everything works ok.

#### Logs
I shared my sentry crash report:
https://sentry.io/share/issue/ccc0d5b6b3a943d9aa48df6890c745ff/

#### Voice iOS SDK

TwilioVoice SDK 2.0.2 via CocoaPods

(please note that the crash report shows TwilioVoice 1.0.0)

#### iOS Version
11.2

#### iOS Device

iPhone X simulator

**Comment by piyushtank** [comment]
Closing the old issue as we have released a new redesigned SDK with more features and more stability.
