### ISSUE TITLE
Xamarin Support Needed

### ISSUE THREAD

**Issue by RedBlue1776** [twilio/voice-quickstart-ios#301]
It's very difficult to use this Objective C library with Xamarin... the bindings produced by objective sharpie require a lot of customization and is a hurdle for newcomers to Twilio.

https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-sharpie/

Please modify the framework build so that Objective Sharpie can consume it from a PodFile or a *.a file more cleanly.

Alternatively, publish bindings for this (as I've seen for Xamarin Chat)

**Comment by piyushtank** [comment]
Closing this ticket as the Xamrin bindings are not officially supported by the TwilioVoice SDK.
