### ISSUE TITLE
Reachability API/method

### ISSUE THREAD

**Issue by geoffliddiard** [twilio/voice-quickstart-ios#302]
Our app falls back to PSTN dialling / receiving when network conditions aren't VoIP friendly. Would you consider exposing the any internal metrics used to determine reachability as mentioned in the changelog notes for Beta5?

Thanks!

**Comment by piyushtank** [comment]
Hi @geoffliddiard,
Thanks for filing the ticket. We have added this to our backlog for prioritization.
(Similar feature request was made in ticket - https://github.com/twilio/voice-quickstart-ios/issues/318)

Best,
Piyush
