### ISSUE TITLE
Error when compiling against 32bit simulator

### ISSUE THREAD

**Issue by kseverin** [twilio/voice-quickstart-ios#303]
### Description

The quickstart-iOS project does not appear to work on iPhone 5 or 32bit simulators

### Steps to Reproduce

1. Download starter project
2. Pod install 
3. Attempt to run project on iPhone 5

#### Code
N/A

#### Expected Behavior

Should run on iPhone 5 simulator.

#### Actual Behavior

Does not work on iPhone 5 and 5s simulators. Only works on iPhone 6 and above simulators.

#### Reproduces How Often

Always

#### Logs
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_TVOAcceptOptions", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOCall", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOCallInvite", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVODefaultAudioDevice", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOConnectOptions", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TwilioVoice", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Voice iOS SDK

TwilioVoice 5.1.1

#### Xcode

Xcode 11.3

#### iOS Version

iPhone 5 simulator using iOS 10.3

#### iOS Device

iPhone 5 and 5s simulator

**Comment by piyushtank** [comment]
@kseverin Thanks for reaching out. Starting Voice SDK version 5.1.0, iOS Voice SDK no longer supports i386 architecture. Unfortunately, our changelogs were not updated. I just pushed a change and updated the changelogs for the 5.1.0 release with this note. I apologize for the inconvenience.

**Comment by kseverin** [comment]
Thanks for the quick response, will make adjustments on my end to account for this.

**Comment by fabriziomoscon** [comment]
Hi @piyushtank,
thank you for adding the deprecation note to the [CHANGELOG](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#511): `Removed support for the iOS i386 architecture (32-bit iOS Simulator)`
Could I ask for a little help to understand how this impacts the development cycle? **For example my app does no longer build in XCode for a Release target when specifying a simulator (iPhone 8, X, 11)**. The error is the same posted in this issue. When I build for a `Generic iOS Device` there are no errors for both target Debug and Release.

I believe that I should change some flag that trigger multiple build for release which try to compile for architecture i386, but I am so far I have not been able to find the answer.

Thank you.
