### ISSUE TITLE
Call failed to connect: Service Unavailable and Unknown UUID to perform end-call action with

### ISSUE THREAD

**Issue by editrShakil** [twilio/voice-quickstart-ios#315]
why i am unable to make an incoming call? here is error log
2020-02-25 19:16:41.819463+0600 SwiftVoiceQuickstart[5004:245976] provider:didActivateAudioSession:
2020-02-25 19:16:43.712931+0600 SwiftVoiceQuickstart[5004:245976] Call failed to connect: Service Unavailable
2020-02-25 19:16:43.718792+0600 SwiftVoiceQuickstart[5004:247487] EndCallAction transaction request successful
2020-02-25 19:16:43.758431+0600 SwiftVoiceQuickstart[5004:245976] provider:performEndCallAction:
2020-02-25 19:16:43.758568+0600 SwiftVoiceQuickstart[5004:245976] Unknown UUID to perform end-call action with
2020-02-25 19:16:43.799505+0600 SwiftVoiceQuickstart[5004:245976] provider:didDeactivateAudioSession:

**Comment by bchen-twilio** [comment]
Hi @editrShakil 

Can you provide a Twilio Call SID so that we can have a deeper look and tell you what exactly caused the failure? Based on the logs it seems you were getting a 31503 error (Service Unavailable) when trying to accept the incoming call. This is usually caused when the network connectivity problem and the mobile client is not able to reach to the service.

The second part of the failure (`Unknown UUID to perform end-call action with`) is printed because the `TVOCall` object was already deleted in the [`callDisconnected` method](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L419) due to the failure above.

Can you check if the network connectivity on the device is good and the network interface the device is connected to is not behind any firewall settings?

If this issue keeps happening in your environment, please provide `TVOLogLevelTrace` level SDK log so we can investigate.

Thanks,
-bobie

**Comment by editrShakil** [comment]
after changing identity it worked. now can you help me with https://github.com/twilio/voice-quickstart-ios#10-receive-an-incoming-call this section? Here what should be identity and who should be receiver? i configured push notification and credential but i am not receiving any incoming call in my device. when i call my personal number i am getting call from my twilio number when i hit on my server's /placeCall endpoint.

**Comment by editrShakil** [comment]
thanks it worked after changing identity

**Comment by editrShakil** [comment]
can you please tell me in detail about client to client calling? i run my app in two devices with only changing identity (device-1 : "alice", device-2:"bob") but i am not receiving any call on device one when calling from device two with the value "bob" in the text field. can you please explain https://github.com/twilio/voice-quickstart-ios#11-make-client-to-client-call this section so that i can make client to client call

**Comment by bchen-twilio** [comment]
Hi @editrShakil 

Glad that things started to work.
To make a call to another client, the TwiML response from you app server must use [\<Dial\> + \<Client\>](https://www.twilio.com/docs/voice/twiml/client) with the callee identity. Your application server needs to parse the URL-encoded parameters to determine the action of the call, in this case it will be making a call to another client (value from the text field). Put the parameter key-value pairs [into the TVOConnectOptions builder](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L657) and then make a call, your TwiML app endpoint should receive the parameter pair(s).

-bobie

**Comment by editrShakil** [comment]
i am getting this error 52004 Credential SID not specified when i try to call a client.

**Comment by bchen-twilio** [comment]
Hi @editrShakil 

Did you follow [this step](https://github.com/twilio/voice-quickstart-ios#8-create-a-push-credential-with-your-voip-service-certificate) to set up a Push Credential SID and put it in the callee's access token when performing registration?

**Comment by editrShakil** [comment]
yes i did but i didnt get "Now let's go back to your server code and update the Push Credential SID. The Push Credential SID will now be embedded in your access token" this. where to set PUSH_CREDENTIAL_SID?

**Comment by editrShakil** [comment]
are you asking me to do 
const token = new AccessToken(twilioAccountSid, twilioApiKey, twilioApiSecret, credentialSID);
something like this? previously i did 
const token = new AccessToken(twilioAccountSid, twilioApiKey, twilioApiSecret);

**Comment by bchen-twilio** [comment]
Hi @editrShakil 

You should be able to replace a placeholder string in the server quickstart for the Push Credential SID.

**Comment by editrShakil** [comment]
![Capture](https://user-images.githubusercontent.com/61462815/75477280-44bf3600-59c6-11ea-9293-73f0a44cc421.PNG)
you mean this? sorry i am not getting it. i did this previously as i am using twilio functions.

**Comment by bchen-twilio** [comment]
This is the correct place if you are using Functions. The basic idea is to put it in the place where your server application can use the value and put it in the access token. You verify the contents of your access token by feeding the string to https://jwt.io. You should see your account credentials in the decoded string if you properly configured everything.

**Comment by editrShakil** [comment]
its working fine. thanks @bchen-twilio

**Comment by bchen-twilio** [comment]
Glad to hear that! I am going to close this ticket. Please feel free to reach out to us if you run into any issue.

Cheers,
-bobie

**Comment by editrShakil** [comment]
surely i will. thanks a lot. @bchen-twilio
