### ISSUE TITLE
How to pass custom parameters with Twilio voice in swift ios?

### ISSUE THREAD

**Issue by TechnoBrigadeInfotech** [twilio/voice-quickstart-ios#317]
Description
How to pass custom parameters with Twilio voice in swift ios

Steps to Reproduce
I want to pass custom parameters from one client to other

So what setup I need to do in server-side and in swift ios as well as how can I get parameter 

I have followed a document from this link
(https://www.twilio.com/docs/voice/how-share-information-between-your-applications#custom-parameters-contextual-calling)

I did below code in my swift code, is there a need to do code from server-side?
How can I get data?

let connectOptions: TVOConnectOptions = TVOConnectOptions(accessToken: accessToken) { (builder) in
            builder.params = [twimlParamTo : self.outgoingValue.text!, "fname" : "Anhas",
            "lname" : "knight"]
            builder.uuid = uuid
        }
        let call = TwilioVoice.connect(with: connectOptions, delegate: self)
        self.activeCall = call
        self.activeCalls[call.uuid.uuidString] = call
        self.callKitCompletionCallback = completionHandler
Versions
All relevant version information for the issue.

Voice iOS SDK
Using TwilioVoice (5.1.1)

Xcode
Xcode 11.2.1

iOS Version
All versions above 10

iOS Device
On All Devices

**Comment by bchen-twilio** [comment]
Hi @TechnoBrigadeInfotech 

Thanks for opening the issue in the quickstart repo.
Yes, your application server, where the TwiML response is generated, has to do a little bit work to return a TwiML response that looks like this:
```
  <?xml version="1.0" encoding="UTF-8"?>
  <Response>
    <Dial callerId="client:alice">
      <Client>
        <Identity>bob</Identity>
        <Parameter name="caller_first_name" value="alice" />
        <Parameter name="caller_last_name" value="smith" />
      </Client>
    </Dial>
  </Response>
```

You can find more details in the changelog: https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#300-preview4

Depending on the server language you opt for your app server implementation, you should be able to find options to add custom parameters into your <Client> noun.

-bobie

**Comment by aymenn** [comment]
Hi @TechnoBrigadeInfotech,
We also have this [document](https://www.twilio.com/docs/voice/how-share-information-between-your-applications) that explains how to pass parameters within Twilio. Please don't hesitate to reopen the request if you have any questions or feedback.

Regards, Aymen
