### ISSUE TITLE
Force cellular network connection using requiredInterfaceType/prohibitedInterfaceType?

### ISSUE THREAD

**Issue by kieronlawson** [twilio/voice-quickstart-ios#318]
Hi Twilio team,

We have a number of customers who have continual problems using our product on their wifi networks.  Despite having DSCP enabled and them having WMM based QOS it seems like their ISPs actively discard DSCP headers and they experience continual call quality issues as a result.   Their end users may also suffer from low wifi signal strength or they are in a noisy wifi environment.

Our normal support recommendation for these customers is to disable wifi on their devices and revert to 4G data, and 99% of the time this resolves the call quality issues.

The key concern we encounter with this solution is that disabling wifi will eat into their plan data - not for the calls themselves but by other applications on their phone.

It seems like it is possible to force a specific network interface in iOS (versions 12.0+) by specifying a requiredInterfaceType option (or conversely prohibitedInterfaceType) on the NWParameters object when creating a new NWConnection:
https://developer.apple.com/documentation/network/nwparameters/2998706-requiredinterfacetype
https://developer.apple.com/documentation/network/nwparameters/2998703-prohibitedinterfacetypes

If this could be exposed through the Twilio SDK it would allow us to expose an option in our app to "force 4G where available".

Is this feasible?

Cheers
Kieron

**Comment by bchen-twilio** [comment]
Hi @kieronlawson 

Thanks for reaching out.
We will research the feasibility and keep you updated.

Regards,
-bobie

**Comment by aymenn** [comment]
Hey @kieronlawson 
Thank you for reaching out. Ive added this to our backlog for prioritisation. 
Regards, Aymen

**Comment by piyushtank** [comment]
A similar feature request was made in ticket - https://github.com/twilio/voice-quickstart-ios/issues/302
