### ISSUE TITLE
Callkit native UI for incoming call gets disappear once I click on answer button.

### ISSUE THREAD

**Issue by shreyapitangent** [twilio/voice-quickstart-ios#325]
I am implementing Twilio call in an app developed in react native.
The incoming call is occuring properly and disconnect also happening if we lock the iphone. 
When the device is unlocked the Incoming UI is coming but the UI disappears when I click on answer button.
I have opened a custom UI but the call is not getting disconnected when I click on the custom disconnect button.
How to disconnect the call properly?

**Comment by shreyapitangent** [comment]
Incoming push is received occassionally but when I call from other device the call is getting connected but the UI is not opening occassionally.

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

> The incoming call is occuring properly and disconnect also happening if we lock the iphone.
This sounds like the known issue of using PushKit and React Native.

> When the device is unlocked the Incoming UI is coming but the UI disappears when I click on answer button.
This is the design by Apple. It only stays in the native Call UI when the call is answered and the device is locked.

> I have opened a custom UI but the call is not getting disconnected when I click on the custom disconnect button.
Please provide SDK log if the call is not properly disconnected when `[TVOCall disconnect]` is called.

> Incoming push is received occassionally but when I call from other device the call is getting connected but the UI is not opening occassionally.
Can you describe more details about the steps (how the call is made) and the environment (is the app in the foreground or background or device locked). Please provide Twilio Call SIDs if you think the incoming push is not received.

Thanks,
-bobie

**Comment by shreyapitangent** [comment]
Hi,
During the outgoing call when I press the disconnect button on custom UI
the call is not getting disconnected.
The error showing the log is attached with screenshot with this mail.

Thanks
shreyapitangent

**Comment by shreyapitangent** [comment]
Hi,
During the outgoing call when I press the disconnect button on custom UI the call is not getting disconnected.
The error showing the log is attached with screenshot with this mail.

Thanks 
shreyapitangent
![Screenshot 2020-03-21 at 7 15 09 PM](https://user-images.githubusercontent.com/62427138/77227744-77fd7b00-6ba8-11ea-8a91-c33f7779e108.png)

**Comment by shreyapitangent** [comment]
In outgoing call access token is generated still while placing call access token required error occurring.

**Comment by shreyapitangent** [comment]
Hi,
In outgoing call access token is generated still while placing call access
token required error occurring.

Thanks
shreyapitangent

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

Based on the screenshot you will need to use a valid UUID to initialize a CallKit action. You should be able to find the value in the TVOCall object.

-bobie

**Comment by shreyapitangent** [comment]
Hi,
Call is getting established properly but disconnection is not
occurring properly when I am using a custom button.
The code I have used is stated below.

-(*void*)disconnect:(TVOCall *)call

{

 _calluuid = [[NSUserDefaults standardUserDefaults]

          stringForKey:@"calluuid"];

  NSLog(@"%@", _calluuid);

  NSLog(@"%@", call);

 // [call disconnect];

  *if* (!*self*.userInitiatedDisconnect) {

         CXCallEndedReason reason = CXCallEndedReasonDeclinedElsewhere;

    [*self*.callKitProvider reportCallWithUUID:call.uuid endedAtDate:[NSDate
date] reason:reason];

     [*self* callDisconnected:call];

     [*self* performEndCallActionWithUUID:_calluuid];

  }

  *else*

  {

    CXCallEndedReason reason = CXCallEndedReasonDeclinedElsewhere;

      [*self*.callKitProvider reportCallWithUUID:call.uuid endedAtDate:[
NSDate date] reason:reason];

     [*self* callDisconnected:call];

     [*self* performEndCallActionWithUUID:_calluuid];

  }







}


Please suggest what I am doing wrong.
The call is getting disconnected properly when I am using native UI or the
lock button is pressed.


[TVOCall disconnect] method is not disconnecting the call.


Please suggest necessary steps.


Thanks and Regards

Shreya Sinha Roy

**Comment by bchen-twilio** [comment]
Hi @shreyapitangen

For disconnecting the active call from the app UI, please follow this call flow in the quickstart: https://github.com/twilio/voice-quickstart-ios/blob/master/ObjcVoiceQuickstart/ViewController.m#L119

**Comment by shreyapitangent** [comment]
Hi,
While disconnecting the call with custom button it is not getting any uuid.
Response showing its nil and its not getting disconnected.

Thanks & Regards
shreyapitangent

**Comment by shreyapitangent** [comment]
Hi,
Sometimes
StartCallAction transaction request failed
error is happening occasionally while placing calls.

Thanks And Regards
Shreya Sinha Roy

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

Does the issue happen when using the quickstart with the same steps?
Can you provide more details about the error you saw when submitting the start call transaction?

-bobie

**Comment by shreyapitangent** [comment]
Hi,
Yes the issue is happening occasionally.
The function performStartCallActionWithUUID
is getting called and sometimes the StartCallAction transaction request
failed
error is coming.
Sometimes after successful transaction the disconnect method is not getting
called.

- shreyapitangent <https://github.com/shreyapitangent>

**Comment by shreyapitangent** [comment]
Hi,
Yes the issue is happening occasionally.
The function performStartCallActionWithUUID
is getting called and sometimes the StartCallAction transaction request
failed
error is coming.
Sometimes after successful transaction the didconnect method is not getting
called.
After 3-4 times sometimes the call is getting connected.
And the disconnection of call is not happening properly.

- shreyapitangent <https://github.com/shreyapitangent>

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

Please provide the details (error code, SDK/app log) when the error happens.
Can you also try with the quickstart? I've used the quickstart to do the same steps but I was not able to reproduce the issue you are describing.

**Comment by shreyapitangent** [comment]
Hi,
I have implemented the steps stated in quickstart .
While placing a call I am directing the page to a custom UI.
Place call action is occurring from a button created through react native.
The function performStartCallActionWithUUID
is getting called and sometimes the StartCallAction transaction request
failed
error is coming.
Sometimes after successful transaction the didconnect method is not getting
called.
After 3-4 times sometimes the call is getting connected.
And the disconnection of call is not happening properly.

-shreyapitangent

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

Please check the error in the completion block when you submit the start-call transaction in the `performStartCallActionWithUUID` method. You should find the reason why the transaction failed and we can use the information to help you debug.

For disconnecting the call:
- Follow [this call flow](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L142) if you are disconnecting from your app UI
- Follow [this call flow](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L548) if the call is disconnected from the system Call UI or disconnected by the remote party.

**Comment by shreyapitangent** [comment]
Hi
Please send code link in Objective C.

-shreyapitangent

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

You should be able to find the Obj C equivalent in the repo: https://github.com/twilio/voice-quickstart-ios/tree/master/ObjcVoiceQuickstart
