### ISSUE TITLE
Question about call between clients

### ISSUE THREAD

**Issue by tsuyoshi777** [twilio/voice-quickstart-ios#327]
Hi Twilio team,

We are implementing Twilio call in our app.

I have a question about call between clients.I heard that I can achieve simple call function without TwiML and app server like [/placeCall](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L99),  If I have an  app server that returns an access token.

Can I make a call between clients if I only have an  app server that gets an access token?

**Comment by bchen-twilio** [comment]
Hi @tsuyoshi777 

Currently to connect a call between clients, you will still need to provide an Application SID in your access token. This App SID tells Twilio the action URL when the caller call is connected with Twilio. By default we are expecting the action URL to return a valid TwiML response, which determines the next action, in this case a <Dial> verb to a call another client.

Hope this makes sense to you.

Cheers,
-bobie

**Comment by tsuyoshi777** [comment]
Thank you for your reply @bchen-twilio 

It seems like Application SID is mandatory! In order to connect a call between clients, We need to implement the following two processing on the server, right?

1. return access token
2. call another client

**Comment by bchen-twilio** [comment]
Hi @tsuyoshi777 

Yes, that is correct. To programmatically connect calls between clients or numbers the best way is to have a server endpoint that returns TwiML responses based on your business logic.

**Comment by tsuyoshi777** [comment]
@bchen-twilio Thanks a lot！

**Comment by bchen-twilio** [comment]
@tsuyoshi777 Any time! Let us know if you need any help.
