### ISSUE TITLE
WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.

### ISSUE THREAD

**Issue by shreyapitangent** [twilio/voice-quickstart-ios#329]
I've checked this issue with the github quickstart links
I have a ViewController from where I am handling the outgoing call functionalities.

This occurring in case of outgoing calls.

**Comment by shreyapitangent** [comment]
The app is crashing while placing multiple outgoing calls.

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

Could you please use the quickstart and see if this happens with your steps?

Thanks,
-bobie

**Comment by piyushtank** [comment]
Hi @shreyapitangent, 
How are you setting the `TwilioVoice.audioDevice` ?  

`TwilioVoice.audioDevice` should not be set when you already have an ongoing call. Once you hangup all your calls, clean up all your media objects, (tracks, calls, connect options), you can set it again.

Let us know if you have any questions.

Best,
Piyush

**Comment by bchen-twilio** [comment]
Hi @shreyapitangent 

I am closing this issue assuming the original issue has been resolved. Please feel free to reopen or file a new ticket if you need help integrating the Voice SDK.

Thanks,
-bobie
