### ISSUE TITLE
Questions to make client to client call

### ISSUE THREAD

**Issue by tsuyoshi777** [twilio/voice-quickstart-ios#330]
Hi @bchen-twilio

Thank you for the other day. I took the code from this tutorial into my project and tested the call, but I couldn't actually talk between devices. It seems that outgoing and incoming are successful. If this tutorial were done correctly up to number 11, would it be possible to actually make calls between different devices?

I did the following steps. 

## Preparation
- The server side uses the sample at https://github.com/twilio/voice-quickstart-server-node .
- Processing related to TwiML App
  - Set the TwiML App Voice item to hit [/placeCall](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L99)
![スクリーンショット 2020-04-01 13 50 28](https://user-images.githubusercontent.com/32233401/78106235-f02c3200-742d-11ea-9952-4ff4bedf4017.png)

## Execution procedure
1. Build with identity set to `bob` on the device.
1. Build with identity set to `alice` on another device.
1. Make outgoing call from `bob` to `alice`.

## Results
Outgoing and incoming are successful. However, the call is disconnected as soon as Alice receives the call.

## Call Logs
![_2020-04-01_13 46 12](https://user-images.githubusercontent.com/32233401/78106476-6df03d80-742e-11ea-925d-bcdcd2fa39aa.png)

Looking at the log, the server and the client are communicating. I think that bob and alice can not realize the call.

## Questions
1. Since the from part of the log is `quick_start`, if I change it to `bob`, can I talk?
2. Is it wrong to set [/placeCall](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L99) in TwiML Request URL?
3. Isn't sample code(including server side) just enough to make client to client call?

**Comment by bchen-twilio** [comment]
Hi @tsuyoshi777 

Thanks for providing the details.

Instead of using the `/placeCall` endpoint, you can use the `/makeCall` endpoint for the alice-bob call scenario.

The `/placeCall` endpoint uses the Twilio REST API client to place outgoing calls to the callee, while the `/makeCall` [endpoint](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L68) returns a TwiML response (based on the parameter values) which will make a call to a number (<Number), to a client identity (<Client>) or play a short message to the caller (<Say).

Let me know if this helps your use case.

-bobie

**Comment by tsuyoshi777** [comment]
Thanks for your reply @bchen-twilio.

Using the `/makeCall` endpoint, outgoing and incoming were successful!

But I can't talk because the call ends immediately when another person having another device answer. Looking at the status of the log, I notice that this is `Not Answer`.Is it necessary to write code other than the sample for the process after the response to talk with another person?

### Call Logs
<img width="1216" alt="スクリーンショット 2020-04-02 16 10 21" src="https://user-images.githubusercontent.com/32233401/78241864-09131100-751c-11ea-8411-f09148488d33.png">

**Comment by bchen-twilio** [comment]
Hi @tsuyoshi777 

Thanks for the update.
Can you provide a Twilio Call SID or the TwiML response returned by your ngrok server? Just in case some unexpected error happened, the `.trace` level SDK log from both the caller and callee mobile clients would also be helpful.

-bobie

**Comment by tsuyoshi777** [comment]
Hi @bchen-twilio

I found out that the cause of the problem is that the accept process on the called side is not working.
Thanks to you, the call was successful!

Thank you very much!

**Comment by bchen-twilio** [comment]
@tsuyoshi777 

Glad to hear that the issue has been resolved and things are working!
I am closing this ticket but please feel free to reach out to us.

Cheers,
-bobie
