### ISSUE TITLE
the operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.).

### ISSUE THREAD

**Issue by palsantosh** [twilio/voice-quickstart-ios#332]
This error occurs when I try to hangup the call from my custom calling screen end button click. 
This error happens on second attempt. First time call disconnected successfully, but in second trials when receive call and answer call, & after few moments when I try to hangup call it shows error "the operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)."

This happens only when I try to update CXProviderConfiguration. I want to make dynamic locaize name for caller
var callKitProvider: CXProvider?
var callKitCallController: CXCallController?

func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {

let configuration = CXProviderConfiguration(localizedName: "XXXXXXX")
configuration.iconTemplateImageData = UIImage(named: "ic_logo1")!.pngData()
callKitProvider = CXProvider(configuration: configuration)
callKitCallController = CXCallController()
callKitProvider?.setDelegate(self, queue: nil)
DispatchQueue.main.async(execute: {() -> Void in
                // The Voice SDK will use main queue to invoke `cancelledCallInviteReceived:error:` when delegate queue is not passed
                TwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self, delegateQueue: nil)
            })
        }

**Comment by bchen-twilio** [comment]
Hi @palsantosh 

The `com.apple.CallKit.error.requesttransaction error 4.` usually indicates that an invalid UUID has been passed to CallKit. In this case (ending a call), it could be an UUID that was never reported to CallKit or the call associated with the UUID has been ended and the UUID is removed from the record. Please make sure you are using matching UUID with the CallKit provider objects in your application.

**Comment by bchen-twilio** [comment]
Hi @palsantosh 

Hope everything is well.
I am closing this ticket since there has been no updates for a while and assuming that the original issue has been resolved. Please feel free to reopen or file a new issue if you are still experiencing problem using the SDK.

Thanks,
-bobie
