### ISSUE TITLE
Twilio + China (CallKit is disabled, possibly PushKit is disabled too)

### ISSUE THREAD

**Issue by gerchicov-bp** [twilio/voice-quickstart-ios#334]
### Description

Apple forbids using of CallKit for China, also:
https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit
```
If you are unable to support CallKit in your app, you cannot use PushKit to handle push notifications. Instead, configure your app's push notification support with the UserNotifications framework. If you need to do work in response to an incoming notification—for example, to decrypt content—use a notification service extension to perform that work.
```
Any guide for using Twilio in China with these limitations?

### Steps to Reproduce

No steps

#### Code

No code is required

#### Expected Behavior

Works via `UserNotifications`.

#### Actual Behavior

Apple just rejects apps for China which use CallKit with "CN" locale.

#### Reproduces How Often

100%

#### Logs

none

### Versions

Any version

#### Voice iOS SDK

Any version

#### Xcode

Any version

#### iOS Version

Any version, for example, iOS 11-13

#### iOS Device

Any iPhone

**Comment by idelgado** [comment]
Use a queue: https://www.twilio.com/docs/voice/queue-calls

The caller will call into your TwiML server application and be enqueued (https://www.twilio.com/docs/voice/queue-calls#caller). Additionally your server can send a notification of some kind to the callee with the name of the queue to join.

The callee will get the notification and call connect into Twilio with the queue name that the TwiML app can then use to dial into the queue (https://www.twilio.com/docs/voice/queue-calls?code-sample=code-dialing-a-queue-2).

**Comment by gerchicov-bp** [comment]
@idelgado you speak about the server part. It is well described and it seems we understood it and can use it now.
But what to do with iOS part? This repository doesn't have mentions of an appropriate "queue" code. So the code for working with queues is hidden/wrapped in twilio sdk isn't it?
Could you add some info about how to use it in iOS/swift?

**Comment by idelgado** [comment]
In both cases the user should call `connect(...)` on the SDK and ensure that the TwiML App specified in the access token performs either the enqueue behavior if it is the caller or dialing into the queue if this is the callee.

As for how you signal the callee, this is up you, as we are circumventing APNS altogether in this case.

**Comment by bchen-twilio** [comment]
Hi @gerchicov-bp 

Hope this finds you well.
Please feel free to reach out to us if you need help connecting calls in you application.

-bobie

**Comment by gerchicov-bp** [comment]
@idelgado @bchen-twilio thanks. It seems to be fine but the customer is paused this project so it wasn't finished and tested properly.
