### ISSUE TITLE
callSid from (activeCall?.sid)! and twilio cloud function response are different

### ISSUE THREAD

**Issue by editrShakil** [twilio/voice-quickstart-ios#339]
when i make a call, i am getting two different call sid from (activeCall?.sid)! and twilio cloud console. why is that? therefore i am unable to record live call. 
please let me know how can i be able to solve this issue,

`
async function makeCall(context, event, callback) {

    var to = event.to;
    var from = event.from;
    let subaccountSid = event.sid;
    let subaccountAuthToken = event.token;
    var call;

    var url = "https://demo.twilio.com/docs/voice.xml";

    if (isNumber(to)) {
        var client = require('twilio')(subaccountSid, subaccountAuthToken);
        console.log("Calling to number:" + to);
        call = await client.api.calls.create({
            method: 'GET',
            statusCallback: 'https://flavescent-kudu-6876.twil.io/callbackStatus',
            statusCallbackMethod: 'POST',
            statusCallbackEvent: ['initiated', 'answered', 'ringing', 'completed'],
            url: url,
            to: to,
            from: from,
        });
    } else {
        console.log("Calling to client: " + to);
        var client = require('twilio')(subaccountSid, subaccountAuthToken);
        call = await client.api.calls.create({ //.api
            method: 'GET',
            statusCallback: 'https://flavescent-kudu-6876.twil.io/callbackStatus',
            statusCallbackMethod: 'POST',
            statusCallbackEvent: ['initiated', 'answered', 'ringing', 'completed'],
            url: url,
            to: 'client:' + to,
            from: from,
        });
    }
    console.log(call.sid)
    return JSON.stringify(call);
}
exports.handler = function(context, event, callback) {
    var p1 = new Promise(function(resolve, reject) {
        resolve(makeCall(context, event, callback));
    });

    p1.then(function(value) {
        console.log("val : " + value); // "Success!"
        callback(null, value);
        throw new Error('oh, no!');
    }).catch(function(e) {
        console.error("error : " + e.message);
    });
};

function isNumber(to) {
    if (to.length == 1) {
        if (!isNaN(to)) {
            return true;
        }
    } else if (String(to).charAt(0) == '+') {
        number = to.substring(1);
        if (!isNaN(number)) {
            return true;
        }
    } else {
        if (!isNaN(to)) {
            return true;
        }
    }
    return false;
}`
Please check this code, is there anything wrong? please let me know.

**Comment by bchen-twilio** [comment]
Hi @editrShakil 

The Call SID you are seeing on your server app is from the parent leg of the call. In this case Twilio will make another call to your mobile client, which will be the child call leg and they are two different calls therefore different Call SIDs.
