### ISSUE TITLE
How to pass custom parameters with Twilio voice in Objective-C ios?

### ISSUE THREAD

**Issue by vuadoc** [twilio/voice-quickstart-ios#344]
Description
How to pass custom parameters with Twilio voice in Objective-C ios?

Steps to Reproduce
I want to pass custom parameters with Twilio voice for showing a "from" readable name when receiving an incoming call. 
I have read this doc https://www.twilio.com/docs/voice/how-share-information-between-your-applications#retrieving-custom-parameters

In my backend server (python), I have 2 cases:
1. Use dial instruction and TwiML
2. Use dial instruction and add participant to conference

In case 1, I can retrieve custom parameters from TVOCallInvite.customParameters.
In case 2, i don't see any custom parameters in client app.

So what I need to setup in case 2 to send custom parameter from server and retrieve in client app?

Voice iOS SDK
Using TwilioVoice (5.3.1)

Xcode
Xcode 11.3.1

iOS Version
All versions above 10

iOS Device
On All Devices

**Comment by bchen-twilio** [comment]
Hi @vuadoc 

Thanks for reaching out and thanks for providing the comprehensive description about the issue.
I am glad that custom params are working in case 1. Is it possible for you to share some more detail of case 2? I am especially curious about what is TwiML response returned from your app endpoint and how the participants are invited to the conference.

Thanks,
bobie

**Comment by vuadoc** [comment]
Thank for your reply
This is the way I invite the callee to the conference (i use aloha for testing)

`participant = client.conferences(conference_id).participants.create(
                from_=from,
                to=f"{to}?identity=aloha",
                timeout=conf_timeout,
                status_callback_event=['completed', 'ringing'],
                status_callback_method="GET",
                status_callback=callback_url,
            )
`

**Comment by bchen-twilio** [comment]
Hi @vuadoc 

Thanks for the update.
I looks like you are using the REST API client to invite the participants. I will need some time to research how to embed (if possible) custom params in this case and will keep you updated.

-bobie

**Comment by bchen-twilio** [comment]
Hi @vuadoc 

I've read through the [participants documentation](https://www.twilio.com/docs/voice/api/conference-participant-resource) and found that you can also provide custom parameters when inviting mobile clients: https://www.twilio.com/docs/voice/api/conference-participant-resource#custom-parameters

All you have to do is append URL-encoded parameter list in the `to` param like this
```
  to="aloha?mycustomparam1=foo&mycustomparam2=bar"
```

I've tried this and I was able to see the custom parameters on the callee mobile client.

Let me know if this works for you.

-bobie

**Comment by vuadoc** [comment]
Hi bobie,
Thank for your reply.

I will try to fix in backend server and let you know if this works. 
However, I want to confirm where you retrieve the custom parameters on the callee mobile client. Is it also in **TVOCallInvite.customParameters** of the delegate - **(void)callInviteReceived:(TVOCallInvite *)callInvite** (same as in case 1)?

**Comment by bchen-twilio** [comment]
Yes, you should be able to see the custom params in the `TVOCallInvite` object once the call notification reaches the callee client.

**Comment by bchen-twilio** [comment]
Hi @vuadoc 

I am assuming that you have already figured out how to use the custom parameters with TwiML and the TVOCallInvite object. Closing this ticket for now but please feel free to reach out to the team anytime.

Cheers.
