### ISSUE TITLE
sendDigits

### ISSUE THREAD

**Issue by vpcunha** [twilio/voice-quickstart-ios#345]
Hi there. I'm a total newbie in programming so I'd like some help. I'm developing an IOS app and I've followed the Twilio Voice Quickstart for iOS tutorial.
Everything is fine and the app is working, but I'm not sure if what I did is correct as to how to send DTMF signals.
In my code when the user taps a button the signal is sent, as in the example bellow:
    
    @IBAction func sendTwo(_ sender: UIButton) {
		if let call = self.activeCall {
            call.sendDigits("2")
        }
    }

But in another post (https://github.com/twilio/voice-quickstart-ios/issues/216), this action was recommended:

- (void)provider:(CXProvider *)provider performPlayDTMFCallAction:(CXPlayDTMFCallAction *)action {
    [self.call sendDigits:action.digits];
    [action fulfill];
}

Although my app seems to be working fine, I'd like to know if I have to do something different, like using the following delegate method of the CXProviderDelegate protocol. And, if yes, how should I code it?

    func provider(_ provider: CXProvider, perform action: CXPlayDTMFCallAction) {

	}

**Comment by bchen-twilio** [comment]
Hi @vpcunha 

Thanks for reaching out and it's nice that you were able to follow the guide and built your working Voice app!

The method you implemented is correct. The implementation in the `CXProvider` callback method is to fulfill the action when the user taps on the system call UI when the call is integrated with the CallKit framework.

**Comment by vpcunha** [comment]
Ok.
Thanks a lot for the prompt answer!
