### ISSUE TITLE
Call drops few seconds after app is going to background

### ISSUE THREAD

**Issue by rakefetWorkiz** [twilio/voice-quickstart-ios#346]
### Description

Calls are dropping few seconds after the device display turns off.
That happens only while connected to wired headphones.
In Twilio console I see the following error : `Call is terminated due to RTP timeout. No audio received from callee`
The audio from both sides of the call works well until the call drops.

### Steps to Reproduce

1. Connect wired headphone to iPhone.
2. Make a call
3. Keep the call active until iPhone display turns off
4. After few seconds - the call drops.

#### Expected Behavior

I expect call to continue, no matter the status of the display, or which headphone I use.

#### Reproduces How Often

100%

#### Logs

From Twilio console: 
```
Msg | "Call is terminated due to RTP timeout. No audio received from callee."
ErrorCode | "32014"
LogLevel | "WARN"
```

#### Voice iOS SDK
5.0.0 via CocoaPods

#### Xcode
11.4

#### iOS Version

13.4.1

#### iOS Device

iPhone Xs

--- 
UPDATE: 

after much more investigaion - I found out the app is terminated when having a call in the background (probably because voip is heavy task, so the os kills it), few seconds after the app goes to background.

this is not happening when the user is not on call.

I need help preventing that

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

Thanks for reaching out.
Is it possible for you to provide SDK log (`.trace` level would be the best) or the Twilio Call SID when this happens?

The `RTP timeout` error that caused the call to be disconnected is a mechanism we use to detect if no audio is received from the call participants for longer than a minute.

Couple of questions to help us debug the issue:
- Does the call stay connected if the device is not locked?
- Does this happen using the quickstart?

Cheers,
-bobie

**Comment by rakefetWorkiz** [comment]
Hi @bchen-twilio 

This was reproduced on production, so it kinda hard for me to get you the log.
Call SID for example would be : CAb9d6e2c8f753d1ad7da2aa732da698e0

as for you questions, 

 - if the device is not locked the call wouldn't drop.
and if the device is is connected to bluetooth headset or if the device is not connected to any headset - the call also won't drop.

- this is happening with code copied from the quickstart into our app code.

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

Thanks for the update!

I have checked the Call SID and from it I didn't see any signs of audio or network quality issues that could have caused the problem.

It sounds like this probably is happening particularly with the wired headset. Is it possible to gather more information about the headset? It would be great if we can try that and see if we can reproduce in your dev environment.

-bobie

**Comment by rakefetWorkiz** [comment]
Thanks @bchen-twilio 
I will give it a try tomorrow in dev, and update here with a log.

**Comment by rakefetWorkiz** [comment]
@bchen-twilio 
I can't do it dev mode, because the second the screen locks, it looses connection with xcode, and disconnect the call, even if I don't use headphones. So the only log I get is the that app went to background..

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

When you lock the device during an active call, did you receive the `provider:performEndCallAction:` callback from CallKit?

**Comment by rakefetWorkiz** [comment]
Hi @bchen-twilio 

I appreciate you help, and sorry about the delay

I have tried in many different ways, but couldn't reproduce it in dev env. either the call drops the second I turn off the screen, with no CallKit callbacks logs, and connection to xcode disappears, or the call go through with no issue.

But it still reproduces in production. every time.

here are some more details.

I am making a call out.
about 25 seconds after the other side answer the call and the call starts, my screen locks.
about 10 seconds later - the call disconnects in my end.
in the other end (the receiver) the call continues for about another minute, getting no sound from my end.
then the call disconnects.

above that - when I go the those calls recording (both numbers are Twilio, and all calls are recorded), 
the recording of both calls (outgoing & incoming) go all the way to the end of the call.
but from the second the call mysteriously disconnected on my side - the sound of the call is only from the other side of the call. (continuing for a minute on both recordings)

new call SID example: CAd5f0ae94e13121191e58ab39fa16aebc
the call was disconnected around 1:15 in this call. 
I kept talking from the other side, thinking maybe there is just no voice input, and voice output still works, but all the sound in the rest of the call comes from the other end of the call.

any idea what could cause that and how I could solve it?

**Comment by bchen-twilio** [comment]
Thanks for the update @rakefetWorkiz 

From the description, it seems like the app is suspended by iOS when you lock the device and the app is backgrounded (resigned from active state).

I used the quickstart and tried the steps, but when I locked the screen CallKit disconnected the active call and the other side of the call was also disconnected. Can you replace the credentials and let us know the behavior when you run the quickstart in your environment?

**Comment by rakefetWorkiz** [comment]
@bchen-twilio 
Thank you again for you help :) 

I tried running the quickstart, and had no issues.
when I run my app now with release scheme, I can see the app gets killed few seconds after it goes to the background.
the only suspicious messages I got are : 

`2020-05-24 17:35:00.743784+0300 workiz[1167:320854] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"`

(^ I get that right after the call connects)

`Message from debugger: Terminated due to signal 9`
(^ I get that when the call disconnects , and the app gets killed.. )

I have Sentry in my app to track crashes - and I get no crash report on that :-/ 

I read that `Terminated due to signal 9` usually shows up when there is a memory leak in the app. but the only task I have in background is this call, that is managed same way you do in the quickstart.

Even updated my app to use Twilio SDK 5.3.1 (instead of 5.0.0), to be up to date, but it didn't change much.

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

Sorry for the delay of getting back to you.
Is it possible for you to use the Mac OS Console app to see if anything related logged when this happens? You just have to connect the device and you should be able to view the system log of the device. It can be a lot of debugging messages but sometimes some of them are quite informative.

**Comment by rakefetWorkiz** [comment]
Hi @bchen-twilio 

I never knew about the option Mac OS Console app  😅(I am a react native developer, and really new to iOS / swift developing .. ) , So first of all, thanks for this tip!

So when filtering logs to "Errors" , I get those messages : 

**When call starts:** 
Process: mediaserverd. 
Message: AudioSessionServerImp.cpp:268:TranslateCMSessionErrorCode: { "action":"set_property", "error":"translating CM session error", "session":{"ID":"0x22402","PID":635,"name":"workiz"}, "details":{"calling_line":2929,"error_code":-16983,"error_string":"Operation denied. IO currently running"} }

**When call terminated in the background** 
Process: runningboardd . 
Message:  RBSStateCapture remove item called for untracked item <RBProcessMonitorObserver: 0x10131e8f0; <RBProcess: 0x100d473e0; 635; identity: application<com.workizeasy>>; configCount: 0>

**Comment by bchen-twilio** [comment]
Thanks for the update @rakefetWorkiz.

While I could not identify what could have caused the app being terminated from the error messages, we might need you to broader the search in all levels of device logs. What also makes me wonder is that you mentioned that this does happen in the quickstart sample app we provide - did you check the background capability configuration in Xcode between the apps and find out any difference in settings or perhaps audio related implementation?

**Comment by rakefetWorkiz** [comment]
@bchen-twilio 

I just spent about 8 hours comparing the quickstart & my code,
and It's all the same.

I have in background mode all these capabilities: 

```
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
		<string>remote-notification</string>
		<string>voip</string>
	</array>
```

I even written again the whole Twilio section in my app, just to make sure I am using the same & updated code..
That didn't help.
The app still gets killed after few seconds in background.

I had the same issue with the android app, that was killed by android after going to background while in call.
I managed to solve it in android having reported to the OS of ongoing service in background.

But I can't find a way to do the same in iOS. or to report in anyway to the OS that this is an important process, so it won't get killed..

**Comment by bchen-twilio** [comment]
Thanks again for the update.

I totally understand the pain going back & forth and inside out but still can't locate the problem.
I went back to the beginning of this thread and was wondering - is it still true that this only happens when using headsets or a specific headset?

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

How are things going on your end? In case the issue is still bugging you, I do have a hunch and here is my theory - in the original description you use the device lock button to turn off the display, and with CallKit integrated this will trigger an end-call action. In previous versions, the entire disconnect process might end prematurely as soon as the audio stopped flowing and the app will be move to the suspended states or even terminated. Since the flow is ended too soon, the call connection is not torn down completely.

Can you try and see if the experience is improved with the latest [5.3.1 SDK](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#531)? We have added a background-task wrapper to guarantee SDK operation can finish before the app is transitioned to the suspended state.

Thanks.

**Comment by rakefetWorkiz** [comment]
Hi  @bchen-twilio 

Originally - when I thought the issue was just with with wired headset - I didn't use the the device lock button, but waited for the device to lock itself. (that was back when I still used 5.0.0 SDK)

I upgraded to 5.3.1 few days ago, and re-copied the code from the getting started. but after I that I started experiencing this issue whenever app is moving to background (with no regard to the headset I use or don't)
But I can't be sure this is related for the version, as I could still reproduce it with my production version - that was still 5.0.0. 
(Maybe iOS updated that I didn't notice.. idk..)

As for the background task wrapper you mentioned - should I add something in the code for that to work?
Or the fact that I upgraded the SDK should do the trick? 

I did try to learn how to use background-task in swift (that is the fix I used for android), but couldn't find anything helpfull 

Thank you

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

Sorry for the delay of getting back to you.

The background task we did in the SDK is to make sure the `invite.reject()` or `call.disconnect()` operation can finish before the system puts the app to the suspended mode when no background audio is flowing.

If the call audio stops when you simply put the app to the background, then I would suggest that you take a look at the project setting, especially the raw xml format of the xcode project file and compare the background capability configuration with the quickstart since you mentioned that call audio works fine in your environment with the quickstart sample app.

**Comment by rakefetWorkiz** [comment]
@bchen-twilio 

Hi :) 
As I wrote before - I have the same background capabilities, and a little more.

This is from my app: 

```
        <key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>location</string>
		<string>remote-notification</string>
		<string>voip</string>
	</array>
```

This is from the Quickstart: 

```
        <key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>voip</string>
	</array>
```

**Comment by rakefetWorkiz** [comment]
hi @bchen-twilio 

I am happy to report that I found the source of the issue :) 
We had a UI component that was trying to render animation while the is in background..
That caused a memory leak, and combined with the call in the background - ios killed the app 

Fixed that 

Thank you very much for all the help!

**Comment by bchen-twilio** [comment]
Hi @rakefetWorkiz 

Glad to hear the issue is resolved.
If it's possible, would you share the rendering part of the code? I am wondering if this is worth adding some test cases in the SDK for validation.

I will close the ticket since the original issue has been resolve, but please feel free to reach out to the team anytime.

-bobie
