### ISSUE TITLE
Issue getting the incoming call

### ISSUE THREAD

**Issue by divyanshub024** [twilio/voice-quickstart-ios#348]
### Description
There is an issue while receiving the incoming call. Sometimes it does work and sometimes it doesn't. Although the code for it is the same.

Twilio call logs show `no answer`. 

#### Logs

```
initializePushKit
pushRegistry:didUpdatePushCredentials:forType:
Successfully registered for VoIP push notifications.
```

### Versions

```
pod 'TwilioVoice', '~> 5.3.1'
```

#### Xcode

v11.4.1

#### iOS Version

v11.4.1

#### iOS Device

iphone 7

**Comment by bchen-twilio** [comment]
Hi @divyanshub024 

Please provide Twilio Call SIDs when you are experiencing issue receiving incoming call notifications on your mobile client. Please also check if your application is handling the VoIP notification and reporting incoming calls to CallKit properly otherwise the users might not be able to see the incoming calls when the app is not in the foreground.

**Comment by procedurallygenerated** [comment]
@bchen-twilio CAec666211f31c749e3078c538ac79aeb4

The push notification never arrived at the iOS device. The issue we have is that it does work sometimes, but not always.

**Comment by bchen-twilio** [comment]
Thanks for the Call SID @procedurallygenerated .

As far as I can tell from the log of the Call SID, the identity `OoHfJbR5hmtq8QFinfSD` of the callee didn't exist at the time when the call was made. Please check your application and see if the mobile client is properly registered for call notifications or perhaps unregistered.

**Comment by divyanshub024** [comment]
Hey, @bchen-twilio every time we launch the app I'm registering for Twilio voice and I even get the logs that it's successfully registered. 
`Successfully registered for VoIP push notifications.`

After this, I try to make a call and but it works sometimes and sometimes it doesn't. I can see `OoHfJbR5hmtq8QFinfSD` is there on my access Token. Is there any other place I need to check for `OoHfJbR5hmtq8QFinfSD`. I can send you access Token if you want. 

Thanks a lot for the help 🙏

**Comment by bchen-twilio** [comment]
Hi @divyanshub024 

Thanks for the update.

From the records I saw that the identity was used for registration only after the call (CAec666211f31c749e3078c538ac79aeb4) was made. Please check and see if you are able to receive calls on the mobile client now.

**Comment by divyanshub024** [comment]
Hi @bchen-twilio!!

Yes, you are right to call started working later. 

How can I make it register before the call? Because as soon as app launches I'm registering for the TwilioVoice.

```
    func credentialsUpdated(credentials: PKPushCredentials) {

           let cachedDeviceToken = credentials.token
           /*
            * Perform registration if a new device token is detected.
            */
        TwilioVoice.register(withAccessToken: self.twilioAccessToken, deviceToken: cachedDeviceToken) { error in
               if let error = error {
                   print("An error occurred while registering: \(error.localizedDescription)")
               } else {
                   print("Successfully registered for VoIP push notifications.")
                   
                   /*
                    * Save the device token after successfully registered.
                    */
                   UserDefaults.standard.set(cachedDeviceToken, forKey: kCachedDeviceToken)
               }
           }
       }
```
The code we are using is almost the same as given in the [sample app](https://github.com/twilio/voice-quickstart-ios/tree/master/SwiftVoiceQuickstart). 

And I'm making the call when it prints  `Successfully registered for VoIP push notifications`. 
Please let me know how can I make it register before the call?

Thanks a lot 🙏

**Comment by bchen-twilio** [comment]
Hi @divyanshub024 

Unless explicitly unregistered, the mobile client should be able to receive incoming call push notifications even when the app is not in the foreground or the device is locked.

**Comment by divyanshub024** [comment]
Hey @bchen-twilio !!

Yeah, I've already checked that and we are not explicitly unregistering it. But I'm still facing the same issue. Although call seems to work after 5-10 mins but not immediately after installing the app. This has become a critical issue for us because AppStore has rejected our app because we were using Twilio for only outgoing calls and they said that if you use VoIP permission than you need to have an incoming call as well. I want to know if it is necessary to have both features (incoming & outgoing call) if we are using the Twilio Voice SDK. 

Please tell us how can we debug this issue. 
Thanks a lot 🙏

**Comment by bchen-twilio** [comment]
Hi @divyanshub024 

Is the capability to receive VoIP notification for incoming call required in your application?
From our past experience, you will need to provide detailed steps for the auditors to validate your app, especially when your app claims to support VoIP.

One suggestion is to create separate Apple VoIP certificate for your dev app and production app. You will need two different Push Credential SIDs for the two environments.

Again, please provide Twilio Call SIDs when you are having trouble receiving incoming call notifications so we can take a look and investigate if there is any issue.

**Comment by divyanshub024** [comment]
Hey @bchen-twilio !!

Here is the call sid: CAf71d21b08a207830a916e74bdc594148

The VoIP permission is already enabled and we generated the push credentials for the production app.

**Comment by shaunc869** [comment]
Yes the inbound is required, Apple won't let our app go live without it.

**Comment by bchen-twilio** [comment]
Thanks for the Call SID @divyanshub024. Does this happen to other identities as well or it's only this identity or some specific identities, especially the ones used during both dev phase and production phase?

**Comment by divyanshub024** [comment]
@bchen-twilio Yes, it was happening for any identity. But now after creating different sub-account and mobile push credentials it's working fine.
