### ISSUE TITLE
Wrong caller name on callee side 

### ISSUE THREAD

**Issue by JohnLennon145** [twilio/voice-quickstart-ios#351]
### Description

Hello,

I'm having an issue with the quickstart demo.

I have installed the `voice-quickstart-server-node` as my local server, strictly following the instructions without any modification, so I also have a forward URL using `ngrok`, and an `.env` file with the expected credentials.
I have then installed the iOS Swift quickstart app on two devices, each of them sharing the same `baseURLString` corresponding to my server URL, and I have set `bob` as the identity of the first device, `alice` for the other one. These are the only modifications I have made to the iOS quickstart project.

With these parameters the call happens fine, but the caller name doesn't appear as expected on the callee side, let's say `bob` calls `alice`, instead of seeing `bob` on `alice`'s device I'm always seeing `quick_start` on the call screen. Is this server-side related or do I need to change something on the iOS app code?

Thank you for your help,

Kind regards

**Comment by bchen-twilio** [comment]
Hi @JohnLennon145 

(Why is there Beatles music playing in my head...)

In the server quickstart (node.js) there is a hardcoded `callerId` value in [server.js](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L7). You need to modify this part and use the identity that works for your business logic, just remember to prefix the non-number client identity with `client:` so it would show as is.

Hope this helps.

-bobie

**Comment by JohnLennon145** [comment]
Ok, so this is actually server-side, which is what I was thinking. Thank you for your answer!

Also, I'd like to ask another question. If I should create a new issue just let me know, here is my concern:
I have actually two different iOS apps, let's say `app A` and `app B`. I want the users of the `app A` to be able to call the users of the `app B`.
I have learned from the server and iOS voice quickstarts (which are really well explained and straightforward) how to create a push credential from a single app using a VoIP certificate, and use it in my server `.env` file.
But since I need to handle two different apps in my use case, I guess I will have to create two different VoIP certificates, one for each app, then create two different Twilio Push Credentials, and here is where I'm stuck : what should I do here, server-side speaking? I only know how to use one `PUSH_CREDENTIAL_SID` value.

Thanks a lot again!

(And btw, that's because The Beatles are the best!)

**Comment by bchen-twilio** [comment]
Thanks for the update @JohnLennon145.

The most important (other than using the same Twilio Account SID) is that your need to make sure the access tokens you get on `app A` and `app B` contains the correct Push Credential SIDs for each VoIP certificate, assuming they have different bundle IDs.

Since the example we provided is a request-based web server app, one way to achieve this is to add arguments in the access token request url and return corresponding credential in the token on your server app:

pseudo code:
// mobile app
```
  accessToken = fetchFromURL("https://pennylane.io/accessToken?app=app-b")
```

// server app
```
function tokenGenerator(request, response) {
    app = request.body.app;
    pushCredentialSid = nil;
    if (app == "app-a") {
        pushCredentialSid = PUSH_CREDENTIALS_SID_A;
    } else if (app == "app-b") {
    }
}
```

**Comment by JohnLennon145** [comment]
Wow... how did you guess my URL was this one? 🤣
Very clear! Thank you very much for your help and your kindness!

**Comment by ybhwang** [comment]
Is it possible to customize caller name?
I cannot find any solution without `Identity`, only display which I set Identity.

**Comment by ybhwang** [comment]
> Hi @JohnLennon145
> 
> (Why is there Beatles music playing in my head...)
> 
> In the server quickstart (node.js) there is a hardcoded `callerId` value in [server.js](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L7). You need to modify this part and use the identity that works for your business logic, just remember to prefix the non-number client identity with `client:` so it would show as is.
> 
> Hope this helps.
> 
> -bobie

Is it possible to customize `caller name`? (I use only `Client Identity`, not PhoneNumber)
I cannot find any solution without `identity`, only display which I set Identity :(

I want to know any properties can set!

**Comment by bobiechen-twilio** [comment]
Hi @ybhwang 

Thanks for reaching out. Indeed the `identity` parameter in the access token is default value that will be used as caller name when the call reaches Twilio and the other participant, and there are some limitation in terms of the characters you can use for this value.

However with the SDK, you can leverage the custom parameter property of Call Invite. Not sure the language of helper library you are using but here is an example in node.js:

```
const VoiceResponse = require('twilio').twiml.VoiceResponse;

const response = new VoiceResponse();
const dial = response.dial();
const client = dial.client();
client.identity('user_jane');
client.parameter({
    name: 'FirstName',
    value: 'Jane'
});
client.parameter({
    name: 'LastName',
    value: 'Doe'
});

console.log(response.toString());
```

then when `user_jane` receives the Call Invite, you should see `{FirstName: Jane, LastName: Doe}` in `TVOCallInvite.customParameters` and you can use the value for your app display.

-bobie

**Comment by ybhwang** [comment]
> Hi @ybhwang
> 
> Thanks for reaching out. Indeed the `identity` parameter in the access token is default value that will be used as caller name when the call reaches Twilio and the other participant, and there are some limitation in terms of the characters you can use for this value.
> 
> However with the SDK, you can leverage the custom parameter property of Call Invite. Not sure the language of helper library you are using but here is an example in node.js:
> 
> ```
> const VoiceResponse = require('twilio').twiml.VoiceResponse;
> 
> const response = new VoiceResponse();
> const dial = response.dial();
> const client = dial.client();
> client.identity('user_jane');
> client.parameter({
>     name: 'FirstName',
>     value: 'Jane'
> });
> client.parameter({
>     name: 'LastName',
>     value: 'Doe'
> });
> 
> console.log(response.toString());
> ```
> 
> then when `user_jane` receives the Call Invite, you should see `{FirstName: Jane, LastName: Doe}` in `TVOCallInvite.customParameters` and you can use the value for your app display.
> 
> -bobie

Can you send DM with [Discord](https://discordapp.com/users/ybhwang#2952) or [Reddit](https://www.reddit.com/u/ybhwang)?
