### ISSUE TITLE
Need some explanation on the lifecycle of a call reception

### ISSUE THREAD

**Issue by JohnLennon145** [twilio/voice-quickstart-ios#352]
Hello,

I am still a beginner with the use of Twilio, and I am a bit confused with the reception of a voice call, notably between `CallKit`/`PushKit` and `TwilioVoice` interactions. So far, I have understood that : 

- First, `PushKit` delegate `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` first gets called to notify the app of an incoming VoIP push,

```
func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType) {
    pushTwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self, delegateQueue: nil)
}
```
- Then, `TVOCallInvite` delegate `callInviteReceived` gets called and an incoming call is reported:

```
func callInviteReceived(_ callInvite: TVOCallInvite) {
    let callHandle = CXHandle(type: .generic, value: from)
    let callUpdate = CXCallUpdate()        
    callUpdate.remoteHandle = callHandle
    callUpdate.supportsDTMF = true
    callUpdate.supportsHolding = true
    callUpdate.supportsGrouping = false
    callUpdate.supportsUngrouping = false
    callUpdate.hasVideo = false
    callKitProvider.reportNewIncomingCall(with: uuid, update: callUpdate) { error in
        if let error = error {
            NSLog("Failed to report incoming call successfully: \(error.localizedDescription).")
        } else {
            NSLog("Incoming call successfully reported.")
        }
    }
}
```

- And finally, depending on the user action, `TVOCallDelegate` methods get called (`callDidConnect`, `didFailToConnectWithError`...).

I have two questions about all this : 
- Can I show the default, iOS native call UI after answering the phone call?
- If not, when should I display it? I tried to display my phone call modal in `TVOCallDelegate`'s `callDidConnect`, but there is a multi-second delay when doing so between the disappearance of the incoming call modal and the appearance of my modal.

Thank you for your help!

**Comment by bchen-twilio** [comment]
Hi @JohnLennon145 

Sorry for my delay of responding back to your questions.

- For calls integrated with CallKit, the only way that the incoming call stays in the native call app is when the incoming call is received while the device is locked.

- From the app's perspective, I would suggest that you continue with your app's UI/UX when incoming calls are received as if there is no CallKit integration, that way when the view transitions back to the app things would look smooth, for example a call duration timer started when the `callDidConnect:` callback is received. That being said, it's up to the application's business logic to determine what is the best user experience.

Hope this answers your questions.

-bobie
