### ISSUE TITLE
Notify last registered device instead of 10 devices by default

### ISSUE THREAD

**Issue by hand228** [twilio/voice-quickstart-ios#357]
### Description

As I know, Twilio will notify last 10 registered devices according to this [FAQ](https://www.twilio.com/docs/voice/voip-sdk/android/faq#incoming-calls-and-registration-for-push-notifications)

> Twilio will notify only most recent 10 registered device and the rest of the devices will not receive notification.

My issue is I only want to notify last registered device and the others will not receive notification. How can I config this using TwilioVoiceSDK or TwilML?

Could you help me please?

**Comment by bchen-twilio** [comment]
Hi @hand228 

The Programmable Voice SDK supports multiple devices to be registered with the same client identity at the same time. To not receive notifications on other devices, you need to explicitly call the `TwilioVoice.unregister()` method to remove the bindings.

**Comment by hand228** [comment]
Hi @bchen-twilio 
Thank you for your response.
In my case, it is impossible for a device to know that another device register with same identity. Is there any other solution on server side?

**Comment by hand228** [comment]
@bchen-twilio 
Could you help me please?

**Comment by bchen-twilio** [comment]
Hi @hand228 

Currently we are relying on the application to unregister the bindings. To work around this, you 
will have to use any mechanisms that work for your business logic and notify the mobile clients to unregister using the `TwilioVoice.unregister()` method. For example you can keep a record in your server database of the clients and use the regular APN push notifications to tell the mobile clients.

Sorry for the inconvenience.

**Comment by hand228** [comment]
Hi @bchen-twilio 
Thanks for your reply. I will try this solution.
This issue will be closed.
