### ISSUE TITLE
TVODefaultAudioDevice crash when i am using https://cobrowse.io/ SDK

### ISSUE THREAD

**Issue by PinkeshGjr** [twilio/voice-quickstart-ios#358]
### Description

TVODefaultAudioDevice got crash showing multiple webRTC connection.

i am using cobrowse app connect my application using remote functionality. Cobrowse provide remote access to you application from there dashboard.

### Steps to Reproduce

1. Connect your device using remote functionality using cobrowse SDK
2. Initiate call using remote from cobrowse SDK
3. App got crash showing multiple connection of webRTC on this line TVODefaultAudioDevice

#### Expected Behavior

I have active connection with cobrowse SDK and when i try to call from cobrowse using there dashboard app should work properly.

#### Actual Behavior

I have active connection with cobrowse SDK and when i try to call from cobrowse using there dashboard app got crash.

#### Reproduces How Often

Always

#### Logs

```
*** Terminating app due to uncaught exception 'TVOAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created call or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'
```

#### Voice iOS SDK

twilio_voice_version = '5.4.0'

#### Xcode

version = '11.5'

#### iOS Version

version = '13.5'

**Comment by bchen-twilio** [comment]
Hi @PinkeshGjr 

As the exception message indicates, the application needs to set up the audio device before making calls with the SDK and can only re-configure the audio device when all calls are finished. Your application probably is simply following the quickstart sample code but is there any chance that it could be assigning the audio device while the call has been disconnected completely?

Also does the crash happen when using the quickstart? or does the crash happen without using cobrowse.io?

**Comment by bchen-twilio** [comment]
Hi @PinkeshGjr 

How are things? I am hoping that my previous comment did help you resolve the crash issue. Happy to hear from you in case you still need assistance.

**Comment by PinkeshGjr** [comment]
@bchen-twilio i am still getting issue. When i try to call from cobrowse SDK app get crash with above details.

**Comment by bchen-twilio** [comment]
Hi @PinkeshGjr 

Thanks for the update.
As I mentioned in the previous comment, our suggestion is to take a look at how the lifecycle is managed, especially the SDK Call object and any UI elements or model object in your app logic that keep the ownership of the SDK. It would be also useful to try the quickstart and let us know if the exception happens under the co-browse environment.

**Comment by bobiechen-twilio** [comment]
Closing the ticket since there has not been update for a while. Feel free to reach out to the SDK team.
