### ISSUE TITLE
How to not record a call history in iOS system phone app

### ISSUE THREAD

**Issue by tsuyoshi777** [twilio/voice-quickstart-ios#360]
Hi,

I don't want to record call history in iOS system phone app. 
Is it possible to not record call history in iOS system phone app?

**Comment by bchen-twilio** [comment]
Hi @tsuyoshi777 

The SDK does not control the experience, however this seems to be possible: https://stackoverflow.com/questions/43681157/how-to-disable-saving-callkit-calls-in-history.

**Comment by tsuyoshi777** [comment]
Hi @bchen-twilio 

Thank you for reply. I'll try it!
