### ISSUE TITLE
Issue when using  answerOnBridge flag in your TwiML response 

### ISSUE THREAD

**Issue by datmassdevs** [twilio/voice-quickstart-ios#361]
Hello Team,
I checked issue # 178
https://github.com/twilio/voice-quickstart-ios/issues/178
I used answerOnBridge to dial () But when accept or reversed the call it all called the callDidConnect function.
Purpose: How do I distinguish user accept or reverse 1 call.
Please tell me what should I do?  Thank you.

**Comment by bchen-twilio** [comment]
Hi @datmassdevs 

Did you get the `callDIdConnect:` callback on the caller side?
And by "reverse" I guess you mean using the `[TVOCallInvite reject]` method?

With `answerOnBridge` enabled in the TwiML app, the caller will receive the `TVOErrorBusyHereError (31486)` error in the `call:didFailToConnectWithError:` callback. The caller will receive the `callDidConnect:` callback if the callee accepts the call.

**Comment by datmassdevs** [comment]
Hi bchen,
Thanks for the reply to my case.
I am using it when I call the user. And whether the user accept or set down will call callDidConnect: callback. And it doesn't call didFailToConnectWithError callback if the user falls. Only receive callDidConnect: callback

**Comment by bchen-twilio** [comment]
Thanks for the update @datmassdevs 

It seems to me that the answerOnBridge flag is not actually enabled based on your description. Can you provide a Twilio Call SID of the call and your server endpoint logic where the TwiML response is generated?

**Comment by bobiechen-twilio** [comment]
Closing ticket since there has not been any response for a long time. @datmassdevs I am assuming that you managed to resolve the original issue and things are working. Please feel free to reach out again.
