### ISSUE TITLE
when I call from app (From Twillio) to any mobile number I want  live  Audio stream of mobile number side 

### ISSUE THREAD

**Issue by milanTbi** [twilio/voice-quickstart-ios#364]
Description
when I call from app (From Twillio) to any mobile number I want  live  Audio stream of mobile number side 

Steps to Reproduce
-> our concept is we call from app (From Twillio) to any mobile number and we want Audio stream of how are talk from mobile number continuously like Live audio stream

So Please give suggestions on how I get a remote audio stream

Voice iOS SDK
Using TwilioVoice (5.1.1)

Xcode
Xcode 11.2.1

iOS Version
All versions above 10

iOS Device
On All Devices

**Comment by bobiechen-twilio** [comment]
Hi @milanTbi 

For accessing the raw data of the remote party, you can refer to the [TVOAudioDevice interface](https://twilio.github.io/twilio-voice-ios/docs/5.5.0/Protocols/TVOAudioDevice.html) (you might need to look into the header file in the framework package) and more specifically the [TVOAudioDeviceRenderer protocol](https://twilio.github.io/twilio-voice-ios/docs/5.5.0/Protocols/TVOAudioDeviceRenderer.html), where you can find the delegate method for your custom audio device to grab the audio data that is to be played back through the speaker or any custom operation that suits your business logic.

You can also take a look at the [ExampleAVAudioEngineDevice](https://github.com/twilio/voice-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m) example app, which showcases the custom audio device usage.

Feel free to let us know if you need any help.

-bobie
