### ISSUE TITLE
Camera hangs after 10 seconds on remote side tcp_input [C12.1:3] is not receive frequently 

### ISSUE THREAD

**Issue by amandevthb** [twilio/voice-quickstart-ios#365]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Twilio Call SID(s)

You can find the Call SID in the SDK from TVOCall.sid or TVOCallInvite.callSid. The Call SID can also be found on the Twilio Calls Console: https://www.twilio.com/console/voice/calls/logs.

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bobiechen-twilio** [comment]
Hi @amandevthb 

We might need you to fill in more detail about the issue, but it looks like you need help with the Video iOS SDK?

**Comment by bobiechen-twilio** [comment]
Closing ticket since there hasn't been response for a while. Please feel free to reach out again.

**Comment by ceaglest** [comment]
If its about the video SDK, let us know if you need any help getting going in http://github.com/twilio/video-quickstart-ios/.
