### ISSUE TITLE
Voice Conference

### ISSUE THREAD

**Issue by smartphone-pro** [twilio/voice-quickstart-ios#370]
### Description

This is not an issue but a question about how to implement voice conference.

I'm building a voice conference app using Twilio.
I was able to successfully implement one-to-one voice call according to the guide.
To create a voice conference, I changed the makeCall of server.js.

```js
function makeCall(request, response) {
  // The recipient of the call, a phone number or a client
  var type = null;
  var to = null;
  var from = null;
  if (request.method == 'POST') {
    type = request.body.type;
    to = request.body.to;
    from = request.body.from;
  } else {
    type = request.query.type;
    to = request.query.to;
    from = request.query.from;
  }

  const voiceResponse = new VoiceResponse();

  if (type == 'conference') {
    const dial = voiceResponse.dial();
    dial.conference(to);
  } else {
    if (!to) {
      voiceResponse.say("Congratulations! You have made your first call! Good bye.");
    } else if (isNumber(to)) {
      const dial = voiceResponse.dial({callerId : callerNumber, answerOnBridge: true});
      dial.number(to);
    } else {
      const dial = voiceResponse.dial({callerId : from, answerOnBridge: true});
      dial.client(to);
    }
  }
  console.log('Response:' + voiceResponse.toString());
  return response.send(voiceResponse.toString());
}
```

But it still seems to recognize the input parameter as callerId.

So my question is what kind of parameters are in TVOConnectOptions that indicate the conference?
Or I want you to tell me what I'm missing.

Thank you for your cooperation.

#### Swift Code

```swift
let connectOptions = TVOConnectOptions(accessToken: accessToken) { builder in
    builder.params = [
        "type": "conference",
        "to": conferenceId
    ]
}
TwilioVoice.connect(with: connectOptions, delegate: self)
```

#### Logs

```
didFailToConnectWithError: Temporarily Unavailable
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

TwilioVoice 5.5.0 via CocoaPods

#### Xcode

11.5

#### iOS Version

13.5.1

#### iOS Device

iPhone 7 Plus
iPhone Pro Max

**Comment by bobiechen-twilio** [comment]
Hi @smartphone-pro 

Thanks for reaching out. Your Swift and server component implementation looks correct to me at the first glance. Are you able to see `type: conference` in the argument list when the endpoint receives the request? We can also use a Twilio Call SID if you have one handy and we can check if the parameters from your mobile client are propagated to the Voice URL request correctly.

-bobie

**Comment by smartphone-pro** [comment]
Thank you for your reply.
I wasn't sure if the parameters were delivered correctly, so I commented on all the rest of the codes and tested them with only the following codes.

```js
const dial = voiceResponse.dial();
dial.conference(to);
```
But I confirmed that it still remains in the calls history, not in the conferences history.
My App SID is `AP30081a2e5ad09da6ea39934e1d72f723`.

I also followed the following guide to deliver the custom parameters.
[https://www.twilio.com/docs/voice/how-share-information-between-your-applications](url)
Is there any need for further manipulation?

Thank you for your cooperation.

**Comment by bobiechen-twilio** [comment]
Thanks for getting back @smartphone-pro.

We can use the Call SID, which you think should have resulted in a \<Conference\> call but instead of \<Client\>, you find in the Call History page and see the TwiML & parameter list of the request.

**Comment by smartphone-pro** [comment]
Thank you for your reply.

I modified makeCall as follows.
```js
function makeCall(request, response) {
  var to = null;
  if (request.method == 'POST') {
    to = request.body.to;
  } else {
    to = request.query.to;
  }

  const voiceResponse = new VoiceResponse();
  const dial = voiceResponse.dial();
  dial.conference(to);
  console.log('Response:' + voiceResponse.toString());
  return response.send(voiceResponse.toString());
}
```

But the history still remains in the Calls.

**Comment by bobiechen-twilio** [comment]
Can you provide a Call SID?

**Comment by smartphone-pro** [comment]
SID: SK987bbcd2ba3b8cca232386ed317c4e37
App SID: AP30081a2e5ad09da6ea39934e1d72f723

What is Call SID?

**Comment by smartphone-pro** [comment]
![1](https://user-images.githubusercontent.com/31697777/88000075-b8114200-cb37-11ea-8dfd-364ecd280c32.jpg)

It's my calls history.
ConferenceId is recognized as clientId.

**Comment by bobiechen-twilio** [comment]
Hi @smartphone-pro 

I modified your previous comment to mask the API key. Please refrain to share any of your account credentials in the public forum. In the Call History view, you can see Call SID (`CAxxxx`) if you click into any of the calls. I will need a Call SID to help you.

**Comment by smartphone-pro** [comment]
I knew that the prefix of the client was client:
Is there a prefix in the conference?

**Comment by smartphone-pro** [comment]
Thank you.

`CAaa7f8ac05bece6f80228a25b41252e25`
`CA9e918eec843951faba80ec7572d103f5`
`CAdd12c958cd7cd6b83b8aa5420bee986d`
`CAc7627adea054e0875e53df3e6d0b1ace`

I have attached the last 4 call SIDs.

**Comment by bobiechen-twilio** [comment]
Thanks for the Call SIDs.
I have checked the calls but I didn't see `type` in the parameter list. Please check your iOS implementation and make sure you are passing the correct parameters in the `TVOConnectOptions`.

**Comment by smartphone-pro** [comment]
I deleted the `type` because I didn't need it when I modified the code on the server side.
I have attached the call SIDs that it was added again.
Please check.
Thank you.

`CA2b9a5b7fca0f725339be5fd3f5dfe71b`
`CAaf46ff81e65db9edde626a4212fba6b1`
`CA258891009e974329ef5ba2825c61ac69`
`CA27d37fff7d03960d69013dbe18181f6a`

**Comment by bobiechen-twilio** [comment]
You might want to check the server URL you specify in the TwiML Application SID because it returned \<Client\> TwiML responses for both calls
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Dial callerId="client:is_conference" answerOnBridge="true">
    <Client>K8MQk*******ozZu</Client>
  </Dial>
</Response>
```

Maybe you are not using the correct URL or you have updates that are not deployed yet?

**Comment by smartphone-pro** [comment]
I'm sorry for the trouble.
I was setting the wrong url.
I can make a successful call now.
Thank you for your help.

**Comment by smartphone-pro** [comment]
One more thing, I'm also building a one-on-one video call.
When I start the call, I want to send the VoIP push notification to the recipient.
I think Twilio does not notify the recipient by default because the video call is based on the room.
Is there a RestAPI that sends VoIP push notification to the recipient, such as a one-on-one voice call?
Thank you.

**Comment by bobiechen-twilio** [comment]
Hi @smartphone-pro 

Thanks for the update and glad that the problem has been resolved.
As you already figured out, Twilio Video offers room-based video conferencing features therefore applications need to implement their own invite mechanism. For more information or if you need more help with the Video SDK, please visit the [Video iOS quickstart repo](https://github.com/twilio/video-quickstart-ios).

**Comment by smartphone-pro** [comment]
@bobiechen-twilio Thank you very much.
