### ISSUE TITLE
Target SDK should be changed to 11.0 or higher

### ISSUE THREAD

**Issue by davidgyoung** [twilio/voice-quickstart-ios#371]
### Description

Archiving the quickstart app or trying to run on a device with iOS 10.x or earlier fails the build with an error like:

```
ld: warning: ignoring file TwilioVoice.framework/TwilioVoice, missing required architecture armv7 in file TwilioVoice.framework/TwilioVoice (2 slices)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_TVOCall", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOAcceptOptions", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOCallInvite", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVODefaultAudioDevice", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TVOConnectOptions", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_TwilioVoice", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This problem is caused by the fact that this quickstart app has a deployment target of iOS 10 [see here](https://github.com/twilio/voice-quickstart-ios/blob/master/ObjcVoiceQuickstart.xcodeproj/project.pbxproj#L254).  That needs to be changed to iOS 11, because your Frameworks no longer support iOS 10.  Starting with iOS 11, XCode no longer requries armv7 architecture, and your frameworks are apparently built to not include it.  So if you try to deploy to iOS 10, or archive (which by default archives all architectures that the deployment target supports) you get the error above.

I realize that is is atypical to archive a quick start app, but it is common for folks to use this as a starting point for their own apps.  I wasted an hour trying to figure out what I thought was a Cocoapods linking problem only to find that it is that the deployment target cannot be 10.0 if using your framework.  So please just change that line so you save somebody else the trouble.

### Steps to Reproduce

1. Open Voice QuickStart iOS 
2. Set a Development Team
3. Product -> Archive

#### Code

N/A

#### Expected Behavior

You can archive the app or run it on any device with the deployment target.

#### Actual Behavior

Linker error.

#### Reproduces How Often

100%

#### Twilio Call SID(s)

N/A for Buildtime issue

#### Logs

N/A for Buildtime issue

### Versions

Applies whenever deploying to a device with iOS 10.x or lower or Archiving for release.

#### Voice iOS SDK

5.5.0 and 5.4.1, but probably applies to any SDK version since you made the SDK's deployment target iOS 11+

#### Xcode

11.4.1

#### iOS Version

Tested with XCode Archive, but applies to iOS 10.x and lower

#### iOS Device

Tested on iPhone 11

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out and reporting the issue @davidgyoung!
We will update the quickstart project settings and our documentation to address this.
Sorry for the inconvenience.

-bobie

**Comment by diegogarciar** [comment]
Hello,
Is there a specific reason to why support to iOS 10 was dropped?

**Comment by diegogarciar** [comment]
So as to my understanding the framework can run on iOS 10 devices but cannot be archived if target SDK is set below iOS 11.
I think that what needs to be fixed is the ability to archive with iOS 10 support, not the other way around.

**Comment by markathomas** [comment]
I am also receiving this error.  Is there any workaround?

**Comment by markathomas** [comment]
I fixed by updating the deployment target to 11 in my flutter plugin

**Comment by michael-reznik** [comment]
Managed to make it work by downgrading to 5.3.1, the latest version that armv7 builds are available for.
