### ISSUE TITLE
No Incoming call receiving once app is closed for 5-10 hours!! 

### ISSUE THREAD

**Issue by palsantosh** [twilio/voice-quickstart-ios#373]
I am unable to get any push notification for incoming call into my device. I updated latest iOS SDK and also followed the iOS 13 migration and Twilio 5.x. When I open the app again, then voice call is working fine. But once I closed the app for 5-10 hours or on next day I unable to get calls. I debug and in that case no push I recieve for incoming calls. 

Please let me know wether it's the issue related to access token expiration or any other?

**Comment by bobiechen-twilio** [comment]
Hi @palsantosh 

Can you provide a Twilio Call SID (`CAxxxx`) when you think a call is made but no incoming push notification is received on the mobile client?
Nonetheless the fact that the app is able to receive incoming calls when the app is in the active state makes me think that the SDK should be working fine. Have you checked how the **PyPushRegistry** instance of the PushKit framework is instantiated? In order for the app to properly receive and handle incoming VoIP notifications, the PyPushRegistry instance needs to be created once the app is woken up, especially when the app is suspended/terminated previously and relaunched upon receiving the VoIP push.

**Comment by palsantosh** [comment]
callSid: CAccef06487caba742fdde7990a8315411

**Comment by bobiechen-twilio** [comment]
Thanks for the Call SID @palsantosh 

I have checked the records and here's what I found:
- There were 4 mobile clients registered with the same identity at the time the call was made
- All 4 push notification requests were sent to Apple successfully
- SDK events showed that 2 of the called clients handled the incoming push notifications.

As I mentioned, one of the best practices of PushKit/CallKit integration on iOS 13 is initialize the PyPushRegistry instance as early as possible, preferably in the AppDelegate. Without the PushKit instance set up, the app won't be able to handle incoming push notifications even if the app is woken up from termination.

**Comment by palsantosh** [comment]
PushKit/CallKit integration on iOS 13 is initialize the PyPushRegistry instance as early as possible, preferably in the AppDelegate. 
- Yes I'm doing the same. I'm calling the following function from didFinishLaunchingWithOptions method of appdelegate, and also after fetching the access token from server.

func registerPushKit() -> Void {
        voipRegistry = PKPushRegistry.init(queue: DispatchQueue.main)
        voipRegistry?.delegate = self
        voipRegistry?.desiredPushTypes = Set([PKPushType.voIP])
    }

**Comment by bobiechen-twilio** [comment]
Thanks for the update @palsantosh.
Can you share a little bit more about the part "also after fetching the access token from server"? Are you saying the app creates a new PkPushRegistry instance after you receive the access token from server?

**Comment by palsantosh** [comment]
Yes, I create PkPushRegistry instance after I receive the access token from server. I get AccessToken in func fetchAccessToken() from server side api response. So once I get access token from server end, I create  PkPushRegistry instance and register VoIP push.

**Comment by bobiechen-twilio** [comment]
Hi @palsantosh 

If I am understanding it correctly, you are initializing the PkPushRegistry instance, possibly again, when the Twilio Access Token is fetched from you server endpoint in order to receive the device token from the PushKit callback. Then you can use the access token and the PushKit device token for the `TwilioVoice.register()` method.

Technically the device token for PushKit on a device (for an app bundle ID) won't change unless the VoIP service certificate for the app has been updated. Following our quickstart sample code, once you initialized the PkPushRegistry instance and received the device token, you can safely save it with the applications in case you need it later, e.g. to call the `TwilioVoice.unregister()` method.

Since there is an "expiration" concept in the access token, you will need to use an access token that is valid at the time when calling methods such as `TwilioVoice.connect()` and `TwilioVoice.register()`.

In case you are still seeing issues where no incoming call notification popped up on the mobile client, please send us Twilio Call SIDs so we can take a look.

Thanks,
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @palsantosh 

Just want to check in and see you managed to figure out the problem since we haven't heard back from you for a while. And just curious, any chance you are using the React Native plugin to create your mobile application?

Cheers,
-bobie

**Comment by palsantosh** [comment]
No, I am not using any React Native plugin. My app native iOS app.

**Comment by bobiechen-twilio** [comment]
Hi @palsantosh 

Is your app still initializing the PyPushRegistry instance twice, first when the app is launched and the second time after an Access Token is fetched from your server? Does this happen in your environment (device, network etc.) using the quickstart with your account credentials?

From what we can see, there is no record under your account indicating any error regarding the VoIP notification delivery requests, which means the push notifications are sent to the mobile devices successfully. In case you are still experiencing the described issue, please attach your device and use the MacOS [Console application](https://www.howtogeek.com/406592/how-to-use-the-console-on-macos-to-check-log-and-activities/#:~:text=The%20Console%20app%20in%20macOS,going%20on%20in%20your%20system.) to view the device logs. You might find additional information in the logs.

**Comment by aniketlokhande07** [comment]
Hi,

I am not able to receive incoming call notification when the device locked. Voice call working fine when the device is not locked and the app is active.

**Comment by bobiechen-twilio** [comment]
Hi @palsantosh 

Have you got the chance to check how the PkPushRegistry instance is created and managed in the app?

**Comment by palsantosh** [comment]
Yes, I will try this again and let you know.

**Comment by bobiechen-twilio** [comment]
@palsantosh 
Hope everything is well. It's been a while since we last received updates from you but I guess that means you probably managed to resolve the issue.
Closing the issue for now. Please feel free to reach out if you need further assistance.
