### ISSUE TITLE
call not working

### ISSUE THREAD

**Issue by maulikm235** [twilio/voice-quickstart-ios#378]
I'm new to use twilio, i follow steps and still can't get the call in real device, token generate properly, but always get voice bot message and disconnect call. also in twilio account still have money.

**Comment by bobiechen-twilio** [comment]
Hi @maulikm235 

Thanks for reaching out!
The fact that you are able to hear the congratulatory message indicates you have successfully integrated the SDK. To be able to help you move forward:
- Please describe the use case of your app, e.g. calling from a mobile client to another mobile client.
- What is the server endpoint URL used in the TwiML application? It will affect the App SID you use in the Access Token when calling `TwilioVoice.connect()`.
- Do you know what is the TwiML response returned from your application server?
- If you believe that you have done everything correctly but the problem persists, please provide a Twilio Call SID so we can take a look. They look like this: `CAa22fc092cadf002688f24e99a3258eb1`, and you can find them in the [Call Logs view](https://www.twilio.com/console/voice/calls/logs) in the developer portal.

**Comment by bobiechen-twilio** [comment]
Hi @maulikm235 

Hope you are doing well. We have not heard back from you for a while so I guess you have figured out the problem and calls started to work now. Let us know if you still need assistance.

Cheers,
-bobie

**Comment by maulikm235** [comment]
Hello,

Thank you for your support, i we found issue and solved that and now we 
have another issue that in iOS device call not coming may be it is 
certificate issue.

Again thanks for your support, i appreciates your service is good than 
other.

Thanks and Regards
Maulik Makwana
