### ISSUE TITLE
 52145 - Failed to authenticate with APNs

### ISSUE THREAD

**Issue by shashi180493** [twilio/voice-quickstart-ios#379]
We have two ios applications for driver and customer and we want to make call between these two apps but we are not able to make call between these two apps it is returning following error :

**Error - 52145**
**Failed to authenticate with APNs**

Error description for above mentioned error:
Could not authenticate with APNs using the provided credentials.

Please check following information which i have:

**DEBUG EVENT SID : NO9a4cadbc7f434943b037123d4dccad02
SERVICE SID : PV5b76bf0835dcee2e6fb40a1d2aaefc4a**

We have generated two different APN certificate for both apps.

**Comment by bobiechen-twilio** [comment]
This seems to be related to #380. Closing this one since we already are investigating.
