### ISSUE TITLE
Multiplatform call (Android to iOS) not working.

### ISSUE THREAD

**Issue by shashi180493** [twilio/voice-quickstart-ios#380]
We have two application in Android and iOS and we want to make call from Android to iOS and iOS to Android. We did the changes in `accessToken.php` to determine which push credential sid to put in the access token. After doing this change iOS to Android call is working fine but we are not able to make call from Android to iOS.

**Comment by bobiechen-twilio** [comment]
Hi @shashi180493 

It would be great if you could provide us additional information, such as Twilio Call SID where iOS devices are not getting call notifications. Did you check the Push Credential SID used in the access token in the iOS application? Was you iOS application able to receive VoIP notifications before the change?

**Comment by shashi180493** [comment]
Hi @bobiechen-twilio 

Call SID : CAf64ea29372af061d8155945689813e42.
Yes, i checked Push Credentials SID in the access token.
From iOS to Android it is working but from Android to iOS it is not working, for Android we are using Push Credential of type FCM and for iOS we are using Push Credential of type APN. 

We follow steps mentioned in `README.md`.

**Comment by bobiechen-twilio** [comment]
Hi @shashi180493 

Thanks for the Call SID, although it shows that all the push notifications Twilio sent were for FCM devices. Could it be possible that something went unexpectedly when the iOS application tried to register with the new credential?

**Comment by shashi180493** [comment]
@bobiechen-twilio 

Registration was successful, it is not returning any error during registration.

**Comment by bobiechen-twilio** [comment]
I guess we can use the Push Credential SID used in the iOS application. Can you give us one that you are using in the iOS app?

**Comment by shashi180493** [comment]
Sure @bobiechen-twilio 

Push Credential SID for iOS app : CRebe7722412cc0d463e8a1d36770a218b

**Comment by bobiechen-twilio** [comment]
Thanks @shashi180493.
From the records it looks like notifications associated with this credential started to fail today, most possibly due to it being updated.

**Comment by shashi180493** [comment]
@bobiechen-twilio 

I also tried the same by generating new Credentials but not working.

**Comment by shashi180493** [comment]
Hi @bobiechen-twilio 

We tried again after updating APN & FCM certificate details but still facing same issue, can you please help us to fix this issue.

**Comment by bobiechen-twilio** [comment]
Sure @shashi180493 

Do you have a Call SID where you are seeing the problem after the credentials are updated?

**Comment by shashi180493** [comment]
Thanks for the reply @bobiechen-twilio 

Here is the Call SID : CAda0f729e709d1e88ef77cd12dc7c6699.

**Comment by bobiechen-twilio** [comment]
Hi @shashi180493 

The records show that
- The VoIP pushes started to fail since August 5th
- The first attempt to update the Push Credential happened at August 6th

It seems to me that VoIP service certificate was either revoked or had expired between 5th and 6th. Please check the validity of the VoIP Service certificate and update the Push Credential with valid keys.

**Comment by shashi180493** [comment]
Hi @bobiechen-twilio 

Thanks for the help, I fixed this issue by deleting all the certificates and generated new one.
Now it is working fine.

Closing this issue as it is fixed now.

Thank you @bobiechen-twilio

**Comment by codewithglocify** [comment]
I am having the same issue, iOS to Android audio and video call is working fine.

Facing issue in when calling from android and receiving on iOS,

but Video call is working fine in both the scenario. Having issue when receiving call on iOS device.

Have updated key and cert on Twilio and my server.

Android to android—audio/ video working fine.
iOS to android—audio/ video working fine.
iOS to iOS video is working fine.
iOS to iOS audio is failing on receiver side.
Android to iOS audio is having same issue in case of audio call,
