### ISSUE TITLE
issue for ending incoming call

### ISSUE THREAD

**Issue by aniketlokhande07** [twilio/voice-quickstart-ios#382]
Hi,

getting issue while disconnecting voice call

Error: EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.).

this error came while ending the call

first time working fine, second time get an incoming call and fire end call function gets above error

**Comment by bobiechen-twilio** [comment]
Hi @aniketlokhande07 

Thanks for reaching out. What is the state of the app, i.e. in the background or foreground or the device is locked, when the problem happens?

**Comment by aniketlokhande07** [comment]
It happens when the device is in the foreground state.

I got an incoming call and accept it, and later I hangup call received above error.

**Comment by bobiechen-twilio** [comment]
Hi @aniketlokhande07 

We have recently updated the sample code, especially around the lifecycle management of the `CXProvider` object. Could you please try the latest quickstart and verify that the bug has been resolved in your environment?

Thanks,
-bobie

**Comment by bobiechen-twilio** [comment]
Closing the ticket since there has not been updates for a while. Please feel free to reach out to us if you still need assistance.
Thanks!
