### ISSUE TITLE
Incoming call notification not getting on iPhone XR

### ISSUE THREAD

**Issue by aniketlokhande07** [twilio/voice-quickstart-ios#383]
Hi,
I am having issues with the incoming calls.

I am able to receive incoming call notification for the following scenario 

1) when the app is active
2) when the app is in background state
3) when the device is locked

for device iPhone 5s, iPhone 6 working fine

but I am not able to get incoming call notification for device iPhone XR

from the above scenario
only first one: **when the app is active** is working fine on iPhone XR and other scenarios not

Not sure what was the issue, please suggest

**Comment by bobiechen-twilio** [comment]
Hi @aniketlokhande07 

Please follow the issue template and provide important information such as Twilio Call SIDs, iOS versions.

**Comment by aniketlokhande07** [comment]
Hi @bobiechen-twilio

**Comment by bobiechen-twilio** [comment]
Thanks for provide the Call SIDs @aniketlokhande07.
From the records, the push notifications of both calls were sent successfully. Any chance your device is in do-not-disturb mode?

Here's what I tried:
- Launch the app and register
- Terminate the app
- Turn on "Do Not Disturb" mode and lock the device

My app didn't ring in this case, whereas when I didn't turn on DnD I was able to get the incoming call ringing when the device is locked.

**Comment by bobiechen-twilio** [comment]
Closing issue since there has not been updates for a while. @aniketlokhande07 please feel free to reach out if you need further assistance. Please provide Call SIDs if you believe you are still having trouble getting incoming call push notifications.

**Comment by umairAsifVeemed** [comment]
I am facing same issue
