### ISSUE TITLE
Unable to make a client to client call

### ISSUE THREAD

**Issue by losernobody** [twilio/voice-quickstart-ios#388]
### Description

I am following the [Quickstart guide](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#twilio-voice-quickstart-for-ios). I am trying to make a client to client call between 2 real devices with different identities as given in the Step 11 of the guide. The call does not happen.

### Steps to Reproduce

1. Run the `SwiftVoiceQuickstart` app on an iPod with identity set to `ipod`.
2. Run the `SwiftVoiceQuickstart` app on an iPad with identity set to `ipad`.
3. From the iPad, make a call to `ipod`.

#### Expected Behavior

On the iPod, a notification or a call screen should appear.

#### Actual Behavior

On the iPad, an automated voice says the word "ipod" and the call is stopped.
On the iPod, nothing happens.

#### Reproduces How Often

100%

#### Twilio Call SID(s)

CA90315846b63134608b8ac8661cb19975

#### Logs

The TwiML Voice Request URL returns following
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="client:quick_start">
        <Client>ipod</Client>
    </Dial>
</Response>
```

#### Voice iOS SDK

TwilioVoice (5.5.0) using CocoaPods

#### Xcode

Version 11.6 (11E708)

#### iOS Version

12.4.8 and 13.6.1

#### iOS Device

iPod Touch 6th Generation and iPad Air 2

**Comment by bobiechen-twilio** [comment]
Hi @losernobody 

Thanks for the Call SID. I have checked the record and for some reason the content type of the TwiML response from your app server is `text/plain`, while a working TwiML response should have `application/xml` as the content type.

You can check out the server sample code in various languages:
- [Java](https://github.com/twilio/voice-quickstart-server-java)
- [NodeJS](https://github.com/twilio/voice-quickstart-server-node)
- [PHP](https://github.com/twilio/voice-quickstart-server-php)
- [Python](https://github.com/twilio/voice-quickstart-server-python)

-bobie

**Comment by losernobody** [comment]
After making the change suggested by you. It works.

Thanks for replying.
