### ISSUE TITLE
Client to client call between accounts

### ISSUE THREAD

**Issue by Dhivysh** [twilio/voice-quickstart-ios#393]
### Description

Is it possible to make a client to client call between two sub account? If it is not possible, can I register the same device for VOIP across accounts?

#### Voice iOS SDK

6.0.0 via CocoaPods

#### Xcode

12

#### iOS Version

14

#### iOS Device

iPhone X

**Comment by bobiechen-twilio** [comment]
Hi @Dhivysh 

The same device can be used to register with different Twilio account credentials as long as the app bundle IDs and PushKit device tokens are different. The combination is used to associate with an unique binding entry on a specific device.

And you probably already figured out - Twilio accounts do not communicate with each other, even between the main and subaccounts.

-bobie

**Comment by Dhivysh** [comment]
Thanks @bobiechen-twilio !
