### ISSUE TITLE
performVoiceCall doesn't work after ending call.

### ISSUE THREAD

**Issue by rushmeh** [twilio/voice-quickstart-ios#395]
Hi,
I'm using Twilio for Voice calls in my app. My problem is when I receive an incoming call, end that call and try to call the caller again, the call doesn't get connected. I get the following when starting a call
"StartCallAction transaction request successful"
"providerDidBegin" 
"provider:performStartCallAction:"
After these logs however the call doesn't initiated.

below is my code:

func performVoiceCall(uuid: UUID, client: String?, completionHandler: @escaping (Bool) -> Void) {
        guard let accessToken = fetchAccessToken() else {
            completionHandler(false)
            return
        }
        
        self.userName = UserDefaults.standard.object(forKey: "username") as? String
        self.firstName = self.userName!.components(separatedBy: " ").first
        
        let receiver = UserDefaults.standard.object(forKey: "receiver") as? String
        
        print(accessToken,receiver, self.firstName)
        let connectOptions = TVOConnectOptions(accessToken: accessToken) { builder in
            
            builder.params = [twimlParamTo: receiver ?? "",
                              twimlParamToName: self.firstName ?? ""]
            print(builder.params)
            builder.uuid = uuid
        }
        
        let call = TwilioVoice.connect(with: connectOptions, delegate: self)
        activeCall = call
        
        print(call.uuid.uuidString)
        activeCalls[call.uuid.uuidString] = call
        print(completionHandler)
        callKitCompletionCallback = completionHandler  
    }
    
 func provider(_ provider: CXProvider, perform action: CXStartCallAction) {
        NSLog("provider:performStartCallAction: \(action.callUUID)")
        
     
//        audioDevice.isEnabled = false
//        audioDevice.block()
        
        print(action.callUUID)
        provider.reportOutgoingCall(with: action.callUUID, startedConnectingAt: Date())
        
       
        performVoiceCall(uuid: action.callUUID, client: "") { success in
            if success {
                NSLog("performVoiceCall() successful")
                provider.reportOutgoingCall(with: action.callUUID, connectedAt: Date())
                
                
            } else {
                NSLog("performVoiceCall() failed")
            }
        }
        
        action.fulfill()
    }

As I had to create a layout for incoming call the following is what I have done
 func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
        NSLog("provider:performAnswerCallAction:")
        
        audioDevice.isEnabled = false
        audioDevice.block()
   
        performAnswerVoiceCall(uuid: action.callUUID) { success in
            if success {
                
                action.fulfill()
                
                let mainStoryBoard = UIStoryboard(name: "Main", bundle: nil)
                let centerVC = mainStoryBoard.instantiateViewController(withIdentifier: "callVC") as! CallVC
                centerVC.receiverName = self.callerName
                centerVC.isIncomingCall = true
                centerVC.audioDevice = self.audioDevice
                centerVC.activeCall = self.activeCall
                let appDelegate = UIApplication.shared.delegate as! AppDelegate
                appDelegate.window?.rootViewController = centerVC
                
                NSLog("performAnswerVoiceCall() successful \(action.callUUID)")
                
                
            } else {
                NSLog("performAnswerVoiceCall() failed")
                action.fail()
            }
        }
        
      
    }

**Comment by bobiechen-twilio** [comment]
Hi @rushmeh 

Looks like the process of requesting a stact-call action was successful but somehow something went unexpected after calling `TwilioVoice.connect()`. What was the TVOCallDelegate callback you received when the call was initiated but not connected (you might also find some more information in the SDK logs for more insights)?

**Comment by rushmeh** [comment]
The TVOCallDelagetes doesn't get called. I get "StartCallAction transaction request successful" , "providerDidBegin" and "provider:performStartCallAction:" after which nothing works.

**Comment by bobiechen-twilio** [comment]
Hi @rushmeh 

Could you please provide the SDK log? What happened after you called `TwilioVoice.connect()`?

**Comment by rushmeh** [comment]
![Screen Shot 2020-09-25 at 4 49 09 pm](https://user-images.githubusercontent.com/10462104/94236387-772b1480-ff50-11ea-9d57-5de7d1bb76dd.png)

**Comment by bobiechen-twilio** [comment]
@rushmeh 
I have removed your previous comment because it contains some of your personal application credentials.
If you follow the quickstart sample, you should be calling the TwilioVoice.connect() method and receive TVOCallDelegate callbacks about the status update of the call, either successfully connected or failed eventually with an error.

**Comment by rushmeh** [comment]
My issues is same as that of #398 issue, calling the same number when I receive and hang up the call and start calling to that number.

**Comment by bobiechen-twilio** [comment]
@rushmeh 
Is there any error message in the SDK log indicating why the call was not connected?

**Comment by bobiechen-twilio** [comment]
Hi @rushmeh 

We have recently updated the sample code and if you believe you are experiencing the issue like you mentioned, please take a look at #400 and apply necessary updates to your app.

**Comment by bobiechen-twilio** [comment]
Hi @rushmeh 
It has been a while since our last conversation. I am assuming the fix addressed the problem you encountered and things are working for you now. Free feel to reach out in the future.
