### ISSUE TITLE
Push Notification issue in iPhone XR

### ISSUE THREAD

**Issue by umairAsifVeemed** [twilio/voice-quickstart-ios#396]
Facing exactly same issue,

https://github.com/twilio/voice-quickstart-ios/issues/383#issue-681854905
@aniketlokhande07

Hi,
I am having issues with the incoming calls.

I am able to receive incoming call notification for the following scenario

when the app is active
when the app is in background state
when the device is locked
for device iPhone 5s, iPhone 6 working fine

but I am not able to get incoming call notification for device iPhone XR

from the above scenario
only first one: when the app is active is working fine on iPhone XR and other scenarios not

Not sure what was the issue, please suggest

**Comment by bobiechen-twilio** [comment]
Hi @umairAsifVeemed 

This does look odd if it only happens on a specific device model. Please provide the following information to help debug the issue:
- Twilio Call SID when you believe the iPhone XR is not receiving the incoming call
- The last 8 characters of the PushKit device token string from the device (iPhone XR). You will need to follow [this](https://stackoverflow.com/a/24979958) to convert the data to string
- The last 4 characters of the Push Credential SID used in the access token on this device

Also you might want to check if you can see anything in the device log from the Mac OS Console application. The fact that you are able to receive incoming call notifications in most of the states and devices, I believe the push notifications were delivered even for this device, but somehow now delivered from iOS to the app.

**Comment by umairAsifVeemed** [comment]
I want to add one comment here,
I am sorry I was a bit wrong,
this issue is not related to "Call" in my case,
This issue is, when someone send the message to 2nd person, the 2nd person doesn't see any notification.
And If he open the App, Go to Message screen, there he can see the message. But there is no Notification shown.
this scenario is working fine in iPhone 6 & iPhone 7
while it isn't working on iPhone XR
which means same thing is working fine on 2 different iPhone models but not on iPhone XR

**Comment by bobiechen-twilio** [comment]
Hi @umairAsifVeemed 

Did you mean using the Twilio Chat SDK  or any other message products of Twilio by "sending message to 2nd person"?
As far as the Programmable Voice SDK is concerned, I didn't see any errors regarding push notification delivery failure standing out using iPhone XR across different iOS versions.

Can you provide more details about the problem you are experiencing?

**Comment by bobiechen-twilio** [comment]
Hi @umairAsifVeemed 

Hope everything is well. We haven't heard from you for a while so I am assuming you have managed to resolve the problem and going to closing this issue. Let us know if you need further assistance.

Cheers,
-bobie
