### ISSUE TITLE
How to handle twilio in background mode, when my initial page is not calling screen

### ISSUE THREAD

**Issue by deftsoftiphone** [twilio/voice-quickstart-ios#399]
I want a help in how can we handle twilio in background or kill mode. I am usinga view controller for calling which is not the initial view controller for app. But I want to handle callkit in case of background or kill mode. Please let me know how can we do the same.

Urgent help required for this

**Comment by bobiechen-twilio** [comment]
Hi @deftsoftiphone 
As the sample code we provided in the quickstart, the most important thing of handling PushKit notification is to always have the PkPushRegistry object initialized at the very beginning of the app, for example the AppDelegate. As long as the PushKit/CallKit policy is complied, the rest is up to your application UI/UX design.
