### ISSUE TITLE
Register success but cannot receive incoming call

### ISSUE THREAD

**Issue by hand228** [twilio/voice-quickstart-ios#402]
### Description

I have one identity registered in 3 devices (an Android device call A1, 2 iOS devices call I1, I2). If I register these 2 devices one by one the later device does not receive VoIP notification. Please see steps below for more information.

### Steps to Reproduce

1. Register device A1. After register several times, A1 can receive VoIP notification.
2. Register device I1. Device I1 does not receive VoIP.
3. Register device I1 again. Device I1 can receive VoIP.
4. Register device I2. Device I2 can receive VoIP
5. Register device A1. Device A1 does not receive VoIP.
6. Register device A1 again. Device A1 can receive VoIP.
7. Register device A1 again. Device A1 still can receive VoIP.

Repeat those steps and I saw that one device cannot receive VoIP notification if it registered after another device (another OS).

#### Code

```swift
            GetTwillioAccessTokenAPI(token: apiToken, callingKind: .voice).execute(showIndicator: false, success: { [weak self] response in
                guard let accessToken = response.accessToken else {
                    return
                }
                TwilioVoice.register(withAccessToken: accessToken, deviceToken: token) { error in
                    if let error = error {
                        NSLog(error.localizedDescription)
                    } else {
                        NSLog("Register notification success")
                    }
                    SharedData.voIPTokenData = token
                }
            })
```

#### Expected Behavior

Device received VoIP when register after another device and OS

#### Actual Behavior

Device cannot receive VoIP when register after another device and OS

#### Reproduces How Often

100%

#### Twilio Call SID(s)

1: CAa255fde8e23210ca773e1b8fae300ee2
2: CA53a653b12688a69117d6d101c5212564
3: CAbbc24d7bf60b77f04ca8c6080c48709d

#### Voice iOS SDK

5.3.0

#### Xcode

XCode 12

#### iOS Version

14.0

#### iOS Device

iPhone 7, iPhone 8 plus

**Comment by bobiechen-twilio** [comment]
Hi @hand228 Thanks for reaching out.

The Programmable Voice SDK allows the same identity to be registered with multiple devices at the same time and, if registered correctly, they will all be able to receive the incoming call.

From the Call SIDs, it looks like some of the iOS clients are not using the correct device token (derived from the app bundle ID and the `aps-environment` value of the entitlements file) when registering. Please check -
- You are using the VoIP Service certificate, the only type supported by the Voice iOS SDK.
- You are using the correct Push Credential SID with corresponding environment (sandbox or non-sandbox).

The [developer console](https://www.twilio.com/console/debugger?quickDate=24) can also help you with the details in case any error happens.

Cheers,
-bobie

**Comment by hand228** [comment]
Hi @bobiechen-twilio 

Thank you for your response.

I will reproduce and check on debugger to find the reason.
