### ISSUE TITLE
Redirecting to custom view while answering the call is not getting done.

### ISSUE THREAD

**Issue by DevGirisankar** [twilio/voice-quickstart-ios#403]
### Description

I have a custom view controller to show for the voice calls.
I'm trying to push to that viewcontroller while receiving the call. It's working while the app is in the inactive state or even in the background state. But if the application is in the killed state, the attend button in the call kit is opening the application, but the pushing to my custom viewcontroller is not working... just launching the app is the only thing getting done
#### Code

```swift
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        NSLog("pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:")
        
        // The Voice SDK will use main queue to invoke `cancelledCallInviteReceived:error:` when delegate queue is not passed
        
        self.payload = payload
        incomingPushCompletionCallback = completion
        if let rootViewController = UIApplication.topViewController() {

            let nextViewController = R.storyboard.voiceCall.voiceCallViewController()!
            audioDevice = DefaultAudioDevice()
            callKitCallController = CXCallController()
            audioDevice.isEnabled = false
            audioDevice.block()
            nextViewController.audioDevice = audioDevice
            TwilioVoice.audioDevice = audioDevice
            nextViewController.fromAppDelegate = true
            nextViewController.callKitProvider = callKitProvider
            nextViewController.callKitCallController = callKitCallController
            callKitProvider!.setDelegate(nextViewController, queue: nil)
            self.pushKitEventDelegate = nextViewController
            
            if let delegate = self.pushKitEventDelegate {
                delegate.incomingPushReceived(payload: payload, completion: completion)
                rootViewController.navigationController?.pushViewController(nextViewController, animated: true)
            }
            completion()

            if let version = Float(UIDevice.current.systemVersion), version >= 13.0 {
                /**
                 * The Voice SDK processes the call notification and returns the call invite synchronously. Report the incoming call to
                 * CallKit and fulfill the completion before exiting this callback method.
                 */
            }
        }
    }
```

#### Expected Behavior

Need to get into custom viewcontroller when the user taps on accept call in call kit.

#### Actual Behavior

The app is launching but not pushing to the custom view.
UIApplication.topViewController() is my custom method to find the top viewcontroller.

#### Reproduces How Often

Always.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

TwilioVoice (6.0.0)

#### Xcode

11.7

#### iOS Version

13.7

#### iOS Device

iPad 6th gen

**Comment by bobiechen-twilio** [comment]
Hi @DevGirisankar 

Please follow the [PushKit best practice guide](https://developer.apple.com/documentation/pushkit/supporting_pushkit_notifications_in_your_app) and make sure you have your PkPushRegistry set up at launch time.

**Comment by DevGirisankar** [comment]
`var voipRegistry = PKPushRegistry.init(queue: DispatchQueue.main)
voipRegistry.delegate = self
voipRegistry.desiredPushTypes = [.voIP]`

No issues with delegates I have done that and I'm getting call while the app in active mode.
Is there anything more that I need to check?

**Comment by bobiechen-twilio** [comment]
Hi @DevGirisankar 

For simplicity, you can create the PkPushRegistry instance in the AppDelegate class and make it sharable across your application components. The most important thing is to set up PushKit at launch time, otherwise the system might not delivery the push notification to your application, particularly when the app was terminated.
