### ISSUE TITLE
Call failed in ios 

### ISSUE THREAD

**Issue by arindam94** [twilio/voice-quickstart-ios#404]
Call failed to connect: Invalid ApplicationSid
Please help me to find out the problem

**Comment by bobiechen-twilio** [comment]
Hi @arindam94 

Thanks for reaching out.
Please provide detailed information suggested in the issue template so we can help you debug the issue.

Have you follow the [TwiML Application section](https://github.com/twilio/voice-quickstart-ios#4-create-a-twiml-application) and embed an Application SID in the access token when making a call?
