### ISSUE TITLE
No audio after changing Ringer and Alert volume

### ISSUE THREAD

**Issue by hand228** [twilio/voice-quickstart-ios#407]
### Description

When I make a voice call then change Ringer and alert volume, I cannot hear any thing from participant.

### Steps to Reproduce

1. Make and join voice call
2. Change Ringer volume to 0
3. Check the audio 

#### Expected Behavior

I can hear from participant normally

#### Actual Behavior

I can't hear any thing from participant

#### Reproduces How Often

100%

#### Twilio Call SID(s)

CA851997c9e9230bb93ffeaf82f713d90b

#### Logs

Log in attached file 
[IPhone DT51 2020-10-14 11_11_56 +0000.log](https://github.com/twilio/voice-quickstart-ios/files/5383168/IPhone.DT51.2020-10-14.11_11_56.%2B0000.log)

#### Voice iOS SDK

6.0.0

#### Xcode

12

#### iOS Version

14 and 13.3

#### iOS Device

Outgoing: iPhone 6s+
Incoming: iPhone 7

![IMG_0162](https://user-images.githubusercontent.com/14069827/96092280-ddbea500-0ef4-11eb-9e36-4b02bf4d86ec.PNG)

**Comment by bobiechen-twilio** [comment]
Hi @hand228 

Thanks for reaching out.
From the log you provided it doesn't seem very clear to me whether CallKit is integrated in your app. I have tried the quickstart, which does integrate with CallKit, and I was able to hear audio both directions and on both participants when I turn the Ringer volume all the way to zero.

**Comment by hand228** [comment]
Hi @bobiechen-twilio 
Of course, I integrated CallKit to receive incoming call (You can see log `provider did begin`). I also tried Quickstart and no problem occur. These are CallKit functions I have implemented in my code:
```
func providerDidReset(_ provider: CXProvider)
func providerDidBegin(_ provider: CXProvider)
func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession)
func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession)
func provider(_ provider: CXProvider, timedOutPerforming action: CXAction)
func provider(_ provider: CXProvider, perform action: CXStartCallAction)
func provider(_ provider: CXProvider, perform action: CXAnswerCallAction)
func provider(_ provider: CXProvider, perform action: CXEndCallAction)
```

I compared the two logs and found that when I change Ringer volume RTCAudioSession change category to `AVAudioSessionCategoryAmbient` in my app but doesn't change in Quickstart app.

Do you have any advice for me? I can provide you my code if necessary.

**Comment by bobiechen-twilio** [comment]
Hi @hand228 

Thanks for the update.
For best compatibility with the Voice iOS SDK please use `AVaudioSessionCategoryPlayAndRecord` before making SDK calls.

**Comment by hand228** [comment]
Thank @bobiechen-twilio for your advice.

I solved this problem by configuring the AudioDevice when call connected and when route change using this method:
```
DefaultAudioDevice.DefaultAVAudioSessionConfigurationBlock()
```

I just want to know why the category and route change when changing Ringer volume.

**Comment by bobiechen-twilio** [comment]
Glad that you were able to use the `DefaultAVAudioSessionConfigurationBlock()` to resolve the issue and get the result you need.
I cannot find the exact issue you faced on the internet, but based on the discussion this looks like the intended behavior when using `AVAudioSessionCategoryAmbient` and the SDK does not have control over.

**Comment by hand228** [comment]
Thank @bobiechen-twilio 

This was resolved so I will close this issue.
