### ISSUE TITLE
Twilio Voice iOS not getting voip push and also not working on multiple environment schemes

### ISSUE THREAD

**Issue by gokiinerds** [twilio/voice-quickstart-ios#409]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

We integrated Twilio voice SDK in our project for Voice call. At first, we had only one environment the voice was done with reference to the Quickstart example for swift. It was working fine except for one issue we were not able to navigate to our custom call view controller when the app is in closed state. This issue is still existing. We were not able to resolve it. But now we have created 3 environment Prod, QA and Dev. Created multiple apps in Twilio n added Voip for each with respect to the local environment apps. Now the voice call is not working in any of the environment, we searched all sources for a solution and attempted replacing certificates still does not work. Has anyone had this issue before? Does anyone have a solution

#### Twilio Call SID(s)

You can find the Call SID in the SDK from TVOCall.sid or TVOCallInvite.callSid. The Call SID can also be found on the Twilio Calls Console: https://www.twilio.com/console/voice/calls/logs.

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bobiechen-twilio** [comment]
Hi @gokiinerds Thanks for reaching out.

Most likely your application is a modified version of the quickstart, which integrates CallKit for call experience. The CallKit framework has made some UX assumptions and in most of the cases I am afraid there is no way to change the behavior, including the ability to use custom (incoming) call UI, which is the most asked request.

For the multiple environment setup, can you share a bit more? are they using the same Twilio account? how are the calls made? do you have any Twilio Call SIDs that we can help debug?

**Comment by bobiechen-twilio** [comment]
Hi @gokiinerds 

Have you managed to resolve the issue you encountered? I am hoping that no news is good news. Let us know if you still need assistance with the SDK.

Thanks.

**Comment by bobiechen-twilio** [comment]
Closing the issue as there hasn't been updates for a while. Please feel free to reach out to us any time.
