### ISSUE TITLE
Not able to play voice mail using url

### ISSUE THREAD

**Issue by aniketlokhande07** [twilio/voice-quickstart-ios#410]
Hi, 
We are recording voice mail for the opponent user if he can't be picked the call.

not able to play voice mail in using URL provided by Twilio

ex:  https://api.twilio.com/2010-04-01/Accounts/ACXXXXX.../Recordings/RE557ce644e5ab84fa21cc21112e22c485.wav

let us know any solution for that.

**Comment by bobiechen-twilio** [comment]
Hi @aniketlokhande07 

Can you describe the feature with more specific steps?

**Comment by aniketlokhande07** [comment]
Hi,
 
we implemented voice mail features for the voice calls.
 
We are connecting a voice call to a number, if the receiver did not pick the call then, we are recording a voice mail for that number.
 
we are able to record and play the voice mail from the Twilio console. we are getting that recording logs in a mobile application with the help of recording API. As the format is given in the documentation for play voice mail using URL, we created like below
 
**Voice mail recording logs:**

{
            CallerName = "<null>";
            From = "+12034569189";
            To = "+12038710662";
            recordingResource =             {
                "account_sid" = AC255536077907e6e344d067770f4a7b16;
                "api_version" = "2010-04-01";
                "call_sid" = CA8d4165804b6a6630e1591439275bda5b;
                channels = 1;
                "conference_sid" = "<null>";
                "date_created" = "2020-08-24T12:58:53+00:00";
                "date_updated" = "2020-08-24T12:58:57+00:00";
                duration = 3;
                "encryption_details" = "<null>";
                "error_code" = "<null>";
                price = "-0.00250";
                "price_unit" = USD;
                sid = RE590ec8095f3a9384df40d4f00e2d5628;
                source = RecordVerb;
                "start_time" = "2020-08-24T12:58:52+00:00";
                status = completed;
                "subresource_uris" =                 {
                    "add_on_results" = "/2010-04-01/Accounts/AC255536077907e6e344d067770f4a7b16/Recordings/RE590ec8095f3a9384df40d4f00e2d5628/AddOnResults.json";
                    transcriptions = "/2010-04-01/Accounts/AC255536077907e6e344d067770f4a7b16/Recordings/RE590ec8095f3a9384df40d4f00e2d5628/Transcriptions.json";
                };
                uri = "/2010-04-01/Accounts/AC255536077907e6e344d067770f4a7b16/Recordings/RE590ec8095f3a9384df40d4f00e2d5628.json";
            };
        }
 
**voice mail URL**: https://api.twilio.com/2010-04-01/Accounts/AC255536077907e6e344d067770f4a7b16/Recordings/RE590ec8095f3a9384df40d4f00e2d5628.wav

 
It's working fine earlier, right now it's not working.

**Twilio reference URL**: https://www.twilio.com/docs/voice/api/recording

**Comment by bobiechen-twilio** [comment]
Thanks for the update @aniketlokhande07 

Let me know if I understood correctly from the record of the Call SID:
- You placed a call to two Twilio Wireless numbers. Once connected, the response of a `/voicemail` endpoint will be executed.
- The `/voicemail` endpoint then redirected the calls to a <Say> & <Record> TwiML response

The part which I am not sure - how does the mobile app (presumably using the Voice iOS SDK) fit into your use case? Are you trying to make calls to the mobile client and play the recordings once the call is accepted and connected on the mobile client's side?

**Comment by umesh180887** [comment]
@bobiechen-twilio 
**How to play audio from this url** : https://api.twilio.com/2010-04-01/Accounts/AC255536077907e6e344d067770f4a7b16/Recordings/RE590ec8095f3a9384df40d4f00e2d5628.wav

Earlier we were able to play audio in android and iOS device by using above url. But now it shows file not found. Above link was accessible from browser also. But now when we open in browser, it asks for authentication. 

Our aim is to fetch user specific voice mails from twilio and show it in android/iOS app side list. And user can play those voice mails in app. 

Looking for your quick update. How to get fully accessible voice mail url in .mp3 or .wav format.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @umesh180887.

The additional authentication may have been introduced recently. Unfortunately this might be the specialized area of the SDK team, I would suggest that you open a support ticket and ask for help regarding direct access to the recordings outside the browser (which might have your credentials cached when you logged in).

Since this is not an SDK specific issue, I will close this one for now but please feel free to reach out to us any time!

**Comment by aniketlokhande07** [comment]
Hi @bobiechen-twilio,
Twilio side I made the below change and voice mail URL working for me

changed **Enforce HTTP Auth on Media URLs** from **enable to disable**
