### ISSUE TITLE
Mac Support or  Mac Catalyst

### ISSUE THREAD

**Issue by chetan1406** [twilio/voice-quickstart-ios#411]
Is Twilio Audio support Mac or Catalyst???

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @chetan1406.
The Programmable Voice iOS SDK currently only supports running on iOS devices and simulators, but we are definitely excited about the new platform support and have also obtained an Apple Silicon machine for development. We will keep the SDK users updated.

**Comment by Vaberer** [comment]
Hello, is there any update or time estimation of when the TwilioVoice will be available to Mac Catalyst?
Thanks

**Comment by bobiechen-twilio** [comment]
Hi everyone,

We have just finished the release of the Voice iOS SDK 6.3.0, which supports the simulator `arm64` architecture on Apple Silicon Macs. Check out the release note here: https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#630

Cheers!

**Comment by shanipatelmoon** [comment]
Hi everyone,
audio input-output working in m1 chip?

**Comment by orj** [comment]
Thanks for supporting M1 simulators. But please also support Mac Catalyst so that iPad/iPhone apps that use Twilio SDKs can be ported to macOS via Mac Catalyst.

**Comment by YoavGro** [comment]
Hi is there any update on the implementation?
We are looking to move to a different provider and this is in our checklist

**Comment by cybex-dev** [comment]
▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬
          E L E G A N T  D O T
▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬

**Comment by cybex-dev** [comment]
Infact, we're looking for some significant additions to Twilio's programmable voice
- web (up to standard with mobile)
- MacOS (swift?)
- Windows (C++?)
- *nix 

@bobiechen-twilio 
Do you know if any additions are planned for this, near term or far out distant future?

**Comment by hawkinbj** [comment]
👋 I'm the PM for the Voice SDKs. This is not a current roadmap priority and that's mainly because we haven't seen much demand for this vs. other feature requests (opportunity cost). I encourage folks to leave a comment here who haven't already so that we can have some data point for future prioritization. If you're a customer with a dedicated Account Rep, please let them know as well.

**Comment by cybex-dev** [comment]
> 👋 I'm the PM for the Voice SDKs. This is not a current roadmap priority and that's mainly because we haven't seen much demand for this vs. other feature requests (opportunity cost). I encourage folks to leave a comment here who haven't already so that we can have some data point for future prioritization. If you're a customer with a dedicated Account Rep, please let them know as well. We actively monitor these Issues/requests and your input is super valuable in how we shape our forward-looking roadmap!

Absolutely fantastic to hear from you @hawkinbj - while I got you here (apologies for the change of topic aswel), do you have anything on the roadmap for FCM integration into Twilio Voice (JS)?

I've had a small discussion [here](https://github.com/twilio/twilio-voice.js/pull/159), though quite limited I highlighted some aspects discussed above - do you have any feedback on this?

_My client (runs a call centre w/ Twilio Voice) is interested in Windows & Mac impl - at present my solution is to use a JS wrapper for native platforms._

**Comment by cybex-dev** [comment]
> 👋 I'm the PM for the Voice SDKs. This is not a current roadmap priority and that's mainly because we haven't seen much demand for this vs. other feature requests (opportunity cost). I encourage folks to leave a comment here who haven't already so that we can have some data point for future prioritization. If you're a customer with a dedicated Account Rep, please let them know as well. We actively monitor these Issues/requests and your input is super valuable in how we shape our forward-looking roadmap!

Absolutely fantastic to hear from you @hawkinbj - while I got you here (apologies for the change of topic aswel), do you have anything on the roadmap for FCM integration into Twilio Voice (JS)?

I've had a small discussion [here](https://github.com/twilio/twilio-voice.js/pull/159), though quite limited I highlighted some aspects discussed above - do you have any feedback on this?

_My client (runs a call centre w/ Twilio Voice) is interested in Windows & Mac impl - at present my solution is to use a JS wrapper for native platforms._

**Comment by wertpoiu** [comment]
> Thanks for reaching out @chetan1406. The Programmable Voice iOS SDK currently only supports running on iOS devices and simulators, but we are definitely excited about the new platform support and have also obtained an Apple Silicon machine for development. We will keep the SDK users updated.

Hi Bobie, hope you are doing well.
i saw you have completed the task.
can you please guide how i can use Twilio voice sdk in apple silicon mac?

**Comment by joshhhhyyyy** [comment]
Despite this issue being marked as completed, Mac Catalyst support is still not available

TwilioVoice.xcframework:1:1 While building for Mac Catalyst, no library for this platform was found in '/Users/$user/Library/Developer/Xcode/DerivedData/$app/SourcePackages/artifacts/twilio-voice-ios/TwilioVoice/TwilioVoice.xcframework'.
