### ISSUE TITLE
TVOAudioDevice errors on first build

### ISSUE THREAD

**Issue by asliu1** [twilio/voice-quickstart-ios#412]
### Description

When building the app for the first time, errors related to TVOAudioDevice will arise. But once a pod install or a make clean deps is ran, and the app is built again, the errors will go away for all subsequent builds. On all jenkins build attempts, this error will be seen and cause the build to fail, making it impossible to build the app for testing and release.

Also referenced this [link](https://github.com/twilio/twilio-video-ios/issues/72) which seems to be very similar

### Steps to Reproduce

1. Pull changes that import TwilioVoice
2. Build the app for the first time

#### Expected Behavior

Build should succeed on first try

#### Actual Behavior

Build fails with errors
<img width="357" alt="Screen Shot 2020-10-27 at 2 58 18 PM" src="https://user-images.githubusercontent.com/6039988/97366638-e43e0c80-1864-11eb-9bd9-58a869c5ba66.png">

#### Reproduces How Often

100% 

#### Logs

11:22:12  [11:22:12]: ▸ ❌  ----/Carthage/Build/iOS/TwilioVoice.framework/Headers/TVOAudioDevice.h:11:1: imported declaration 'TVOAudioDeviceContext' could not be mapped to 'AudioDevice.Context'
11:22:12  [11:22:12]: ▸ NS_SWIFT_NAME(AudioDevice.Context);
11:22:12  [11:22:12]: ▸ ^
11:22:12  [11:22:12]: ▸ ❌  ---/Carthage/Build/iOS/TwilioVoice.framework/Headers/TVOAudioDevice.h:59:1: imported declaration 'TVOAudioDeviceWorkerBlock' could not be mapped to 'AudioDevice.WorkerBlock'
11:22:12  [11:22:12]: ▸ NS_SWIFT_NAME(AudioDevice.WorkerBlock);

### Versions

Swift 5

#### Voice iOS SDK

a binary package was created for v6.0.0 and added to our project via Carthage

#### Xcode

Xcode 12.0.0 build 12A7208

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @asliu1.
I have created a ticket for tracking the issue and will keep you updated.
Sorry for the inconvenience.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @asliu1 

We have finished the release of the [Voice iOS 6.0.1 SDK](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#601), which has the fix for the Swift API naming.
Thanks again for reporting the issue.

Cheers,
-bobie

**Comment by asliu1** [comment]
Thank you @bobiechen-twilio I will update and verify!

**Comment by Harisam26** [comment]
@bobiechen-twilio There were two errors: one with AudioDevice.Context and another AudioDevice.WorkerBlock, both from the same file.. The former is fixed, while the latter still causes the same issue.

**Comment by bobiechen-twilio** [comment]
Hi @Harisam26 

Thanks for catching this. We missed this one in the 6.0.1 release and have published another version of the SDK: [Voice iOS 6.0.2](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#602).

**Comment by asliu1** [comment]
verified that it's working properly now! closing the issue, thank you :)!

**Comment by bobiechen-twilio** [comment]
Great! Thanks again for reporting this one @asliu1
