### ISSUE TITLE
didReceiveIncomingPushWith is not called

### ISSUE THREAD

**Issue by ggurikalsi** [twilio/voice-quickstart-ios#413]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

I am using Twilio Voice Version: 6.0.0 on iOS 14. I have set up the server and app according to the steps provided in this link https://www.twilio.com/docs/voice/voip-sdk/ios/get-started

pushRegistry:didUpdatePushCredentials:forType: is getting called as well as calling functions are working but not receiving the incoming call i.e. didReceiveIncomingPushWith is not called.

VOIP certificate is created as well info regarding key and certificate is also updated on the console. I followed each and every step given in the guidelines but still no notification for the call though I am getting logs for the voice calls in the console.
Kindly let me know if I am missing anything or I need to do some additional coding to get it working apart from the given steps in the docs.

#### Expected Behavior

didReceiveIncomingPushWith should be called with notification pop up

#### Actual Behavior

nothing happens

#### Twilio Call SID(s)

Call SID: CAa47f41a22ae90aaded414cd80596a4a1

### Versions

I am using TwilioVoice version 6.0.0

#### Voice iOS SDK

pod 'TwilioVoice'

#### Xcode

Version 12.0.1 (12A7300)

#### iOS Version

iOS 14.0

#### iOS Device

iPhone XSMax

**Comment by 50shashwat** [comment]
i am having the same issue

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @ggurikalsi.
From the Call SID I can see there are 3 notification delivery attempts. Two of them succeeded but one didn't. From the error code and record it says the push credential (`CR****d4d52`) is actually created using GCM credential. Please check the access token used on this device and make sure you are using the right Push Credential SID.

@50shashwat It would be helpful if you follow the issue template and provide more information, such as Call SIDs.

**Comment by ggurikalsi** [comment]
@bobiechen-twilio thanks for replying; I will check the backend files and will get back to you if it's fixed.

**Comment by ggurikalsi** [comment]
Thanks for your help @bobiechen-twilio
Somehow android credentials were getting used at that time though there were APN credentials.
