### ISSUE TITLE
Connect to an specific CallSid

### ISSUE THREAD

**Issue by aldo-israel** [twilio/voice-quickstart-ios#414]
Hi,

I'm trying to add a conference functionality on my iOS app, right now I can create a TwiML on my server and call the conference participants but I can't find a way to connect my iOS app to that call created with the TwiML.

Is there a way to connect to a specific CallSid or ConferenceSid using the iOS SDK?

Thanks.

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @aldo-israel.

When you say that you are able to call the participant, does it include the iOS client? 
To add a Twilio Client participant, including the mobile client registered for incoming call push notifications, you can use the syntax `client:CLIENT_IDENTITY`. The mobile client should receive a call and accept to join the conference.
Your iOS client can also join the conference directly using the [\<Dial\> + \<Conference\>](https://www.twilio.com/docs/voice/twiml/conference) verbs in the TwiML app used on your mobile client, although in this case your mobile needs to know the conference information (name or SID) via your own update channels such as push notification.

**Comment by aldo-israel** [comment]
Thanks for your response.

At this moment I'm creating the TwiML with the <Conference> verb on my backend (Java) I already have the friendly name, and the sid but I don't know how to connect my app directly to that conference. The "solution" that I'm testing is creating the TwiML on my backend and then calling myself and the other participants.

But that solution is not user friendly.

Thanks.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @aldo-israel. If you already have the friend name of the conference, you can use the `TwilioVoice.connect()` method with an TwiML App SID that returns something like this:
```
<Response>
  <Dial>
    <Conference>Room 1234</Conference>
  </Dial>
</Response>
```

**Comment by aldo-israel** [comment]
I don't fully understand that. I already have a TwiML like that but I don't how to connect to the call using the callSid or the conferenceSid.

How can I use the TwilioVoice.connect() function to do that?

Thanks.

**Comment by bobiechen-twilio** [comment]
@aldo-israel 

1. First you need to create a TwiML app, which generates a response similar to the one in my last comment. Place the conferenceSid in the <Conference> verb.
2. Put this App SID into the Access Token used by your iOS app.
3. Call the TwilioVoice.connect() method with the Access Token.

**Comment by aldo-israel** [comment]
Seems like it will work.

Thank you!
