### ISSUE TITLE
'ConnectOptions' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by smartphone-pro** [twilio/voice-quickstart-ios#420]
### Description

I'm building a voice & video conference app using Twilio.
I am using two SDKs at the same time.
`TwilioVoice` & `TwilioVideo`

There is an error when I try to use `DefaultAudioDevice` and `ConnectOptions`.
> 'ConnectOptions' is ambiguous for type lookup in this context

There is also an error when I try to do the following.
`TwilioVoice.ConnectOptions`
> 'ConnectOptions' is not a member type of 'TwilioVoice'

How can I use the correct `ConnectOptions`?
Please help me.

### Versions

All relevant version information for the issue.

#### Voice & Video iOS SDK

TwilioVoice 6.0.2 via CocoaPods
TwilioVideo 3.7.2 via CocoaPods

#### Xcode

12.2

#### iOS Version

14.2

#### iOS Device

iPhone 7 Plus
iPhone Pro Max

**Comment by piyushtank** [comment]
@smartphone-pro Thanks for reaching out. What have reported is probably a bug in our SDK introduced when we introduced swift naming with the `TVO` prefixes. Ideally we should not have used the the identical names for  `TwilioVoice` class, and `TwilioVoie` framework. Our Video SDK solves this problem by using `TwilioVideoSDK` class name. We will fix this problem in subsequent releases. In the meantime, as a work around, can you move such methods in to a separate swift class/file. Following is a code snippet - 

```swift
// TwilioVoiceUtils.swift

import TwilioVoice

class TwilioVoiceUtils {
    func getConnectOptinos()->ConnectOptions {
         return ConnectOptions(accessToken: "the-access-token");
    }
}
```

**Comment by smartphone-pro** [comment]
@piyushtank Thanks for your message.
Ok, I'll use it as above.
Thanks again.

**Comment by smartphone-pro** [comment]
@bobiechen-twilio Thank you for the information.
Regards!
