### ISSUE TITLE
[Question Help Wanted] TwilioVoice with Custom PushKit

### ISSUE THREAD

**Issue by hardikdevios** [twilio/voice-quickstart-ios#421]
We had already integrated `TwilioVideo` and `TwilioVoice` in our application with Our Logic of Push.

- Front: iOS/Android 
- Back: NodeJS

We have achieved the following things so far 

- Client to Client Call (iOS to Android and vice versa) with Room mechanism of TwilioVideo
- Client to PSTN call (iOS/Android to the mobile number via purchased number) using TwilioAudio 

Now we are building the `IVR` flow where a customer will call on the number and we will route them using Rest API on Node JS and here we have to connect our Support staff(An agent who is either on Android or iOS).

So if we use the Twilio Push service we can register the client and bind the access token on the Twilio server and from there we can provide "client:55" and place a call.

But we want to use our mechanism of sending push to iOS/Android users without relying on the Twilio Push service because we want all control on our Socket server as logic was already implemented.

Any Help?

**Comment by bobiechen-twilio** [comment]
Hi @hardikdevios Thanks for reaching out.
It sounds like [Twilio Call Queuing](https://www.twilio.com/docs/voice/queue-calls) could help solve the design you are trying to achieve - 
- A call to a client identity will be queued by your TwiML application
- You can then use whichever communication channel (socket, custom push notification, etc) to notify your mobile client with the queued call information
- Use `TwilioVoice.connect()` to dial back to the queued call

Some discussion from a [previous thread](https://github.com/twilio/voice-quickstart-ios/issues/334).

Please note that your application is now responsible of handling the lifecycle of the "incoming call" to the mobile client, i.e. notifying the mobile client the time that an incoming call is received as well as the time when the incoming call has ended (hung up by the caller or timed out)

-bobie

**Comment by hardikdevios** [comment]
@bobiechen-twilio 
Thanks for the support, I will try that out and will let you know for sure. I will auto close this issue in few days. one question form the link which you have provided 
`
const response = new VoiceResponse();
response.enqueue({
    waitUrl: 'wait-music.xml'
}, 'support');
`
`wait-music.xml` here is the default one or we can pass any custom XML there?

**Comment by bobiechen-twilio** [comment]
Hi @hardikdevios 

Yes, you can pass a custom TwiML for `waitUrl`: https://www.twilio.com/docs/voice/twiml/enqueue#attributes-waitUrl

**Comment by bobiechen-twilio** [comment]
Hi @hardikdevios 

There hasn't been any update for a while so I am assuming things are working.
Closing the issue for now but please feel free to reach out to us any time.

Cheers,
-bobie

**Comment by hardikdevios** [comment]
@bobiechen-twilio 
Can you please provide the information on how to dial the queue from iOS Swift Application? Here is the sample code that I am trying

```
        let connectOptions = ConnectOptions(accessToken: request.token) { builder in
            builder.params = ["to": request.phone!, "room": request.room]
            
            //builder.params = ["queuename":"support","room": request.room]
        }
        
        // Connect to the Room using the options we provided.
        call = TwilioVoiceSDK.connect(options: connectOptions, delegate: self)
```

**Comment by bobiechen-twilio** [comment]
Hi @hardikdevios 

Your server endpoint, which is pointed by the URL of the TwiML App SID embedded in the access token, should look for `to` and `room` from the request parameter list and use the value(s) to determine what is the TwiML response to be returned. In this case, dial to a queue: https://www.twilio.com/docs/voice/queue-calls?code-sample=code-dialing-a-queue&code-language=Node.js&code-sdk-version=3.x

**Comment by hardikdevios** [comment]
@bobiechen-twilio Thanks will try and let you know
