### ISSUE TITLE
Target integrity error in Xcode 12.3 

### ISSUE THREAD

**Issue by iturrajoel** [twilio/voice-quickstart-ios#422]
I'm getting an error in Xcode 12.3 that was not present before, not even on the last 12.3 beta. 

I have to mention that I'm using Twilio on an iOS app for a couple of years without any similar problem.

### Error

Building for iOS Simulator, but the linked and embedded framework 'Twilio.framework' was built for iOS + iOS Simulator.

### Versions

Xcode 12.3 running on a MacOS 10.15.7
For devices running iOS 14.3

#### Voice iOS SDK

5.5.1 and 6.0.2

#### iOS Device

Simulator, and also physical devices.

**Comment by bobiechen-twilio** [comment]
Hi @iturrajoel 

Thanks for reaching out.
Can you provide a full build log when you encounter the error? I was able to build the quickstart (ObjC & Swift) with the 6.0.2 SDK and Xcode 12.3.

**Comment by bobiechen-twilio** [comment]
Hi @iturrajoel 

Is this still happening in your environment with the latest version of Xcode? Could you provide us logs if still reproducible?

Thanks,
-bobie

**Comment by bobiechen-twilio** [comment]
Closing issue. Please check out the latest [6.2.1 Voice iOS SDK](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#621) for XCFramework & Swift Package Manager support. 🎉
