### ISSUE TITLE
Echo on 6.0.2 when speaker is used

### ISSUE THREAD

**Issue by nalexn** [twilio/voice-quickstart-ios#423]
### Description

The users on Twilio Voice SDK v6.0.2 are hearing echo of them speaking when they turn on the speaker. The previous version (v6.0.1) is not affected by this issue.

### Steps to Reproduce

1. Start a call with SDK v6.0.2
2. Turn on the speaker
3. The phone plays back whatever you say

#### Expected Behavior

There should be no echo

#### Actual Behavior

Echo is there

#### Reproduces How Often

The echoed voice is heard clearly when you start speaking after a pause. A few seconds after SDK seems to start suppressing the echo, although not ideally. There is a noticeable difference between 6.0.2 and 6.0.1

### Versions

Issue introduced in version 6.0.2

#### Voice iOS SDK

6.0.2

#### Xcode

12.3

#### iOS Version

14.0

#### iOS Device

iPhone 6s, iPhone 7

**Comment by ceaglest** [comment]
Hi @nalexn,

Thank you for the report. 

I looked at the changes in [6.0.2](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#602) compared to [6.0.1](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#601) and they were only related to Swift compatibility. I will dig deeper to see if there is anything else in 6.0.2 that could cause differences in echo cancellation behaviour.

Best,
Chris

**Comment by nalexn** [comment]
Hey @ceaglest , we've shipped a new version of our app with a downgraded SDK version to 6.0.1, however, a few users who stayed in touch reported that the update didn't help with resolving the echo issue. I wonder if this was introduced earlier, most of those users didn't have the issue in the past.

**Comment by bobiechen-twilio** [comment]
Hi @nalexn thanks for the update.
Any chance you can provide the Twilio Call SIDs where your users are experience the echo issue?

Best,
-bobie

**Comment by nalexn** [comment]
Hey @bobiechen-twilio 

One user:

```
CA73896deea90d37639d2498d9ad0070da
CA52584caa3fa626815d0677ff830b94bf
CA17aa3ec62709eb7a33d7a922e4b78580
```

Another user:

```
CA73896deea90d37639d2498d9ad0070da
CA52584caa3fa626815d0677ff830b94bf
CA17aa3ec62709eb7a33d7a922e4b78580
```

**Comment by bobiechen-twilio** [comment]
Hi @nalexn 

Thanks for the Call SIDs. I have created a ticket for tracking the issue.
While we are trying to reproduce and triage the issue, is this issue reproducible in your dev environment, other than the the reports from app users?

-bobie

**Comment by nalexn** [comment]
Hey @bobiechen-twilio , this is probably our fault, after a refactoring we've introduced a line of code that was changing the `AVAudioSession` category setting, overriding the `voiceChat` setting that Twilio SDK sets via the `audioDevice`.

A slight echo is always there, even after we've fixed the above, so we'd need to release the fix and have the users try it before I can close this ticket.

**Comment by bobiechen-twilio** [comment]
Hi @nalexn 

Hope you are doing well and have resolved the echo issue. We are happy to hear back from you.

Cheers,
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @nalexn 

I am hoping the echo problem has been resolved with the AVAudioSession config. Closing the issue for now but please feel free to reach out to us in the future.

Cheers,
-bobie
