### ISSUE TITLE
performVoiceCall() failed

### ISSUE THREAD

**Issue by beherasusanta** [twilio/voice-quickstart-ios#424]
func provider(_ provider: CXProvider, perform action: CXStartCallAction) {
        NSLog("provider:performStartCallAction:")
        
        toggleUIState(isEnabled: false, showCallControl: false)
        startSpin()
        
        provider.reportOutgoingCall(with: action.callUUID, startedConnectingAt: Date())
        
        performVoiceCall(uuid: action.callUUID, client: "") { success in
            if success {
                NSLog("performVoiceCall() successful")
                provider.reportOutgoingCall(with: action.callUUID, connectedAt: Date())
            } else {
                NSLog("performVoiceCall() failed")
            }
        }
        
        action.fulfill()
    }
What we need to send in place of client: "".I think this is the reason i am getting above error.

**Comment by bobiechen-twilio** [comment]
Hi @beherasusanta 

Sorry that we couldn't get back to you sooner.
Can you provide the debugging log so that we can help you figure out why it failed?

**Comment by bobiechen-twilio** [comment]
Hi @beherasusanta 

Have you found the error that caused the start call failure?

**Comment by beherasusanta** [comment]
No i didn't find any solutions.
________________________________

**Comment by bobiechen-twilio** [comment]
Hi @beherasusanta 

Did you find any error message from the SDK log or CallKit framework log? Also did you get the same failure when using the quickstart sample app in your environment?

**Comment by shanipatelmoon** [comment]
i also facing same error so please help

**Comment by bobiechen-twilio** [comment]
Hi @shanipatelmoon Could you provide detail (error messages, SDK log, steps and expected/actual behavior)?

**Comment by JoeFerrucci** [comment]
It's probably the case that your `.env` file contains wrong values for one of the five different keys. Double-check that your values for each key are correct: `ACCOUNT_SID, API_KEY, API_KEY_SECRET, PUSH_CREDENTIAL_SID, APP_SID`.

**Comment by bobiechen-twilio** [comment]
Hi everyone, please feel free to open new issues in case you run into any problem using the SDK. Closing this issue for now.

**Comment by ManukumarSB** [comment]
Facing same issue in iOS when using twilio_voice.
