### ISSUE TITLE
Couldn't receive voice call in background

### ISSUE THREAD

**Issue by LearnWithTung** [twilio/voice-quickstart-ios#425]
### Description

[Description of the issue]

My app works fine in foreground but couldn't receive voice call in background. I've tried to debug and here is the error description.

"killing app because it never posted an incoming call to the system after receiving a pushkit voip push callback"

The `callInviteReceived` never called in background

#### Voice iOS SDK

SDK 6.0.2

#### Xcode

XCode 12.3

#### iOS Version

iOS 14.2

#### iOS Device

iPhone 11

**Comment by weitsungchengkkday** [comment]
I got same issue 

Voice iOS SDK
SDK 6.0.2

Xcode
XCode 12.2

iOS Version
iOS 14.3

iOS Device
iPhone 12

**Comment by LearnWithTung** [comment]
I finally figure it out. 
The issue caused by i'm calling report in coming call in background.
Make sure that you're report in coming call in main thread

**Comment by ceaglest** [comment]
Hi @LearnWithTung,

I'm glad you were able to figure out a solution. Most of the voice experts weren't in the office, sorry that we did not respond sooner.

Best,
Chris
