### ISSUE TITLE
Couldn't receive voice call in background mode and  terminate 

### ISSUE THREAD

**Issue by weitsungchengkkday** [twilio/voice-quickstart-ios#426]
**Description**
My app works fine in foreground but couldn't receive voice call in background and  terminate. I've tried to debug and found

The callInviteReceived never called in background and terminate mode

I tried use demo app. That works fine. I tried to find what difference between demo APP and mine
Here is my Appdelegate 
`
```
import UIKit
import PushKit

protocol PushKitEventDelegate: AnyObject {
      func credentialsUpdated(credentials: PKPushCredentials) -> Void
      func credentialsInvalidated() -> Void
      func incomingPushReceived(payload: PKPushPayload, completion: @escaping () -> Void) -> Void
}

```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    weak var pushKitEventDelegate: PushKitEventDelegate?
    var voipRegistry = PKPushRegistry(queue: DispatchQueue.main)
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        // Initialize PushKit
        voipRegistry.delegate = self
        voipRegistry.desiredPushTypes = Set([PKPushType.voIP])
        
        return true
    }
    
    // MARK: UISceneSession Lifecycle
    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }
    
    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
    }
    
}

// MARK: PKPushRegistryDelegate
extension AppDelegate: PKPushRegistryDelegate {
    
    func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
        print("〽️ pushRegistry:didUpdatePushCredentials:forType:")
        
        if let delegate = self.pushKitEventDelegate {
            delegate.credentialsUpdated(credentials: pushCredentials)
        } else {
            print("〽️⚠️ pushKitEventDelegate is not set")
        }
        
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        print("〽️ pushRegistry:didInvalidatePushTokenForType:")
        
        if let delegate = self.pushKitEventDelegate {
            delegate.credentialsInvalidated()
        } else {
            print("〽️⚠️ pushKitEventDelegate is not set")
        }
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        print("〽️ pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:")
        
        if let delegate = self.pushKitEventDelegate {
            delegate.incomingPushReceived(payload: payload, completion: completion)
        } else {
            print("〽️⚠️ pushKitEventDelegate is not set")
        }
        
        completion()
    }
    
}`

and I set PushKitEventDelegate when TwilioServiceViewControlle is created
```
`
import UIKit
import SnapKit
import CallKit
import AVFoundation
import TwilioVoice
import PushKit

final class TwilioServiceViewController: UIViewController {
.....
        override func viewDidLoad() {
                       super.viewDidLoad()
                guard let delegate = UIApplication.shared.delegate as? AppDelegate else { return }
                      delegate.pushKitEventDelegate = self
                      delegate.initializePushKit()
                }
        }
.....
}
```

TwilioServiceViewController is not created in launch time, I am not sure it's the main reason?

**Environment**
Voice iOS SDK
SDK 6.0.2

Xcode
XCode 12.2

iOS Version
iOS 14.3

iOS Device
iPhone 12

**Comment by weitsungchengkkday** [comment]
Another different between my implement and demo APP is that I have used SceneDelegate.swift.

**Comment by weitsungchengkkday** [comment]
I found I use unnecessary weak here, but still not work
`weak var pushKitEventDelegate: PushKitEventDelegate?`

**Comment by bobiechen-twilio** [comment]
Hi @weitsungchengkkday 

Thanks for reaching out and I am sorry that I didn't get back to you sooner.
To ensure the app can handle the incoming VoIP notifications properly even when the the app is in the background or was terminated, the `PkPushRegistry` object must be initialized in the frontmost component of the app. You can check out the Swift quickstart [AppDelegate](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/AppDelegate.swift) and apply necessary updates to your app.

**Comment by weitsungchengkkday** [comment]
hi @bobiechen-twilio 

Thanks for your reply, PkPushRegistry object  in quickstart is 
`var voipRegistry = PKPushRegistry.init(queue: DispatchQueue.main)`

in my app is
` var voipRegistry = PKPushRegistry(queue: DispatchQueue.main)`

they are same .

So.... do you mean PushKitEventDelegate Object?

**Comment by bobiechen-twilio** [comment]
Hi @weitsungchengkkday 

Thanks for the update. The way your application initializes the `PkPushRegistry` instance is correct, just that you want to make sure it is created and kept in the component which will be created at launch time. That way the PkPushRegistry object is guaranteed to be alive and can handle the VoIP notification. This is especially crucial when the application was previously terminated and woken up by the system upon receiving a VoIP push.

The quickstart for example, we chose the AppDelegate as the component to host the `PkPushRegistry` object because we know the component will always be created at launch time. The `PushKitEventDelegate` is one of the ways to signal other app components with VoIP related events - your can follow the similar approach that suits your application as long as you properly handle the events under various app states.

**Comment by bobiechen-twilio** [comment]
Closing the issue since there hasn't been update for a while.
