### ISSUE TITLE
How to get voice & video call logs like missed calls etc

### ISSUE THREAD

**Issue by Naresh6885** [twilio/voice-quickstart-ios#428]
How can I get the missed call logs in iOS. I am using the following version:
'TwilioChatClient', '~> 4.0.0'
'TwilioVideo', '~> 3.7.2'

**Comment by bobiechen-twilio** [comment]
Hi @Naresh6885 

Thanks for reaching out.
I am assuming you are also using the TwilioVoice iOS SDK - there is no API to fetch missed call logs. You can either check the iOS system Call app if the incoming call push notifications were reported to CallKit or check out your [Call Logs console](https://www.twilio.com/console/voice/calls/logs).

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @Naresh6885 

Hope things are well. I am hoping that you have found the place to find the call logs you need.
I am closing the ticket for now but please feel free to reach out to us in the future.

Best,
-bobie
