### ISSUE TITLE
Failed to report incoming call to CallKit

### ISSUE THREAD

**Issue by meokullu** [twilio/voice-quickstart-ios#430]
### Description

App doesn't handle callInvite properly when it is in background or inactive state. On quickstart-ios, there is note says;

"The Voice SDK processes the call notification and returns call invite synchronously. Report the incoming call to CallKit and full the completion before  existing this callback method." and after that it does report incoming call in another functions.

### Steps to Reproduce

1. Register VoIPPush and Twilio in app.
2. Exit app, wait enough to app is terminated because it failed to report incoming call.

#### Code

```swift
func pushRegistry(... didReceiveIncomingPushWith)
{
incomingPushReceived(payload: payload, completion, completion)

getCallInfo { (callInfo: CallInfo) in
reportIncomingCall(from: callInfo.nameLastName, uuid: callInvite.uuid)
}

completion()
}
```

#### Expected Behavior

Receive Call Invite properly

#### Actual Behavior

iOS terminated App

#### Reproduces How Often

While the app is in background or inactive states, always.

#### Voice iOS SDK

Twilio 6.1.0

#### Xcode

12.3

#### iOS Version

14.0

#### iOS Device

iPhone 6s

**Comment by bobiechen-twilio** [comment]
Hi @meokullu 

Sorry that we couldn't get back to you sooner.
To sure that your application can handle incoming VoIP push notifications properly especially when the app was previously terminated, please make sure the `PkPushRegistry` object is initialized at launch time and kept in the frontmost app component. You can check out the AppDelegate implementation of the quickstart and apply necessary updates.

**Comment by bobiechen-twilio** [comment]
Hi @meokullu 

Hope everything is well. I am hoping that no news is good news and you have managed to resolve the issue.
Closing the ticket for now but please feel free to reach out to us any time.

Best,
-bobie
