### ISSUE TITLE
Why Callkit redirect user to the mobile app after accepting the call?

### ISSUE THREAD

**Issue by salman-pixarsart** [twilio/voice-quickstart-ios#431]
Description
I have a react-native application that uses a React-Native Plugin (react-native-twilio-programmable-voice) to handle Twilio communication.
Whenever a call comes in , User clicks on accept call button and call is get accepted but immediately at the same time user is routed back to the App while the call screen goes in the background but I want my app to stay on the Call Screen but no to move user to the mobile app.

![Call Screen IOS SS](https://user-images.githubusercontent.com/69501240/104909150-45c7d000-59a9-11eb-8500-0eb33073542f.jpg)

If User taps on the Topbar ( Red line as shown in the Attached image ) It  takes the user back to the app which shouldn't be happening

Steps to Reproduce
Launch the application on the iPhone with iOS 14.x and log in. Make sure Twilio is registered
Call the phone.
Accept the call.

Expected Behavior
That user should stay on the call screen of the call kit.

Actual Behavior
When user answers the call he/she routed to the mobile app after accepting the app.

Reproduces How Often
Always

Versions
Voice iOS SDK
5.5.1

Xcode
12.3.0

iOS Version
14.2.0

iOS Device
iPhone 7 Plus

**Comment by bobiechen-twilio** [comment]
There doesn't seem to be any CallKit API that allows application to config such behavior.
