### ISSUE TITLE
Cannot make outbound call from client to client

### ISSUE THREAD

**Issue by yabutaka** [twilio/voice-quickstart-ios#432]
### Description

I have installed the quickstart swift app on both my iPhone 7 and my iPad, and used different identities ("alice", and "ipad") to call from one device to another. However, I could not make any outbound call, and only received "Welcome to Twilio" message.

I have tried using both the Node.js server and the Python server. It turned out that the app was making a POST request to the root "/" instead of "/makeCall" every time I pressed the "Call" button on the app. I think the app should make a POST request to "/makeCall" but please correct me if I am wrong.

Note: I could replicate the quickstart tutorial until "Step 10. Receive an incoming call," so I believe that push notification and API Keys are set properly.

### Steps to Reproduce

1. Install Quickstart Swift version app on two iOS devices.
2. Start a Node.js server with credentials.
3. Set the identity of an app as "alice", which is default, and the other one as "ipad".
4. Open the app with "alice" and type "ipad" and press "Call."

#### Code

```swift
let accessTokenEndpoint = "/accessToken"
let identity = "ipad" // this could be alice on another device
let twimlParamTo = "to"
```

```swift
func performVoiceCall(uuid: UUID, client: String?, completionHandler: @escaping (Bool) -> Void) {
      guard let accessToken = fetchAccessToken() else {
          completionHandler(false)
          return
      }
      
      let connectOptions = ConnectOptions(accessToken: accessToken) { builder in
          builder.params = [twimlParamTo: self.outgoingValue.text ?? ""]
          builder.uuid = uuid
      }
      
      let call = TwilioVoiceSDK.connect(options: connectOptions, delegate: self)
      activeCall = call
      activeCalls[call.uuid!.uuidString] = call
      callKitCompletionCallback = completionHandler
  }
```
I am suspecting that this part of the code is making a POST request to "{server url}/" instead of "{server url}/makeCall"

```node.js
// This is called every time instead of /makeCall
app.post('/', function(request, response) {
  response.send(welcome());
});

app.post('/makeCall', function(request, response) {
  makeCall(request, response);
});
```

#### Expected Behavior

The device with the identity "ipad" receives an incoming call.

#### Actual Behavior

The device with the identity "ipad" does not receive any incoming call. Rather, the device with the identity "alice" receives the message that says "Welcome to Twilio".

#### Reproduces How Often

100% of the time.

#### Twilio Call SID(s)

Account SID: AC13a6c72c3c7173ca7c8586a3a5e29cf0

#### Logs

```
2021-01-24 17:25:59.541901+0900 SwiftVoiceQuickstart[3144:99707] StartCallAction transaction request successful
2021-01-24 17:25:59.556785+0900 SwiftVoiceQuickstart[3144:96157] provider:performStartCallAction:
2021-01-24 17:26:01.582600+0900 SwiftVoiceQuickstart[3144:96157] provider:didActivateAudioSession:
2021-01-24 17:26:02.976376+0900 SwiftVoiceQuickstart[3144:96157] callDidConnect:
2021-01-24 17:26:02.976566+0900 SwiftVoiceQuickstart[3144:96157] performVoiceCall() successful
2021-01-24 17:26:03.012683+0900 SwiftVoiceQuickstart[3144:96157] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2021-01-24 17:26:12.745419+0900 SwiftVoiceQuickstart[3144:96157] Call disconnected
2021-01-24 17:26:13.726699+0900 SwiftVoiceQuickstart[3144:96157] provider:didDeactivateAudioSession:
```

### Versions

TwilioVoice version: 6.1.0

#### Voice iOS SDK

11.0 via CocoaPods

#### Xcode

12.3

#### iOS Version

14.3

#### iOS Device

iPhone 7 and iPad Air 2

**Comment by bobiechen-twilio** [comment]
Hi @yabutaka 

Thanks for reaching out.
For your use case, `/makeCall` is the correct app endpoint. For this example endpoint, the `to` parameter will determine which TwiML verb will used in the response: https://github.com/twilio/voice-quickstart-server-python/blob/master/server.py#L98

In case you are still getting trouble connecting the caller and callee, you can provide us Twilio Call SIDs so we can check the details of the call.

**Comment by yabutaka** [comment]
Hi @bobiechen-twilio 

Thank you for your clarification. I have been looking into this issue a while now, and I have found that the iOS SDK tries to connect to "{server url}/" instead of "{server url}/makeCall" when I press the "Call" button. I actually changed the function inside the Node.js server as shown below.

```Node.js
// This is the original code. You will get "Welcome to Twilio" message.
app.post('/', function(request, response) {
  response.send(welcome());
});

// I changed the code to the makeCall funcriton as the following.
app.post('/', function(request, response) {
  makeCall(request, response);
});
```

When I changed the code to makeCall function, pressing the "Call" button did in fact enabled outbound call from the original phone to the target phone. So, based on this situation, I think the issue is that iOS SDK or sample code tries to connect to the root while it should have been sending a request to the "{server url}/makeCall" endpoint. Is there any way of changing the endpoint that the iOS sample code makes a request for? Could you tell me if there is anything I can do to change this behavior?

Successful Call ID: CAdc2cfc1be6a2023098022b519f50dc84

**Comment by bobiechen-twilio** [comment]
Thanks for the update @yabutaka.

The call routing logic is determined by the endpoint specified in the TwiML application.
From the mobile client standpoint, it will try to connect to a TwiML application - the endpoint URL that you specify in the voice incoming call handler of your Twilio number. This is the place where you specify which server endpoint, `/makeCall` or `/placeCall`, works best for your application logic. The application will then use the Application SID in the access token for making outbound calls.

I am closing the ticket for now since the original issue seems to be resolved, but please feel free to reach out.

Cheers,
-bobie
