### ISSUE TITLE
Only getting push notifications about 50% of the time, even when my device has strong network coverage

### ISSUE THREAD

**Issue by KodyKendall** [twilio/voice-quickstart-ios#434]
### Description

I implemented the voice-quickstart-ios guide, and everything was working well. I took it a step further and implemented a /connectCall URL on my server, and in the Twilio console, I connected one of my phone numbers to POST to the /connectCall URL. The /connectCall URL returns the following TWIML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial>
        <Client>alice</Client>
    </Dial>
</Response>
```

and it works! My iOS device successfully receives the call and I'm connected to the caller. The problem is that as I've continued to test it, my device only seems to get the push notifications about 50% of the time, and in the Twilio console, the status of the call is "Unanswered", even though the call never came into the iOS device. 

Here are what the call logs look like in the Call Logs page.

______________________________ **Calls that Didn't Connect:**
22:26:39 UTC 2021-01-28 | Outgoing Dial | +1801xxxxxxx | client:alice | Client | No Answer -- 
CA0ce4996cdf1e0387ff112db0a1f78f36

22:26:34 UTC 2021-01-28 | Incoming | +1801xxxxxxx | +1385xxxxxxx | Phone | Completed -- CA25fb60cfb026e6aba0a9d11d3e09088a

______________________________ **Calls that Did Connect**
00:14:45 UTC 2021-01-29 | Outgoing Dial | +1801xxxxxxx | client:alice | Client | Completed |   | — | 6 sec -- CA6b90f9d7c2594708a08059d6f2852e08

00:14:42 UTC 2021-01-29 | Incoming | 1801xxxxxxx | +1385xxxxxxx | Phone | Completed |   | — | 17 sec -- CAb80de1e0bb07855d4f6c9ee1de6eab95

### Steps to Reproduce

1. Implement Quickstart Guide for iOS and Server
2. Add New Route /connectCall on the Server that returns the following TWIML: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial>
        <Client>alice</Client>
    </Dial>
</Response>
```

3. Connect a Twilio Number to POST to the /connectCall
4. Call the phone number to be connected to the quickstart iOS app.

#### Code

```python
response = VoiceResponse()
dial = Dial()
dial.client('alice')
response.append(dial)

return(response)
```

#### Expected Behavior

A push connection should happen 100% of the time where I can accept the call on the iOS device and be connected to the caller.

#### Actual Behavior

A push notification only happens ~50% of the time where I can accept the call on the iOS device and be connected to the caller.

#### Reproduces How Often

~50%
#### Twilio Call SID(s)

Calls that didn't connect: 
CA0ce4996cdf1e0387ff112db0a1f78f36
CA25fb60cfb026e6aba0a9d11d3e09088a

Calls that did connect: 
CA6b90f9d7c2594708a08059d6f2852e08
CAb80de1e0bb07855d4f6c9ee1de6eab95

#### Voice iOS SDK

May need a little bit of help on this one.. Not quite sure how to tell what version of the SDK I'm using. 

This was in my podfile: 

pod 'TwilioVoice', '~> 6.1.0' 

#### Xcode

12.4 (12D4e)

#### iOS Version

iOS 14.3

#### iOS Device

iPhone 8 Plus

**Comment by bobiechen-twilio** [comment]
Hi @KodyKendall 

Thanks for reaching out and providing Call SIDs. I've checked them and the push notification requests were successful.
To ensure the application can handle incoming VoIP notifications, especially when the app is not active, the PkPushRegistry object must be initialized at app launch time. You can follow the [AppDelegate](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/AppDelegate.swift#L39) of the quickstart and apply updates that works for your app.

For more information please see https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md

**Comment by KodyKendall** [comment]
Ok, I will continue to test and look at those articles and see if there's some changes I can make with the app to more consistently ring the app. Can we keep this issue open while I explore more, then I will close it when I figure out a solution, or I can comment with an update/ask for more help?

**Comment by KodyKendall** [comment]
Here's another question, if the push notification requests were successful, why did my iOS device not ring or I did not see the push notification for the call that wasn't answered?

**Comment by bobiechen-twilio** [comment]
This is the behavior of the iOS VoIP notification - the notifications are delivered to the device successfully but for some reason the `PkPushRegistry` is not presented to handle the incoming push when the app was launched.

**Comment by KodyKendall** [comment]
Ok, is this a bug with the voice-quickstart-ios project, that the `PkPushRegistry` object is not initialized? Or is initializing the `PkPushRegistry` object something that we are expected to implement ourselves?

**Comment by bobiechen-twilio** [comment]
@KodyKendall 

The quickstart follows the PushKit guideline and implements the `PkPushRegistry` object in AppDelegate, which is guaranteed to be executed at launch time. Do you also experience problem getting the app to ring upon incoming call when using the vanilla quickstart with your account credentials?

**Comment by KodyKendall** [comment]
Yes, I am using the vanilla quickstart, and when I call, it seems like about 50% of the time I don't get the call ringing through, and I don't see the logs in the project that I would see when the call connects successfully. 

I don't see these logs: 

```
2021-01-29 11:26:13.343918-0700 SwiftVoiceQuickstart[5211:1461623] pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:
2021-01-29 11:26:13.438374-0700 SwiftVoiceQuickstart[5211:1461623] callInviteReceived:
2021-01-29 11:26:13.439962-0700 SwiftVoiceQuickstart[5211:1461623] Call invite received from verified caller number!
2021-01-29 11:26:13.514165-0700 SwiftVoiceQuickstart[5211:1461623] Incoming call successfully reported.
```

**Comment by KodyKendall** [comment]
Here are some more call SIDS of this happening

**Comment by bobiechen-twilio** [comment]
Is the app active, in the background or was terminated when you are having trouble getting the incoming call ringing?

**Comment by KodyKendall** [comment]
I just did a test call where I had the app active and open when I tried to call, and it didn't work. Call SID: CA0a228be348b6e83933f1793b071e3279

**Comment by KodyKendall** [comment]
<img width="497" alt="Screen Shot 2021-01-29 at 12 50 33 PM" src="https://user-images.githubusercontent.com/23284820/106320787-96082300-6230-11eb-8c55-cd5d16099005.png">

My phone was also no longer attached to the debugger in xCode.. is that necessary for the call to make it through?

**Comment by bobiechen-twilio** [comment]
Hi @KodyKendall Thanks for the call SID. Did you receive any PkPushRegistryDelegate callbacks at all?

**Comment by KodyKendall** [comment]
I'm not sure, I had unplugged my phone from my Macbook because I stepped away from my desk, and so I lost access to the iOS application logs. I just reconnected my phone, launched the application from xCode on my phone, and tried calling again, and the call didn't get connected, and I didn't get any `PkPushRegistry` notifications/logs at all. Here is the call SID after reconnecting to xCode: CA5afc92bce3ebc0116c1218c12f53b3f1

And here are the iOS voice-quickstart project logs for the whole session 

```
2021-01-29 12:52:09.242387-0700 SwiftVoiceQuickstart[5406:1496961] Twilio Voice Version: 6.1.0
2021-01-29 12:52:09.323302-0700 SwiftVoiceQuickstart[5406:1496961] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282c61c70 UILabel:0x108719130.centerX == UIView:0x1087193a0.centerX   (active)>",
    "<NSLayoutConstraint:0x282c61c20 H:|-(16)-[UILabel:0x108719130]   (active, names: '|':UIView:0x1087193a0 )>",
    "<NSLayoutConstraint:0x282c61bd0 UILabel:0x108719130.width == 0.514243*UIView:0x1087193a0.height   (active)>",
    "<NSLayoutConstraint:0x282c4b9d0 'UIView-Encapsulated-Layout-Height' UIView:0x1087193a0.height == 736   (active)>",
    "<NSLayoutConstraint:0x282c4b980 'UIView-Encapsulated-Layout-Width' UIView:0x1087193a0.width == 414   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x282c61c70 UILabel:0x108719130.centerX == UIView:0x1087193a0.centerX   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-01-29 12:52:09.330430-0700 SwiftVoiceQuickstart[5406:1496961] pushRegistry:didUpdatePushCredentials:forType:
2021-01-29 12:52:09.331860-0700 SwiftVoiceQuickstart[5406:1496961] providerDidBegin
```

**Comment by bobiechen-twilio** [comment]
The PushKit behavior should not be affected whether the phone is plugged in or not. You can also use the MacOS Console application to check if the notification is received by iOS (and delivered to the app) from the device log.

**Comment by KodyKendall** [comment]
It's been working more consistently now as I've been testing. I'm still a little concerned rolling this out to our users, because if they miss a single call it's a really big deal.. so I will continue to test and update this post as I learn more

**Comment by KodyKendall** [comment]
@bobiechen-twilio Is it possible the access tokens were expiring so the TVOCallInvite was being automatically rejected?

**Comment by bobiechen-twilio** [comment]
Hi @KodyKendall the expiry of the access token only affects the authentication when performing registration operations. Once registered, the mobile client will continue to receive VoIP push notifications unless the push binding has expired (no notification for a year), VoIP certificate has expired (1 year without renewal) or explicitly unregistered.

**Comment by bobiechen-twilio** [comment]
Hi @KodyKendall 

I am hoping that no updates means good news and now incoming call push notifications are working. Closing the ticket but please feel free to reach out to us.

Cheers,
bobie

**Comment by fattalgazi** [comment]
I have faced the same situation as well, everytime I removed the app and reinstalled it from XCode, and it started to work again. What I guess is, because we are testing the callkit a lot when we code, CallKit maybe blocks the incoming call automatically sometimes, because it thinks we abuse the CallKit. I don't remember where I read it but maybe this happens.
