### ISSUE TITLE
No audio when making call from android to iOS (call kit)

### ISSUE THREAD

**Issue by softsan** [twilio/voice-quickstart-ios#437]
### Description

When making a voip call from Android to iOS (which uses callkit), there is no audio on both side.

### Steps to Reproduce

1. User A Making a call from Android to user B
2.  User B is on iOS (with callkit), receive the incoming call and accept the ca
3. No Audio on both side (Android and iOS)

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

Audio should be audible when making a voip call from Android to iOS

#### Actual Behavior

No audio on both side when making a call from Android to iOS

#### Reproduces How Often

Every time

#### Twilio Call SID(s)

Caller's Call SID(Android): CA50fe0ec8d7627fe14daece8dc058c2ad
Receiver's Call SID (iOS) : CAa7b6a4be1ea5449212aaa7462e3297a3

#### Logs
[twilio_iOS.log](https://github.com/twilio/voice-quickstart-ios/files/5953826/twilio_iOS.log)
[twilio_android.log](https://github.com/twilio/voice-quickstart-ios/files/5953827/twilio_android.log)

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK
6.0.2
ANDROID: 5.6.2
#### Xcode

12.4

#### iOS Version

14.3/4

#### iOS Device

IPhone 6s, iPhone 11 pro max

**Comment by bobiechen-twilio** [comment]
Thanks @softsan for providing the logs. Although the iOS log doesn't seem to be complete but I did see that the local audio input and packets are all show 0. To help us diagnose the problem:
- Does this happen when the quickstart (no code change but only with your access token and credentials)?
- Can you enable `.trace` log level and provide us the full log from the beginning when the call is accepted?
```
  TwilioVoiceSDK.setLogLevel(.trace, module: .core)
  TwilioVoiceSDK.setLogLevel(.trace, module: .webRTC)
```

Also does this happen only when the iOS client is the call receiver? or does this happen when the call receiver is behind a special network environment?

**Comment by softsan** [comment]
Here is iOS logs with trace for core and webRTC module)
[twilio_iOS.log](https://github.com/twilio/voice-quickstart-ios/files/5961420/twilio_iOS.log)
.

I am using Xamarin and i ported code from quick start iOS swift to my Xamarin/c# project.

Now i also observed that it is happening for iOS to iOS call as well. So in all cases iOS is the receiver and then there are no audio.

**Comment by bobiechen-twilio** [comment]
Thanks @softsan. Could you check if the log you uploaded is the one with additional logging level and modules?
Please follow the quickstart and make sure
- UUID is provided in the `TVOAcceptOptionsBuilder`. This ensures that the audio device is configured to work with CallKit properly.
- The audio device is enabled (or disabled) at the right CallKit callbacks.

**Comment by bobiechen-twilio** [comment]
Hi @softsan 

Hope things are well and perhaps you managed to resolve the no-audio issue? Happy to help if the problem still persists in your environment.

**Comment by softsan** [comment]
@bobiechen-twilio Sorry for not responding. Actually i have another issue of Invalid APNs and thus not receiving incoming call/voip push so investigating on that so this one is currently on hold to check.

**Comment by bobiechen-twilio** [comment]
@softsan 

Does this happen to a specific device or devices using the same Push Credential SID?

**Comment by softsan** [comment]
@bobiechen-twilio  Actually we changed the CR by recreating certificates and also recreated Mobile push credentials but it still shows Invalid APNs for older one as well.

**Comment by bobiechen-twilio** [comment]
@softsan Do you have a Call SID when you got the delivery failure?

**Comment by softsan** [comment]
@bobiechen-twilio  CAe11a41d9d444ebfaeffa1365a702fd89

**Comment by bobiechen-twilio** [comment]
Thanks @softsan.

From the records there are 2 active bindings associated with the callee identity (`client:*******0213`), and they are both registered using an invalid format PushKit device token. I have deleted them and you should not be getting this error when calling this identity.

Let me know if this resolves the problem.

**Comment by softsan** [comment]
@bobiechen-twilio  Thanks a lot! Just make a call between _iOS (iphone 6s) to iOS(iPhone 11 Pro Max)_ and looks like that error is no longer showing up in twilio console. but i was not able to hear the audio. here is call sid: CA6290d4a62423f4ebc806dc73cb12de21
We already enabled voice trace so if you can find anything from that.

Also make another call from _iPhone 11 Pro Max_ to _iPhone 6s_ and audio is audible. but again get that Invalid APNs error. Here is a call SID: CA3958ec26c85234f9334321ffb5101c76
Just note that both device has iOS 14.4

**Comment by bobiechen-twilio** [comment]
Cool! I've removed the invalid bindings associated with the identity of CA3958ec26c85234f9334321ffb5101c76.
Please use PushKit device token with the correct format when calling the `TwilioVoiceSDK.register()` method in the future.

**Comment by softsan** [comment]
> @bobiechen-twilio Thanks a lot! Just make a call between _iOS (iphone 6s) to iOS(iPhone 11 Pro Max)_ and looks like that error is no longer showing up in twilio console. but i was not able to hear the audio. here is call sid: CA6290d4a62423f4ebc806dc73cb12de21
> We already enabled voice trace so if you can find anything from that.


Did you find anything for this? @bobiechen-twilio

**Comment by softsan** [comment]
@bobiechen-twilio  Just did couple of tests between two iOS device (iphone 6s  to iPhone 11 Pro Max and vice-a-versa), but there is no audio.

These are the call SID: 
CA7d5fbe1ac594d233bedd7ac3b1e63f43
CA46966aa6aee3f43234b9457d6aa9380c

**Comment by bobiechen-twilio** [comment]
Thanks for the update @softsan.

Please enable `.trace` level SDK log and also `.trace` level for the `.webrtc` log module. We need to check the SDK log and see if any error happened while establishing the media connection.

Does the no-audio issue happen on the same device (with the same network environment) when running on the quickstart?

**Comment by softsan** [comment]
@bobiechen-twilio  here is a log file for iOS
[twilio_iOS.log](https://github.com/twilio/voice-quickstart-ios/files/6012627/twilio_iOS.log)

**Comment by bobiechen-twilio** [comment]
Thanks @softsan. While we are investigating the logs for clues, can you confirm a few things:
- Based on your description, does this only happen on a specific device?
- Is there any custom AVAudioSession configuration in your app that could be different from the default setup of the SDK/quuickstart?

**Comment by softsan** [comment]
I am testing with iphone 6s and iPhone 11 pro max as i have those two devices.

There are no special audio setup in the app.

**Comment by softsan** [comment]
@bobiechen-twilio further updates: I figure out why there was an audio issue, on answering call there were some missing piece of audio initialisation, so i guess that was the issue. Thank you much for your help so far.

**Comment by bobiechen-twilio** [comment]
@softsan Thanks for the update and glad that the issue is resolved. 👍

**Comment by bmarrelli05** [comment]
@softsan i am having a similar issue where an incoming call comes in, there is no audio. I am also using Xamarin Twilio Voice iOS SDK 6.0.2. Making outgoing calls works great but for some reason incoming calls have no audio. What type of audio initialization worked for you to resolve your issue?

**Comment by softsan** [comment]
For those who are facing this issue, here is how i solved it.
In my `ProviderDelegate.cs`
```
public override void DidReset(CXProvider provider)
{
    this.audioDevice.Enabled = false; // This is my TVODefaultAudioDevice object 
}

public override void DidActivateAudioSession(CXProvider provider, AVFoundation.AVAudioSession audioSession)
{
    this.audioDevice.Enabled = true;
}

public override void DidDeactivateAudioSession(CXProvider provider, AVFoundation.AVAudioSession audioSession)
{
     if (isOnHold || isEnded)
     {
         this.audioDevice.Enabled = false;
     }
}
```
