### ISSUE TITLE
iOS cannot use FCM credential type

### ISSUE THREAD

**Issue by izio38** [twilio/voice-quickstart-ios#439]
Related : https://github.com/twilio/voice-quickstart-objc/issues/109

### Description
I fall into the same conclusion, we cannot use fcm credential type for voip push notification even if we've added APN certificates into the FCM application.
First of all, is that correct ? Then, is this possible to make such a thing (that would simplify a lot the registration / make call process). Actually we're creating a Flutter application and we are creating a twilio programmable voice package and want to not make a huge difference between iOS and Android. And with things as it, it's a huge mission.

### Steps to Reproduce

1. Create an FCM Credential type
2. Register with a generated accessToken that has this properties : 
```json
{
  "jti": "SKxxxxxx",
  "grants": {
    "identity": "testId",
    "voice": {
      "incoming": {
        "allow": true
      },
      "outgoing": {
        "application_sid": "APxxxxx"
      },
      "push_credential_sid": "CRxxxxx"
    }
  },
  "iat": 1613644068,
  "exp": 1613647668,
  "iss": "SKxxxxxx",
  "sub": "ACxxxxxxx"
}
```
3. Try to make a dialing out call to the `testId` client
4. See the error in the Twilio debugger : 
![image](https://user-images.githubusercontent.com/9900846/108347505-e267d280-71e0-11eb-8cbd-098336ab4516.png)

### Versions
Latests

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @izio38.

We do have research tasks to expand our call notification delivery alternatives, but currently the Programmable Voice iOS SDK only supports Apple's VoIP Service certificate for incoming call push notifications. To provide the best and seamless VoIP experience on iOS, especially when the app is not active or not running, it's highly recommended to integrate CallKit and PushKit for incoming calls.

**Comment by hawkinbj** [comment]
@maningyt we don't have any committed plans to implement right now, though we have added it to the list for official consideration for 2023 roadmap. We've [recently released a React Native Voice SDK](https://github.com/twilio/twilio-voice-react-native), and this request is something worth considering as we see more and more developers look to share common code between platforms
