### ISSUE TITLE
Framework not found Pods_TwilioVoice_SwiftVoiceQuickstart

### ISSUE THREAD

**Issue by KodyKendall** [twilio/voice-quickstart-ios#445]
When trying to build the swift voice quickstart project, it doesn't build and I get the error: Framework not found Pods_TwilioVoice_SwiftVoiceQuickstart

**Comment by bobiechen-twilio** [comment]
Thanks for reporting this @KodyKendall.
I do see a remaining `Pods` folder in the latest Swift quickstart project, which was missed when we migrated the quickstart from Cocoapods to using Swift Package Manager to integrate the Voice SDK. You can update to the latest version of the quickstart or update your Cocoapods dependencies (`pod install` or `pod update`) so your project can build properly.

**Comment by bobiechen-twilio** [comment]
@KodyKendall 

I am hoping that no news is good news and you have managed to resolve the build error. Feel free to reach out any time if you need assistance.

Cheers,
-bobie
