### ISSUE TITLE
POST request to another server from the Twiml function

### ISSUE THREAD

**Issue by saqibdb** [twilio/voice-quickstart-ios#450]
### Description

I followed the guide project, made all the functions (in default node.js). Made all the flow in the mobile app end.
All is working perfect.
I made the logic in a way so that if a call comes of twilio purchased number then the call is to be redirected to twilio logged in user, using the app. This is working as well.
Problem is I need to map the specific phone number in which the call is coming to, to a specific user that is currently logged in.
Currently I am doing this by giving static values but by idea was to make a call to my own other database server through a simple POST request and get the proper user from their.
Issue is while make the POST request through twiml function in the node.js.
I dont get any error(with proper request), but i dont get response as well. 
I tried debugging with logs as well, and looks like call is not even entering the part where response should come.
If i make some deliberate error in call to see if the response part is ever hit, then it does gets called but obviously with error (which is good), but on proper request, its not being called for even any error(if any)
My assumption is might be request is interfering with twiml callback or maybe twiml server wont allow request to another server etc but i am not sure

### Steps to Reproduce

1. my-app-twilio-url/make-call with the twilio purchased number

#### Code

```node.js
 var request = require('request');
    var options = {
      'method': 'POST',
      'url': 'https://someurl.com/api/endpoint',
      'headers': {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({"phone":"+123456789"})

    };
    request(options, function (error, response) {
      console.log('HERE IT IS '+ error + response.body);
    });
```
#### Code with static values
```node.js
if (event['To'].toString() == "+123456789") {
      callTo = 'John Does'
      const dial = twiml.dial({callerId : callerIdentification, answerOnBridge : true, timeLimit : 180});
      dial.client(callTo);
 }
else if (event['To'].toString() == "+987654321") {
      callTo = 'Jane Doesnot'
      const dial = twiml.dial({callerId : callerIdentification, answerOnBridge : true, timeLimit : 180});
      dial.client(callTo);
}
```
#### Expected Behavior

Post request ,response callback code to be hit, so i can get the proper user that is mapped against this phone number from my server and then route call to that.

#### Actual Behavior

Post request ,response callback code never gets called.

#### Reproduces How Often

Everytime

#### Twilio Call SID(s)

Here is the function sid = ZH8f2f3dafe8eba7a72b043cdaf72f4a55
version sid = ZNb81202e89758f0f11afdbf157c4a77e5
request sid = RQd80512fd2e6180c5340d7a0a38f10c0b
call sid = CA4694826f3c1d51749d8eb59eba55fb42

#### Logs

```
No logs
```

### Versions

twilio-cli version 2.18.0

#### Voice iOS SDK

I am not sure if that is relevant but still version = 6.2.0

#### Xcode

I am not sure if that is relevant but still version = 12.4

#### iOS Version

I am not sure if that is relevant but still version = 14.4

#### iOS Device

I am not sure if that is relevant but still device = 6s, 11 pro, 12 pro, even simulator

**Comment by bobiechen-twilio** [comment]
Hi @saqibdb 

Thanks for reaching out and glad that you were able to make most of the onboarding experience working!
If I am understanding this correctly, you are trying to make an additional request to your own server endpoint, which retrieves number-identity mapping information from the DB), when your TwiML app endpoint is hit when your Twilio number is called?

Does your server endpoint return a TwiML response (i.e., the <Client> verb) within a proper time frame, or did it keep waiting for the subsequent request and never generated the response and called the mobile client?

**Comment by saqibdb** [comment]
@bobiechen-twilio Ohhh yeah, that is surely it. Basically logic was to hit my server first then get a response, extract user information from that response and then make the dial, but for testing purposes, i was making async dial, meaning dial was done without waiting for the response.
Again. Thank you very much for the help

```node.js
 var request = require('request');
    var options = {
      'method': 'POST',
      'url': 'https://someurl.com/api/endpoint',
      'headers': {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({"phone":"+123456789"})

    };
    request(options, function (error, response) {
      console.log('HERE IT IS '+ error + response.body);
    });
```
and then next to it
```node.js
 if (event['To'].toString() == "+............") {
        callTo = '..........'
        const dial = twiml.dial({callerId : callerIdentification, answerOnBridge : true, timeLimit : 600});
        dial.client(callTo);
 }
```

BTW, just out of curiosity, would i be able to make calls to multiple clients at same time and however picks up the call first will get the call routed to them, is this possible with the system

**Comment by bobiechen-twilio** [comment]
The Programmable Voice service and SDK allow developers to register multiple clients with the same identity at the same and all of them will receive incoming call notifications when there is a call made to this identity. As soon as one of them took action upon the call (accepted or rejected the call), the rest of the clients will also be notified that the local call invite has been canceled.
