### ISSUE TITLE
Calls to a specific region's local numbers are always failing

### ISSUE THREAD

**Issue by saqibdb** [twilio/voice-quickstart-ios#452]
### Description

I made an app through which i can make calls to local phone numbers. Calls are working but when i try to call local phone numbers in Armenia, the calls are failing.
For other countries (that i tested, like USA, Australia, Pakistan etc) they are working perfectly.
They also use to work like 1 week ago, but suddenly they just stop working.
Its like call is not getting connected to the phone number.

I also thought maybe this issue was related to 1 specific number so i tried 3 different phone numbers but all failed

### Steps to Reproduce

1. Dial any Armenia based local phone number

#### Code

```swift
const dial = twiml.dial({callerId : comingFrom, answerOnBridge : true});
dial.number(to);
```

#### Expected Behavior

Call should get connected to local phone number

#### Actual Behavior

Calls are failing.

#### Reproduces How Often

Everytime on Armenia based phone numbers

#### Twilio Call SID(s)

CA52d73317267509f82d90c3d7f94322ab
CAea36af4781ff3efe91248000c8a2294b
CA81743c8f075bc6341474722d0b3ee509

#### Logs

```

Outgoing Dial | +1............. | +37......... | Phone | Failed
-- | -- | -- | -- | --
```

### Versions

twilio-cli version 2.18.0

#### Voice iOS SDK

6.2.0

#### Xcode

12.4

#### iOS Version

14.4

#### iOS Device

6s, 11 pro, 12 pro

**Comment by bobiechen-twilio** [comment]
Hi @saqibdb 

Please check the [Geo Permissions settings](https://support.twilio.com/hc/en-us/articles/223180228-International-Voice-Dialing-Geographic-Permissions-Geo-Permissions-and-How-They-Work) of your Twilio account and enable specific regions.

**Comment by saqibdb** [comment]
@bobiechen-twilio Yes that was the issue.
Thanks for your help, my mistake, i missed that.
