### ISSUE TITLE
We're sorry, an application error occurred

### ISSUE THREAD

**Issue by ITASerus** [twilio/voice-quickstart-ios#453]
Hi!
I need to create an app that lets the user to call some tel numbers.

I think that twilio should be the right service and found this quickstart project...
I implemented it but when I call any number (the one in my free account or others) a voice tells me that an error occurred...
What should be the problem?

In the twilio console i fount this in the error page:
"An attempt to retrieve content from https://my-quickstart-dev.twil.io/make-call returned the HTTP status code 404"

**Comment by bobiechen-twilio** [comment]
Hi @ITASerus 

Thanks for reaching out. Please make sure the TwiML URL specified in the Application SID is a valid one and returns a valid TwiML response.

**Comment by BlakeBoxberger** [comment]
I am also facing this issue while following the tutorial. The HTTP response is 404 and the error code is 11200.

**Comment by bobiechen-twilio** [comment]
Hi @BlakeBoxberger - could you please check the Twilio developer console and provide more detail about the error? Most likely the TwiML app URL of the Voice incoming handler is not valid and Twilio is not able to fetch the TwiML response. Please make sure you are using a working URL of your Serverless component.

**Comment by BlakeBoxberger** [comment]
@bobiechen-twilio,

Of course, here are the details about the error:

![image](https://user-images.githubusercontent.com/18316681/117050143-dfea2480-acc9-11eb-849d-a3f4f1de0803.png)

I suspect the issue could be that the "to:" field is not set, rather the "To:" field.

**Comment by bobiechen-twilio** [comment]
Hi @BlakeBoxberger @ITASerus 

Sorry we couldn't get back to you sooner. The error message from the Twilio console indicates that the service wasn't able to fetch the TwiML response from your application endpoint and resulted in a 404 error. Please make sure the URL you specify for the TwiML App is valid and publicly accessible. You can view and configure the TwiML apps in the developer's console: https://www.twilio.com/console/voice/twiml/apps.

Please note that the URL in the README is only for instruction purpose. You should receive a different URL from the Twilio CLI command based on your unique project name.
