### ISSUE TITLE
Extending the wait time for incoming call to answer

### ISSUE THREAD

**Issue by yuxx** [twilio/voice-quickstart-ios#455]
Hi.
I'm using TwilioVoice SDK for iOS.
And I have a question.
Can I extend the wait time for incoming call to answer?
I want to extend the wait time to 60 seconds, but shutting down after 40 seconds later.

In our application, start calling from the server like below.
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play>https://some.domain/path/to/anaunce.mp3</Play>
    <Dial callerId="some-call-id" timeLimit="14400" timeout="60">
        <Number statusCallbackEvent="initiated ringing answered completed" statusCallback="https://some.domain/path/to/callback/some_id">+815000000000</Number>
    </Dial>
</Response>
```
When I create call, adding optional value `timeout="60"`, but no effect.

I can't find configuration about this in TwilioVoice for iOS.
Please any help.

**Comment by bobiechen-twilio** [comment]
Hi @yuxx 

Thanks for reaching out.
This is indeed a known issue of the Voice SDK where the longest timeout value of the incoming call invite is always 40 seconds. I have created an internal ticket for tracking this issue and will update you as soon as there is a fix.

**Comment by yuxx** [comment]
Hi @bobiechen-twilio

Thank you for responding.
I understand this problem and waiting for a fix.

**Comment by bobiechen-twilio** [comment]
@yuxx please check out the [6.3.1 release](https://www.twilio.com/docs/voice/sdks/ios/changelog#631) where we extended the max timeout to 10 minutes by default.
Closing issue.

**Comment by yuxx** [comment]
@bobiechen-twilio 
Oh, thank you! I will test the new SDK.
