### ISSUE TITLE
On voice call receive, make multiple redirect voice calls

### ISSUE THREAD

**Issue by Umer-naseer** [twilio/voice-quickstart-ios#457]
### Description

Basically i made the system in which when a call is received on a twilio purchased phone number, the twiml bin function gets called, where i put some logic in. All is working perfect.
Now i need to put a scenario, in which when the call comes in on twilio number, the call is to be redirected to multiple phone numbers at same time, and whoever picks the call first will get the voice call
For 1 redirect, the system is working.

### Steps to Reproduce

1. Receive call on twilio purchased number
2. Call is to be redirected to multiple local numbers
3. Currently only 1 number is getting called

#### Code

```jquery
const dial = twiml.dial({callerId : comingFrom, answerOnBridge : true, record : 'record-from-ringing'});
dial.number(to_1);

const dial2 = twiml.dial({callerId : comingFrom, answerOnBridge : true, record : 'record-from-ringing'});
dial2.number(to_2);

const dial3 = twiml.dial({callerId : comingFrom, answerOnBridge : true, record : 'record-from-ringing'});
dial3.number(to_3);
```

#### Expected Behavior

Calls redirect to multiple phone numbers

#### Actual Behavior

Only 1 redirection to 1 phone number is made

#### Reproduces How Often

Always

**Comment by bobiechen-twilio** [comment]
Hi @Umer-naseer 

Thanks for reaching out.
As far as I understand, TwiML execution is sequential - your TwiML bin for example, the second <Dial> won't start until the first one is finished. You may want to reach out to the Twilio Support so our Voice service experts can help and fulfill your application requirement since this is out of our area of expertise.

**Comment by Umer-naseer** [comment]
@bobiechen-twilio Thanks for the quick response.
I have tested myself with different codes and settings
So for any future user, who is looking for something similar, here is the code that works:

`
const dial = twiml.dial({callerId : comingFrom, answerOnBridge : true, record : 'record-from-ringing'});
dial.number(to_1);
dial.number(to_2);
dial.number(to_3);
`
