### ISSUE TITLE
Ability to receive incomings calls via custom APNS notification setup

### ISSUE THREAD

**Issue by abhinavsingh** [twilio/voice-quickstart-ios#460]
### Description

Currently, `Twilio` recommends setting up an APNS key in console to receive calls on the device.  In our case, we already have an APNS system setup and would like to re-use the same for receiving calls.  Consider this:

1. Twilio notifies our server endpoint about an incoming call
2. Our server dispatches APNS
3. Client handles APNS and shows notification to the user
4. User clicks on notification to initialize `CallInvite` and accept the call

However, doc says

```
/**
 * The `TVOCallInvite` object represents an incoming Call Invite. `TVOCallInvite`s are not created directly;
 * they are returned by the `<[TVONotificationDelegate callInviteReceived:]>` delegate method.
 */
```

I am wondering if this feature is currently supported or do we have to necessarily setup APNS token to receive calls directly on the device.

Thank you

**Comment by bobiechen-twilio** [comment]
Hi @abhinavsingh 

Thanks for reaching out.
The Voice iOS SDK currently only supports the Apple VoIP Service and will require a Push Credential with the certificate and key so that the Twilio can send push notification requests to Apple on the app developer's behalf.
