### ISSUE TITLE
How to get the secret after twilio login

### ISSUE THREAD

**Issue by rahulserver** [twilio/voice-quickstart-ios#462]
When i do `twilio login`, heres the output

```
 ›   Warning: twilio-cli update available from 2.24.0 to 2.25.0.
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Account or Subaccount, and then forgotten.
? The Account SID for your Twilio Account or Subaccount: ACa**97 (redacted by @bobiechen-twilio)
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]
? Shorthand identifier for your profile: rahulserver
Created API Key ** (redacted by @bobiechen-twilio) and stored the secret in your keychain. See: https://www.twilio.com/console/runtime/api-keys/SK**fe (redacted by @bobiechen-twilio)
twilio-cli configuration saved to "/Users/rahulserver/.twilio-cli/config.json"
Saved rahulserver.

```

And when I goto link `https://www.twilio.com/console/runtime/api-keys/SK**fe` (redacted by @bobiechen-twilio) I don't see any secret: 
** image removed by @bobiechen-twilio 

Due to this I am not able to run the quickstart.

**Comment by bobiechen-twilio** [comment]
Hi @rahulserver 

I updated your original comment and removed the credentials. Please note it's not safe to share any account credentials in the public.

The secret of the API key will only be shown ONCE when the key is created. It is the developer's responsibility to safely save the secret. You can create a new API key, save the secret, and delete the old key.
