### ISSUE TITLE
How to receive call in IOS Kiosk mode

### ISSUE THREAD

**Issue by SaugataBhandari** [twilio/voice-quickstart-ios#463]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description
My ios application receive incoming call when it is not in kiosk mode. If it is in kiosk it is getting incoming call but user can not able to receive or reject the call.
[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Twilio Call SID(s)

You can find the Call SID in the SDK from TVOCall.sid or TVOCallInvite.callSid. The Call SID can also be found on the Twilio Calls Console: https://www.twilio.com/console/voice/calls/logs.

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bobiechen-twilio** [comment]
Hi @SaugataBhandari 

Thanks for reaching out. I have tried running the app in the Guided Access mode and while I was able to receive the incoming call notification, the system call pop-up did not give me the answer/reject button after I reported the VoIP push to CallKit. This makes me think it's a system restriction for devices running the kiosk mode.

<img width="400" src="https://user-images.githubusercontent.com/16326574/125361913-e082e500-e322-11eb-829f-1196ed061b7f.jpeg">
