### ISSUE TITLE
Maximum number of calls to same client at same time

### ISSUE THREAD

**Issue by saqibdb** [twilio/voice-quickstart-ios#466]
### Description

I made an app in which when a call comes in to a twilio number, the call is redirected to twilio client (user) which is in my system is mapped to my system's user.
Now the app can login the same user on multiple devices (e.g user is concurrently logged in the iphone and ipad). I am only talking about the iOS side. 
When an incoming call comes in, i made the code in the twilio cloud function and through my own custom logic, the number is decoded to get the corresponding user in our system, and then call is redirected to twilio_client (which is mapped against the number).
I have tested with 2 devices at same time, and both iphones were getting calls at same time (which is good).
My question is if there is a limit to that, e.g only 10 devices will get calls for same twilio_client, and should i even be doing this, or make a system in which only 1 login is done at 1 time etc
I basically want to know this limitation, if it even exists or not. I tried searching the documentation but i couldn't find this specific limit.

### Steps to Reproduce

1. name a user client:test_user
2. get access token on multiple devices at same time
3. make an outgoing call to client:test_user
4. all devices (i tested with 2) are getting calls at same time
5. whoever picks up first will get the call routed

#### Expected Behavior

I just want to know if there is any limit of concurrent calls to multiple devices at same time to same user

#### Actual Behavior

I cannot test with alot of iphones, so thats why asking if there is limitation

### Versions

twilio-cli version 2.18.0

#### Voice iOS SDK

6.2.0

#### Xcode

12.4

#### iOS Version

14.4, 14.6

#### iOS Device

6s, 11 pro, 12 pro

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @saqibdb and kudos to the nice and clear issue description 👍.
AFAIK there is no such flag to configure the number of clients, with the same identity under the Account SID, to receive the incoming call notification at the same time.

For what it's worth, there is a hard limit of the Voice service by which only the last 40 devices registered with the same identity will receive the incoming call push notification, in case you have more than this number of clients with the same identity at the same time.

**Comment by saqibdb** [comment]
@bobiechen-twilio Thats perfect, so 40 is the number on which i put a limit on my system as well
Thanks for the quick response
