### ISSUE TITLE
twilio serverless:deploy - Cannot read property 'next_page_url' of undefined

### ISSUE THREAD

**Issue by caksabre** [twilio/voice-quickstart-ios#469]
### Description

Hi,

When running twilio serverless:deploy
I get
Service Name	quickstart
Environment	dev
Root Directory	/Users/chrisevans/code/voice-quickstart-ios/Server
Dependencies	
Env Variables	API_KEY_SID, API_SECRET, APP_SID, PUSH_CREDENTIAL_SID
Runtime		undefined

✖ Failed Deployment

│ ERROR 
│ 
│ Cannot read property 'next_page_url' of undefined

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Twilio Call SID(s)

You can find the Call SID in the SDK from TVOCall.sid or TVOCallInvite.callSid. The Call SID can also be found on the Twilio Calls Console: https://www.twilio.com/console/voice/calls/logs.

#### Logs

```
// Log output when the issue occurs
```

**Comment by bobiechen-twilio** [comment]
Hi @caksabre 

Thanks for reporting the issue. I would love to help you out but unfortunately I am not the expert of the Twilio CLI tool. Perhaps you want to reach out to the [Twilio CLI repository](https://github.com/twilio/twilio-cli) and hopefully our CLI champions can provide better help.

Sorry for the inconvenience when deploying the sample server.

-bobie

**Comment by bobiechen-twilio** [comment]
Closing ticket for now. @caksabre please feel free to reach out if you still need help deploying the sample server.
