### ISSUE TITLE
AnswerOnBridge doesn't work

### ISSUE THREAD

**Issue by d3nzZ3L** [twilio/voice-quickstart-ios#471]
Documentation says that if we providing answerOnBridge parameter to Dial callDidConnect callback in client will fire only when incoming call will be answered but callDidConect firing immediately after we call .connect() method in TwilioVoiceSDK on client side

How can i track when user answer call or not. I need to implement missed call feature in app

Here's how i pass answerOnBridge in twilio functions:
`const dial = twiml.dial({
      answerOnBridge: true
    });
`

Thank you.

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @d3nzZ3L.
Do you have a Twilio Call SID? We can take a look and check if the flag is correctly applied in the TwiML response.

**Comment by bobiechen-twilio** [comment]
Closing ticket since there has not been response for a while. @d3nzZ3L please feel free to reach out with Call SIDs if the problem persists.
Thanks!
