### ISSUE TITLE
Calling from verified caller ID not work

### ISSUE THREAD

**Issue by trmquang93** [twilio/voice-quickstart-ios#472]
### Description

When I made call from number that is in verified caller ids. the destination number was not ringing. When I call from bought number, it worked normally

### Steps to Reproduce

1. Add 2 numbers to verified caller id
2. Call from 1 number to other

#### Expected Behavior

the second number was expected to ring

#### Actual Behavior

the second number did not ring

#### Reproduces How Often

always

#### Twilio Call SID(s)

CAf1bd199060142ff1b56927a660eefa75
CA268de2f6f1cdacd7000e6454d2c8413f

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

6.3.0

#### Xcode

12.5.1

#### iOS Version

14.6

#### iOS Device

iPhoneX

**Comment by bobiechen-twilio** [comment]
Hi @trmquang93 thanks for reaching out and providing the Call SIDs.

From the Call SID I can see that the calls made from the SDK were connected successfully to the Twilio Voice service and the child calls were made to the number specified in the TwiML response. No errors were recorded for the subsequent calls to the number. I have a feeling there could be some issue when Twilio Voice tried to connect your calls with the carrier but unfortunately this is out of the expertise of the SDK. Could you please file a [Twilio Support](https://support.twilio.com/hc/en-us) ticket with the Call SIDs so our carrier experts can help you out.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @trmquang93 

Curious if you received any help from Twilio Support already?

-bobie

**Comment by trmquang93** [comment]
Hello, thank you very much for helping. I received help from Twillio support and problem was resolved. They said my country is not supported for this function of twillio
