### ISSUE TITLE
Unable to open app when phone call is received from locked state.

### ISSUE THREAD

**Issue by vaibhavtech1302** [twilio/voice-quickstart-ios#473]
I wan't to run some service sdk and functionality from app when user receive call but that need to run when app is opened so I wan't to open app in case of user received call in terminated and locked state as well. Please let me know how I can open app when user receive call in locked state.

This is for iOS application and version 13.0 or greater

Thanks

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

The quickstart sample app should be able to let you receive incoming call when the app is in the background or when the device is locked. Once the call is answered, in the system call app you should see a button letting you go to your app (passcode/Touch ID/Face ID will be needed if the device was locked).

Cheers,
-bobie
