### ISSUE TITLE
When I cancel call some time in background call is running but the call is cancel is there any way to forcefully remove background call is active if

### ISSUE THREAD

**Issue by vaibhavtech1302** [twilio/voice-quickstart-ios#474]
When I cancel call some time in background call is still active as I can see red strip in top but the call is cancel is there any way to forcefully remove background call is active. 

Twilio iOS 13.0

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

- Is this an outgoing call or incoming call?
- What is the Voice SDK API you use to "cancel" the call?
- Did you see any error message in the debugging log?

**Comment by vaibhavtech1302** [comment]
Hi @bobiechen-twilio 

Is this an outgoing call or incoming call?
Answer:- This is for outgoing call only, And it's occur randomly when I cancel the call before directed to ringing state.

What is the Voice SDK API you use to "cancel" the call?
Answer :- I am using sdk 5.0 or after
I tried two code for it but non of them worked. It generally occur randomly some times when we click cancel button before moving to ringing state.
  1.      if let provider = callKitProvider {
           provider.reportCall(with: UUID(), endedAt: Date(), reason: CXCallEndedReason.failed)
       }
       
      2.           performEndCallAction(uuid: UUID())


Did you see any error message in the debugging log?
Answer:- I was unable to debug till now because it's occurring randomly some time.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @vaibhavtech1302.
Feels like something went wrong when calling `performEndCallAction(uuid: UUID)` and the debug message should be able to give us more clue. Most likely some error occurred, for example CallKit cannot find the UUID of the call that the app is trying to end, when the app tried to submit the end-call action to CallKit.

**Comment by vaibhavtech1302** [comment]
Hi @bobiechen-twilio ,

Error which I am facing when trying to cancel the call is 

EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)

And this occurs when I get status StartCallAction transaction request successful but it's not moved to ringing state.

Please let me know how I can counter this issue.

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

The CallKit request error 4 typically means the UUID used for the transaction is invalid, either the UUID was never reported to CallKit, or the call associated with the UUID has been ended. Please check your application and make sure the UUID you use for CallKit requests is valid.

**Comment by bobiechen-twilio** [comment]
Closing: inactive for a week. @vaibhavtech1302 please feel free to reach out if you believe this is a bug. You can reference the CallKit example in the quickstart and implement call logic in your application.
