### ISSUE TITLE
I wan't to direct to my app when user receives call in terminate and locked state because I need to run some sdk and service.

### ISSUE THREAD

**Issue by vaibhavtech1302** [twilio/voice-quickstart-ios#476]
I wan't to direct to my app when user receives incoming call in terminate and phone locked state because I need to run some sdk and service when user is in call and it should redirected in locked state only when I receive call. Could you please help me how I can achieve that.

I am using iOS 13, iPhone XR

Thanks

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302,

Please follow the quickstart sample app, which is able to receive and display the incoming call when the app is in the background, terminated or when the device is locked.
