### ISSUE TITLE
Unhold button is cancelling the call instead of unhold

### ISSUE THREAD

**Issue by vaibhavtech1302** [twilio/voice-quickstart-ios#477]
When I am trying unhold the call then call is getting cancelled instead of unholding the call scenario is like when I am call with other person from app then call get hold and when I try to unhold call from app then call get cancelled instead of unholding the call .

My code is for unhold:-
call.isOnHold = false

iOS 13.0

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

Could you please provide `.trace` level SDK logs and the Twilio Call SID when this happens?

**Comment by bobiechen-twilio** [comment]
Closing ticket since there has not been any activity for a while. Please feel free to reach out to us with debugging information if you believe this is still an issue.
