### ISSUE TITLE
Install a tap on AudioEngine input node

### ISSUE THREAD

**Issue by abhinavsingh** [twilio/voice-quickstart-ios#483]
### Description

We are looking into how to grab raw input audio during a call.  I looked into `ExampleAVAudioEngineDevice` example, but it looks too much for our needs.  We don't intend to mix or even record at this stage.  We need audio stream for speech recognition workflows.

Ideally, we want to just install a Tap on the input node (over a bus).  This seemingly can be achieved using a few lines of code:

```
private var inputNode: AVAudioInputNode!
inputNode = audioEngine.inputNode
let outputFormat = inputNode.outputFormat(forBus: 0)
inputNode.installTap(onBus: 0, bufferSize: 1024, format: outputFormat) { (buffer, _) in
    // Use buffer here
}
```

However, I am unable to wrap my head around getting access to the `inputNode` without a custom `AudioDevice`.

PS: I am quite new to entire iOS/Swift development.

Thank you!!!

**Comment by DeepanshCUHK** [comment]
Were you able to get this working?
