### ISSUE TITLE
Twilio call temporary blocking

### ISSUE THREAD

**Issue by vaibhavpandey130240** [twilio/voice-quickstart-ios#486]
Hi @bobiechen-twilio

We tried this demo of VoIP calling in iOS in the following ways and checked the results:
Using static token generated for device-specific identity.
Device A: application in one client device.
Device B: application in another client device

Scenario: 1 (Demo app )
1. Calling from device A to device B: call was successful.
2. Deregistered the token in B by invalid for logout
3. Now calling from A to B - (Call Error:20104), Access Token expired or expiration date invalid.(as we have deregistered it’s also valid)

Scenario: 2 (Our main app)
1. Login in both device
2. Call from A to B (successful)
3. Logout in B
4. Call from A to B (not available)
5. Again login in to device B with a successful registration message.
6. Now calling from device A to B ((Call Error:20104), Access Token expired or expiration date invalid)
7. The above point 6 should work but it’s unexpected

The demo code works but when we are adding login and logout functions and adding the same codebase like we have created instance class for call manager to add call functionality throughout the application but this thing is causing issues in the call blocking.
Do you have any other solution for adding a file manager class for VoIP.

Xcode
13.0

iOS Version
15.0

iOS Device
iPhone XR

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavpandey130240 

The 20104 error code and its message suggests that the access token has expired when making the outbound call on client A. Please check the expiry value of the access token and make sure you are using a valid token (has not expired) when making outbound calls or registering.
