### ISSUE TITLE
How to Press Any Key for Input When working with Trail account?

### ISSUE THREAD

**Issue by trantorGurjitSingh** [twilio/voice-quickstart-ios#509]
When dealing the free given number with trail account from app, it asking to press any key to execute the code.

So how can I press the key for input. Please help. It does to showing dialling screen for outgoing call.

**Comment by bobiechen-twilio** [comment]
Hi @trantorGurjitSingh 

Please check out the [[TVOCall sendDigits:]](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TVOCall.html#//api/name/sendDigits:) method if you wish to deliver DTMF code during a call.

For account specific assistance, please contact [Twilio Support](https://support.twilio.com/hc/en-us).
