### ISSUE TITLE
Bluetooth headphones not connected unless you answer the call with them

### ISSUE THREAD

**Issue by brent-hiya** [twilio/voice-quickstart-ios#513]
### Description

When I use the TwilioVoice SDK, it does not route audio to any connected Bluetooth headphones unless you answer the call using the headphones (a button on some headsets, by double tapping on AirPods). If you just answer the VoIP call normally using the on-screen answer button, it does not seem possible to get the audio to route to the Bluetooth headphones.

If I do the same with a normal incoming call on iOS, I can answer the phone with the button and then press "speaker" to see the available headphones and switch to it.

I found this issue https://github.com/twilio/voice-quickstart-ios/issues/135 which suggests using the headset button to answer the call but I am afraid most users would not know to do this.

Is there a way to programmatically set the audio route to bluetooth?

#### Code

If I answer the device with the bluetooth headset, the device properly shows up in 

```swift
AVAudioSession.sharedInstance().currentRoute.outputs
```

But if I answer via the button on the screen, no bluetooth device is listed there and I cannot seem to access it.

#### Voice iOS SDK

version: 6.4.3 vis CocoaPods

#### Xcode

14.0.1

#### iOS Version

16.0

**Comment by chetan1406** [comment]
facing same issue
