### ISSUE TITLE
VOIP notification not receiving on incoming call

### ISSUE THREAD

**Issue by hgomnist** [twilio/voice-quickstart-ios#514]
### Description

I am using this quickstart app's code in my app for calling. I have enabled background mode and voip in the capabilities, but I am still not receiving call VoIP notifications. Everything looks okay from the console.

#### Voice iOS SDK

  - TwilioVoice (6.2.2)

#### Xcode
14.0

#### iOS Version
16.1

#### iOS Device
iphone x

**Comment by bobiechen-twilio** [comment]
Please make sure you are following the example code in the quickstart, especially the part that initiates the PushKit instance in the frontmost component of the app ([AppDelegate](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/AppDelegate.swift#L24) for example), that way the PkPushRegistry instance can be created to handle the VoIP push notifications when the app is launched from the previously terminated state.

Please reach out to the [Twilio Support](https://support.twilio.com/hc/en-us) with a Twilio Call SID (you can find them in the Twilio developer console) if you believe the call is successfully made but the push notification is never delivered to the mobile client, which rarely happens without an error being logged in the developer console.

-bobie
