### ISSUE TITLE
Question: Need help with making a call from a test app to a SIP-phone.

### ISSUE THREAD

**Issue by yRerikh** [twilio/voice-quickstart-ios#523]
Hello, thank you for your sample app.
I have faced with one problem.
I have a trial account and the test app works fine with a test incoming call.
But when I try to make a call from the app to a SIP-phone (a free phone number is used from Twilio console) there is an error **13214 - Dial: Invalid callerId value**.

Should I use upgraded account for that action or there are some special configurations that allow making a such call by using trial account?

Please advice.

**Comment by bobiechen-twilio** [comment]
Hi @yRerikh 

Thanks for reaching out.
I have not found any specific `callerId` example in the <Dial><SIP> TwiML documentation, but you can open a ticket at [Twilio Support](https://www.twilio.com/docs/voice/twiml/dial#callerid) for generic Twilio assistance.

**Comment by yRerikh** [comment]
@bobiechen-twilio I see that you have closed the issue, but I have faced with a bit different problem.
I would like to make a call from an iOS application to a SIP-phone.
Here is an example how to make a call to a SIP-phone:
https://www.twilio.com/docs/voice/tutorials/how-to-route-calls-to-your-sip-network.
I used **curl** example and it seems to be working fine, 
but when I tried to implement something similar with the sample of iOS application I failed.
Here are some logs (there is a hidden SIP domain):

**Status**: **No Answer** 
**Direction**: **Outgoing Dial** 
**From**: **client:alice**
**To**: **client:sip:XXXXXX@XXXXX.XXXX.XXXX.XXXX.com** 
**Call type**: **Client** 
**Duration**: **0 sec**
**STIR Status**: **-**

Please advice.

**Comment by bobiechen-twilio** [comment]
Hi @yRerikh 

Since this is the SDK quickstart repository, I would encourage you to reach out to Twilio Support if you need general Programmable Voice related assistance.

From the log you provided it seems an additional `client:` is added to your SIP callee. I have a feeling it should work once it's removed.

**Comment by yRerikh** [comment]
@bobiechen-twilio thank for advice.
