### ISSUE TITLE
Not able to reject call

### ISSUE THREAD

**Issue by liyamahendra** [twilio/voice-quickstart-ios#526]
### Description

The main bug is - when we have an active Twilio call and the user receives a normal PSTN call, the active Twilio call goes blank - no audio is audible on either side.

To resolve this issue, we decided to end the new incoming call programatically and I'm successfully able to detect an incoming PSTN call. But when I try to end the call, I get error saying:

```
EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)
```

### Steps to Reproduce

1. Start an active VoIP call, lets say from Device A to Device B
2. Now use another device C to call Device A 
3. The audio goes blank for both Device A and Device B while the call from Device C is ringing.

#### Code

```
self.callObserver = [[CXCallObserver alloc] init];
[self.callObserver setDelegate:self queue:dispatch_get_main_queue()];
```

```
- (void)callObserver:(nonnull CXCallObserver *)callObserver callChanged:(nonnull CXCall *)call {
    // isCallInProgress static variable tracks if a VoIP call is active and I verified its value - works as expected
    if(isCallInProgress) {
        if(!call.isOutgoing && !call.hasConnected && !call.hasEnded) {
            NSLog(@"*** New incoming call detected while a call is in progress - so reject it");
            dispatch_async(dispatch_get_main_queue(), ^{
                CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:call.UUID];
                CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];

                CXCallController *controller = [[CXCallController alloc] init];
                [controller requestTransaction:transaction completion:^(NSError *error) {
                    if (error) {
                        NSLog(@"*** EndCallAction transaction request failed: %@", [error localizedDescription]);
                    }
                    else {
                        NSLog(@"*** EndCallAction transaction request successful");
                    }
                }];
            });
        }
    }
} 
```

#### Expected Behavior

1. Originally, the audio call should be audible on both end until the new incoming call in accepted.
2. Should be able to reject the incoming PSTN call when we choose to

#### Actual Behavior

1. The active audio call goes blank when a new incoming call arrives (both PSTN and a new VoIP call)
2. Not able to reject a new PSTN call

#### Reproduces How Often

100% of the time

#### Twilio Call SID(s)

`CA500408cb6f2c1424e8fe1c19e0377035`

#### Logs

[twilio-debug-log.txt](https://github.com/twilio/voice-quickstart-ios/files/10948700/twilio-debug-log.txt)

#### Voice iOS SDK

5.5.2 via CocoaPods

#### Xcode

Version 14.2 (14C18)

#### iOS Version

16.3.1

#### iOS Device

iPhone 12

**Comment by liyamahendra** [comment]
The UUID submitted to the`CXEndCallAction` action was directly from the detected PSTN call via the `- (void)callObserver:(nonnull CXCallObserver *)callObserver callChanged:(nonnull CXCall *)call` delegate method.

Do you see any reason why the UUID obtained from the delegate callback wouldn't be valid?

**Comment by bobiechen-twilio** [comment]
The UUID needs to be valid to CallKit - the `request error code 4` typically means the call/UUID is no longer in the CallKit records due to incorrect process of reporting updates (e.g. new incoming call, call connected, etc.) to CallKit.

**Comment by liyamahendra** [comment]
@bobiechen-twilio I'm afraid none of your comment really helps - I understand what error code 4 means, what I don't get is why would the call's UUID which was detected in the `callChanged` delegate method give an invalid UUID error. Do you've a specific comment about this?

On another note, rejecting call was a work around we opted to do. Any comment about the main bug we reported:

1. Start an active VoIP call, lets say from Device A to Device B
2. Now use another device C to call Device A
3. The audio goes blank for both Device A and Device B while the call from Device C is ringing.

**Comment by bobiechen-twilio** [comment]
CallKit has a sophisticated system of keeping records of Call UUIDs and requires the application to follow. The UUID might be valid from the application/SDK perspective (i.e. the same UUID used throughout the lifecycle of the call), but CallKit might not recognize the UUID due to the process of updating various call states to CallKit, e.g. the application missed reporting the event to CallKit when the call is connected. Please refer to the Apple CallKit documentation for the best practice.

By the way, are you able to reproduce the same error using the quickstart?

For the 3rd call interruption scenario, does the application receive callback events from the CallKit framework indicating that the first call (A-B) will be put on hold or the AVAudioSession will be deactivated?
