### ISSUE TITLE
Nothing happens when I tap the green system phone icon on the top-left corner of the screen

### ISSUE THREAD

**Issue by JohnRoxMySox23** [twilio/voice-quickstart-ios#532]
### Description

I am using Twilio Voice SDK, and I am able to receive a call from the server (where Twilio SDK has also been implemented) :

![1](https://github.com/twilio/voice-quickstart-ios/assets/103497627/b74a96eb-8c03-41ec-aa7b-3300e4b27f4e)

I correctly receive the call and am able to discuss, but when I try to tap the green system phone icon on the top-left of the screen, nothing happens. 

![2](https://github.com/twilio/voice-quickstart-ios/assets/103497627/c2328992-b9cf-4881-8ec3-3e2e577ebfe9)

I realized that doing the same thing from outside the app opens the app. 

My question is, is there a way to open a default, system call view when tapping the green phone icon?

Thank you for your help

**Comment by bobiechen-twilio** [comment]
Hi @JohnRoxMySox23 

Thanks for reaching out and glad you are able to make the calls work!
I believe this is the how the behavior is designed by iOS and unfortunately not controllable from the SDK.

-bobie
