### ISSUE TITLE
performVoiceCall() failed

### ISSUE THREAD

**Issue by m-shakeel-techelix** [twilio/voice-quickstart-ios#541]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

I just downloaded this and change the token and put my number to call but as call initiates it gets failed and i got this in log.

2023-08-03 16:39:38.954911+0500 SwiftVoiceQuickstart[4634:250451] callDidStartRinging:
2023-08-03 16:39:43.256621+0500 SwiftVoiceQuickstart[4634:250451] Call failed to connect: Decline
2023-08-03 16:39:43.257026+0500 SwiftVoiceQuickstart[4634:250451] performVoiceCall() failed

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Twilio Call SID(s)

You can find the Call SID in the SDK from TVOCall.sid or TVOCallInvite.callSid. The Call SID can also be found on the Twilio Calls Console: https://www.twilio.com/console/voice/calls/logs.

#### Logs

```
// Log output when the issue occurs
2023-08-03 16:39:38.954911+0500 SwiftVoiceQuickstart[4634:250451] callDidStartRinging:
2023-08-03 16:39:43.256621+0500 SwiftVoiceQuickstart[4634:250451] Call failed to connect: Decline
2023-08-03 16:39:43.257026+0500 SwiftVoiceQuickstart[4634:250451] performVoiceCall() failed

```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bobiechen-twilio** [comment]
Hi @m-shakeel-techelix 

Thanks for reaching out. Are you able to see more detailed information with higher SDK logging level? From the debug messages you provided it looks like either callee did not answer the call, or the TwiML response returned from your app server might be invalid. For the latter case, you might see some error notification in the Twilio developer console or a notification email.

-bobie
