### ISSUE TITLE
Duplicate LC_RPATH are deprecated ('@executable_path/Frameworks') using Xcode 15

### ISSUE THREAD

**Issue by MirceaX2Mobile** [twilio/voice-quickstart-ios#544]
### Description

While running an empty project with a single pod `TwilioVoice` (latest version 6.9.0) using CocoaPods 1.12.1 and Xcode 15.0 (15A240d) you get this warning
`Duplicate LC_RPATH are deprecated ('@executable_path/Frameworks')`

### Steps to Reproduce

1. Just build an simple iOS project having a single pod `TwilioVoice` using Xcode 15.0

Initially Xcode doesn't specify which binary generates this warning, to find out it I copy compile command from Xcode's build log and run it directly in the terminal, adding argument for additional linker logging:
`-t      Logs each file (object, archive, or dylib) the linker loads.  Useful for debugging problems with search paths where the wrong library is loaded.`

` /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -t ....very long args list....`

And then you get this, so you can see that TwilioVoice is generating this warning.

`/Users/mirceadragota/Library/Developer/Xcode/DerivedData/VerityIQ-Student-giqoehcyzzzwrifauqaclxsfnaxa/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/TwilioVoice/TwilioVoice.framework/TwilioVoice
ld: warning: duplicate LC_RPATH are deprecated ('@executable_path/Frameworks')`

I found out that this warning occurs in other frameworks too [https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/251](url)
#### Expected Behavior

Compilation completes without warnings

#### Actual Behavior

Compilation completes with following warnings:
`Duplicate LC_RPATH are deprecated ('@executable_path/Frameworks')`

#### Reproduces How Often

100%

#### Logs

`/Users/mirceadragota/Library/Developer/Xcode/DerivedData/VerityIQ-Student-giqoehcyzzzwrifauqaclxsfnaxa/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/TwilioVoice/TwilioVoice.framework/TwilioVoice
ld: warning: duplicate LC_RPATH are deprecated ('@executable_path/Frameworks')`

### Versions

6.9.0

#### Xcode

15.0

#### iOS Version

17.0

#### iOS Device

iPhone 15 Pro

**Comment by bobiechen-twilio** [comment]
@MirceaX2Mobile 

Thanks for reaching out. We will investigate immediately.

**Comment by MirceaX2Mobile** [comment]
Any updates on this?

**Comment by rockgard3n** [comment]
any update on this?

**Comment by dipankadas** [comment]
Hi, we have tried with our Quickstart with Xcode 15.2 and SDK version 6.10.0 and we don't see this warning. Can you please confirm if you are still seeing this issue with the latest version of the SDK and Xcode 15.2?

**Comment by bobiechen-twilio** [comment]
Closing as answered
