### ISSUE TITLE
Incoming calls notification not working on iOS

### ISSUE THREAD

**Issue by davidsquarev** [twilio/voice-quickstart-ios#546]
### Description

We built our app for years and noticed the iOS version can't receive any incoming calls recently, but android version is no problem.

### Steps to Reproduce

give a VoIP call from iOS/Android app to a iOS app

#### Expected Behavior

VoIP push notification arrives at `didReceiveIncomingPushWith`

#### Actual Behavior

`didReceiveIncomingPushWith` is not triggered.

#### Reproduces How Often

100%

#### Twilio Call SID(s)

CAa08c76f4d42215911f70660ca4a692f3
CAaf3da4ba2f27ee7687fb35513dbe195d

#### Voice iOS SDK

6.0.2

#### Xcode

13.4.1

#### iOS Version

12.5.7

#### iOS Device

ipad air

**Comment by bobiechen-twilio** [comment]
Hi @davidsquarev 

Thanks for providing Call SIDs. From what I can see, the push notification deliveries requested in the Twilio `52131 Invalid APNs credentials` error, which is most likely caused by the expired VoIP certificate, given that it only started to fail recently.

**Comment by davidsquarev** [comment]
Thanks so much! I have updated it and solved the problem. you could close it now.
Very appreciated!

**Comment by wmt-raj-mobile** [comment]
i'm getting success message from this method 
""" 
 TwilioVoiceSDK.register(accessToken: accessToken, deviceToken: cachedDeviceToken) { error in
        if let error = error {
            NSLog("An error occurred while registering: \(error.localizedDescription)")
        } else {
            NSLog("Successfully registered for VoIP push notifications.")                
        }
    }

"""
and my certificate is also not expired but still getting

"52131 - Invalid APNs credentials" this error 

Please HELP!
