### ISSUE TITLE
Not Getting Incoming Voice Notification

### ISSUE THREAD

**Issue by wmt-raj-mobile** [twilio/voice-quickstart-ios#547]
'm getting success message from this method
"""
TwilioVoiceSDK.register(accessToken: accessToken, deviceToken: cachedDeviceToken) { error in
if let error = error {
NSLog("An error occurred while registering: (error.localizedDescription)")
} else {
NSLog("Successfully registered for VoIP push notifications.")
}
}

"""
and my certificate is also not expired but still getting

"52131 - Invalid APNs credentials" this error

Please HELP!

**Comment by bobiechen-twilio** [comment]
Hi @wmt-raj-mobile 

From the error code most likely the certificate or key in the Push Credential is incorrect or the format is not valid. Please make sure you followed the [quickstart quide](https://github.com/twilio/voice-quickstart-ios#bullet6) for retrieving the credentials out of the VoIP Certificate.

**Comment by wmt-raj-mobile** [comment]
I have followed [Quickstart Quide](https://github.com/twilio/voice-quickstart-ios#bullet6) and made certificates accordingly, but still getting ""52131 - Invalid APNs credentials" this error" and Twilio SDK also returning success message "Successfully registered for VoIP push notifications" Can you please healp me with this

**Comment by bobiechen-twilio** [comment]
Hi @wmt-raj-mobile 

The successful registration message from the SDK means the account credentials in the access token and the PushKit device token passed in the `register()` method are valid, but the certificate information stored in the Push Credential might not be valid and Twilio was not able to send the push notification request to APNS successfully.

Please check that you have copied
- Certificate: From `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`
- Key: From `-----BEGIN PRIVATE KEY-----` to `-----END PRIVATE KEY-----`
when filling the APN Push Credential in the developer console. Also make sure the sandbox option is configured correctly according to the iOS app development environment (see quickstart instructions)

**Comment by wmt-raj-mobile** [comment]
Ok i think it was cache issue i removed the existing push creds ids and added new one from twilio and its starts working
