### ISSUE TITLE
Getting Voice Notification Eventhough call is active

### ISSUE THREAD

**Issue by wmt-raj-mobile** [twilio/voice-quickstart-ios#550]
How do i restrict call notification if call is already active. For Eg : If there is ongoing call between person A and person B now if person C calls person A then person A should not receive call notification if there is ongoing call

**Comment by bobiechen-twilio** [comment]
Hi @wmt-raj-mobile 

Currently Programmable Voice does not restrict calls to a client who is already in an active call. The application can decide what to do with the subsequent incoming call notification.
