### ISSUE TITLE
No Such Module 'TwilioVoice'

### ISSUE THREAD

**Issue by wmt-raj-mobile** [twilio/voice-quickstart-ios#553]
i am getting this error in Xcode 15.2 "No Such Module 'TwilioVoice'" , i have runned pod install, pod update everything but getting this error

**Comment by bobiechen-twilio** [comment]
Hi @wmt-raj-mobile 

The quickstart is configured to reference the SDK using SPM. Once `pod install` is done you should be able to use the `.xcworkspace`, which has the SDK reference set up for you. Please check the Xcode project settings in case the app cannot find the SDK.

**Comment by wmt-raj-mobile** [comment]
It was not working as per your solution. But when i updated the ruby from 2.7.0 to 3.3.0 it started working.
