### ISSUE TITLE
APNs push notifications registration issue

### ISSUE THREAD

**Issue by Punit30** [twilio/voice-quickstart-ios#556]
### Description
Seeking assistance / advice on resolving a APNs VOiP notification issue.

VOiP notification service is not being registered after it gets unregistered and I have to restart the application. 

I am developing an application using Flutter, and I've noticed that when I initially launch the application, everything works well. However, upon logging out and subsequently unregistering the VoIP notifications, if I attempt to log in again without closing the application, the VoIP notifications fail to register. Additionally, my application features multiple phone numbers, requiring VoIP notification registration and unregistration for each. Unfortunately, this process yields the same unfavorable outcome.

### Steps to Reproduce

1. Register Device using accessToken
2. Unregister Device
3. Try to register device again without closing the application

#### Code

I am using a flutter library named as twilio_voice which invoke all the method of twilio IOS SDK.

#### Expected Behavior

VOiP notification service should be registered again without closing and reopening the application

#### Actual Behavior

VOiP notification service does not registered again after unregistered once and have to restart the application

#### Reproduces How Often

It reproduce every time

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

flutter package twilio_voice version: 0.1.3

#### Xcode

XCode version  - 15.0.1

#### iOS Version

version - 17.3.1

#### iOS Device

device - Iphone 13

**Comment by Punit30** [comment]
@dipankadas @kbagchiGWC  Could you please let me know if there have been any updates on this?

**Comment by dipankadas** [comment]
@Punit30 Can you please give us your account sid? If you don't want to share your account sid here, please file a support ticket with it and please provide the support ticket link here.

**Comment by dipankadas** [comment]
@Punit30 Also any log regarding the registration failure will be helpful

**Comment by Punit30** [comment]
@dipankadas Thank you for reply.

Please find ticket id below.
Ticket ID: #15932834

I am getting error logs. It only shows "Succesfully registered for VoIP APN push notifications" when I register the device for the first time after the application gets opened but is does not appear when I unregister the device and try to register it again.

Also, I have a multiple number feature implemented for which device registration and unregistration is important.

**Comment by dipankadas** [comment]
@Punit30 We have looked at your binding request and we just see handful of binding create and binding delete requests. So we have tested multiple binding create and delete on our end and we don't see any issues so far. 

Can you please enable SDK logging and give us the full log for `registration success` -> `unregister` -> `registration failure`?

**Comment by dipankadas** [comment]
Closing this.
