### ISSUE TITLE
DefaultAudioDevice' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by sumit-vts** [twilio/voice-quickstart-ios#558]
In our project, we've successfully implemented Twilio video calls. We're now integrating the Twilio Voice framework as well. However, we've encountered an error: 'DefaultAudioDevice' is ambiguous for type lookup in this context.

import TwilioVideo
import CallKit
import TwilioVoice

var audioDevice: DefaultAudioDevice = DefaultAudioDevice()

I tried with TwilioVideoSDK.DefaultAudioDevice() but its throw the following error: "Type 'TwilioVideoSDK' has no member 'DefaultAudioDevice'"

**Comment by bobiechen-twilio** [comment]
Hi @sumit-vts 

Thanks for reaching out. We will take a look and keep you updated.

**Comment by bobiechen-twilio** [comment]
Hi @sumit-vts 

Are you able to successfully build and run the app by adding `TwilioVoice` in front of `DefaultAudioDevice`?

```
var audioDevice = TwilioVoice.DefaultAudioDevice()
```
