### ISSUE TITLE
Hi @mrchauhan2802

### ISSUE THREAD

**Issue by Gangadhar1806** [twilio/voice-quickstart-ios#559]
Hi @mrchauhan2802 

There are different ways that the SDK may receive the 603 response. One possible reason is that the TwiML response returned from your app server is invalid. Can you check if you are receiving related errors in the [debugger of your Twilio dev console](https://www.twilio.com/console/debugger?quickDate=24)? We can also help with that if you can provide us the Twilio Call SID when you receive this error.

Thanks,
-bobie

_Originally posted by @bobiechen-twilio in https://github.com/twilio/voice-quickstart-ios/issues/337#issuecomment-616687938_

**Comment by Gangadhar1806** [comment]
Hi team,

Now I am facing the below issue, when I try to use Twilio voice call SDK. Please let me know, how to fix this one and make call functionality from iOS side.

error
(NSError) 0x0000600000c728b0 domain: "com.twilio.voice.error" - code: 31603 {
  _userInfo = 0x0000600000279f60
}

Call disconnected without error
call SID CAe398f5de69351eb13d66f7059565919f
sender call id: 
received call id: 
Call status: TVOCallState(rawValue: 4)

**Comment by bobiechen-twilio** [comment]
Hi @Gangadhar1806 

Thanks for reaching out.
I've checked the Call SID and it looks like something went wrong when Twilio tried to fetch the TwiML from your app endpoint. Please check the URL that is associated with the Application SID (ending with `ad79`) and make sure it is returning valid TwiML responses.

Please reach out to the [Twilio Help Center](https://help.twilio.com/) if you need assistance with the TwiML setup.
