### ISSUE TITLE
Documentation Needed - Exclude UUID to Prevent CallKit

### ISSUE THREAD

**Issue by rsynnest** [twilio/voice-quickstart-ios#564]
I spent a while trying to initiate a call without using CallKit (I'm using a custom UI). Eventually I found that I needed to remove the `uuid` parameter from `TwilioVoiceSDK.connect()` in order to make a call without Callkit.

This is somewhat obscure behavior based on the parameter name, and doesn't seem to be documented anywhere besides [this migration guide](https://github.com/twilio/voice-quickstart-ios/blob/master/Docs/migration-guide-5.x-6.x.md?plain=1#L53):

> Please note, if you are not using CallKit in your app, you must not set ConnectOptions.uuid or AcceptOptions.uuid while making or answering a call. The Voice SDK will enable the audio device for you when the uuid is nil.

I think it would be great to add this info to the [HeaderDoc for the connect method](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TwilioVoiceSDK.html#//api/name/connectWithAccessToken:delegate:), and maybe also a code comment in the Quickstart, or a note in the README.

Thanks for the open code and the transparent Issue history here, it's been very useful!

**Comment by bobiechen-twilio** [comment]
Thanks for reaching and great feedback @rsynnest. We will revisit and update the API documentation.
