### ISSUE TITLE
voice call issue

### ISSUE THREAD

**Issue by sumitcse27** [twilio/voice-quickstart-ios#565]
We are already on a call. During the call, there is an incoming call on the Twilio number. When we decline the incoming call, we discover that we have lost the sound of the first call. how to solve this issue in swift ios

**Comment by bobiechen-twilio** [comment]
Hi @sumitcse27 

Does this happen in your environment with the Swift quickstart? Also in your app did you receive any CallKit callbacks, for example the set-held-call action or audio-session-activated events?
