### ISSUE TITLE
Outgoing call doesn't disconnect properly

### ISSUE THREAD

**Issue by talalt** [twilio/voice-quickstart-ios#67]
### Description

Hello, dear Twilio team. I have a problem with outgoing calls. When I make a call from my app to GSM number, it calls properly, but when receiver hang up the call, in my app the call doesn't finish, and **callDidDisconnect** function doesn't get call. My app still calling, and finish after receiver hang up call after two-three times.  

#### Expected Behavior

I expect to finish call properly

#### Reproduces How Often

20-30%

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta16 via CocoaPods]

#### Xcode

[e.g. 8.3.1]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6]

**Comment by bchen-twilio** [comment]
Hi @talalt 

Thanks reporting the issue.
Can you provide us the Call-SID (you can find it in the `TVOCall.sid` object once the call is connected) when you are experiencing the issue? We can use the Call-SID to dig up more information about the lifecycle of the call and see what happened. 

A better way of providing us debugging info is to enable `TVOLogLevelVerbose` log-level of the SDK and send the debug log to us. We don't want to post any of your credentials here publicly so please go to [Twilio Support](https://support.twilio.com/hc/en-us) and create a ticket. Please tag the ticket with Programmable Voice iOS SDK and bchen so that the support experts know where to forward the issue.

Thanks
-bobie

**Comment by talalt** [comment]
Hi @bchen-twilio 

Thanks for your answer.
Call-SID: CAe6d270443918d77a9c7248e9b0bf6906

Log file:  [twilio-log.txt](https://github.com/twilio/voice-quickstart-swift/files/1339597/twilio-log.txt)

Also I usually faced with problem described [here](https://github.com/twilio/voice-quickstart-swift/issues/60). I use TwilioVoice 2.0.0-beta16 via CocoaPods. Could you please look that problem too? Thanks!

**Comment by bchen-twilio** [comment]
Hi @talalt 

Thanks for providing us the Call-SID and SDK log.
From the log I can actually see the client getting the disconnected-by-remote event and the call did end properly. Did you get any `TVOCallDelegate` callbacks (call disconnected or failed) in this call?

**Comment by talalt** [comment]
Hi @bchen-twilio 

Yes, call disconnects, but before that the receiver needs to hang up two-three times, because after first hang up, the call continues to calling. I didn't get any callbacks when receiver hangs up the call.

**Comment by bchen-twilio** [comment]
Hi @talalt 

If I am understanding this correctly, the situation you are seeing is:
- the receiver (GSM phone number) hangs up the call
- the call on the SDK client side (mobile app) doesn't get disconnected immediately
- even if the call is disconnected (on the mobile side) eventually, you never get the `callDidDisconnect:` callback?

thanks,
bobie

**Comment by talalt** [comment]
Hi @bchen-twilio 

Yes, situation looks like that, except that when the call disconnects properly, I properly get _callDidDisconnect:_ callback. No problem with that. Also when receiver hangs up the call, call disconnects on his side, but not on the mobile side. And after few seconds call ring on the receiver side again. Thanks!

**Comment by bchen-twilio** [comment]
Hi @talalt 

Thanks for the update.
Based on your description I think this is beyond the SDK can handle. Could you please reach out to the [Twilio Support](https://support.twilio.com/hc/en-us/requests/new) and open a ticket with the Call-SIDs that you are experiencing problematic calls. We experts from the Voice service team to dig up more insights why the calls behaved weirdly.

Thanks
bobie

**Comment by bchen-twilio** [comment]
Hi @talalt 

How are things? I am wondering if you application is still experiencing connection callback issues?

-bobie

**Comment by logesh45** [comment]
I have the same issue, the callback is never called.also I noticed **call.delegate = self** cannot be used since it is a get-only property

**Comment by bchen-twilio** [comment]
Hi @logesh45 

Please use Twilio Support to open a new ticket with the SDK (verbose log level) log so we can take a look why the delegate didn't get the callback.

The attribute of the `TVOCallDelegate` is intentionally designed that way so you will need to provide the `delegate` when making or accepting calls.

Thanks.

**Comment by piyushtank** [comment]
We had redesigned the entire SDK in 3.x. The latest version of SDK is 5.2.0. See changelogs for 5.2.0 [here](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#520). I

Closing an old ticket. Feel free to reopen if you still run into the same issue or have any questions.

**Comment by Nisha-spaceo** [comment]
Hello
I am still facing issues while an outgoing call is disconnected from another side. I am using latest sdk version.

**Comment by bobiechen-twilio** [comment]
Hi @Nisha-spaceo,

Any chance you have the Call SID of such call? We can use that to check the signaling records and the TwiML so we can help you resolve the issue.
