### ISSUE TITLE
Trouble finding how to access the audio streams

### ISSUE THREAD

**Issue by jtokoph** [twilio/voice-quickstart-ios#74]
I'm having trouble finding a way to access the raw audio streams of the active call. Is that not made available? We would like to be able to do some live recording/transcription on the device. Is there any way to access the incoming/outgoing audio streams?

**Comment by bchen-twilio** [comment]
Hi @jtokoph 

Being able to access the incoming/outgoing audio streams has been one of the most popular inquiries of the Voice SDK. Currently the SDK doesn't provide the applications APIs for accessing the streams but this is definitely something we will be working on once the Voice SDK is GA.

Thanks
-bobie

**Comment by woodsnick** [comment]
Just wanted to put in another vote for access to audio streams.  We have a separate, non-Twilio, live video chat that we'd like to conference in external phone callers into.  Just looking for a way to get access to inbound / outbound audio so that we can multiplex and route as needed.  Happy to try out any beta's or early access releases as they appear.

**Comment by bchen-twilio** [comment]
Hi @woodsnick 

Thanks for the interests in the Voice SDK :). I am sure once the SDK is as stable as GA this is definitely the first thing we would be investing our time on and provide developers better experiences.

Thanks.
-bobie

**Comment by brianhans** [comment]
Hi @bchen-twilio 

Can't wait for this feature, the Twilio Voice SDK has been great so far. Do you guys have any timeline or estimated release date for when the SDK will be GA?

**Comment by woodsnick** [comment]
Hey Twilio folks, any update on this one?  Definitely still a big one on our feature want list.

**Comment by bchen-twilio** [comment]
Hi @woodsnick 

We are in the process of upgrading our media stack to provide applications better integration experience such as call quality stats, and being able to provide access to the audio stream is definitely one of them.

Thanks
-bobie

**Comment by krishnapsarthi** [comment]
Hi @bchen-twilio ,

Any updates on this feature?

**Comment by bchen-twilio** [comment]
Hi @krishnapsarthi 

We are working on the next generation API of the Programmable Voice SDK and will provide new audio APIs such as custom audio device or access to the audio streams.
Please stay tuned.

Thank
-bobie

**Comment by CallMeMeow** [comment]
Hey, do you guys have any timeline regarding the access to the audio streams?

**Comment by CallMeMeow** [comment]
Hey @bchen-twilio

Appreciate the quick answer.
Is there a road map of the iOS SDK releases? We want to transition from using Twilio Video (which seems to provide the audio streams) to Twilio Voice. But this is a deal breaker for us at this point of time. I am really interested to know this so that we can plan out our transition as well.

**Comment by bchen-twilio** [comment]
Oh oh our Video SDK experts are going to be sad...
Well only thing I can guarantee now is to let you know once the preview of next-gen Voice SDK is ready and work with you guys closely to help the transition from Video to Voice.

cheers
-bobie

**Comment by jayanth1991** [comment]
Hi @bchen-twilio, 

We just want to get access to the local audio stream, how do we go about doing that?

**Comment by alexsorokoletov** [comment]
FYI The latest preview docs can be found here: https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-preview5/docs

**Comment by gad2103** [comment]
Just to follow up on this. The only call center like software I've found that gives access to real-time audio streams is AWS connect. It would be great if any of the other companies offered something similar...

**Comment by piyushtank** [comment]
Closing the ticket as AudioDevice APIs have been already released.
